#应用信息
app:
     #版本号
     version: 1.0.6
     #名称
     title: 附件管理（高级版）
     #描述
     des: 附件管理可文件分类查看、批量删除，两种视图显示、查看文件信息、重命名、预览等可点击详细了解更多
     #标识包目录名
     name: filemanage
     #安装状态
     isinstall: true
     #安装是否为覆盖原来代码
     installcover: false
     #mod拉取依赖
     isModTidy: false
     #Vue前端依赖命令行
     commandLines: ""
     #Go后端文件路径
     goFiles: '[{"isDir":false,"path":"/app/admin/datacenter/filemanage.go"}]'
     #vue前端文件路径
     vueFiles: '[{"isDir":true,"path":"/src/views/datacenter/filemanage"}]'
     #安装Go后的app下模块控制器路径（多个,分开）
     appfolders: admin/datacenter
     #数据库表名称（多个,分开）
     packtables: 
     #菜单ID，安装后返回的ID
     adminmenuids: 83
