// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newAdminAuthDept(db *gorm.DB, opts ...gen.DOOption) adminAuthDept {
	_adminAuthDept := adminAuthDept{}

	_adminAuthDept.adminAuthDeptDo.UseDB(db, opts...)
	_adminAuthDept.adminAuthDeptDo.UseModel(&model.AdminAuthDept{})

	tableName := _adminAuthDept.adminAuthDeptDo.TableName()
	_adminAuthDept.ALL = field.NewAsterisk(tableName)
	_adminAuthDept.ID = field.NewInt32(tableName, "id")
	_adminAuthDept.TenantID = field.NewInt32(tableName, "tenant_id")
	_adminAuthDept.AccountID = field.NewInt64(tableName, "account_id")
	_adminAuthDept.Name = field.NewString(tableName, "name")
	_adminAuthDept.Pid = field.NewInt32(tableName, "pid")
	_adminAuthDept.Weigh = field.NewInt32(tableName, "weigh")
	_adminAuthDept.Status = field.NewInt8(tableName, "status")
	_adminAuthDept.Remark = field.NewString(tableName, "remark")
	_adminAuthDept.CreatedAt = field.NewTime(tableName, "created_at")
	_adminAuthDept.UpdatedAt = field.NewTime(tableName, "updated_at")
	_adminAuthDept.DeletedAt = field.NewField(tableName, "deleted_at")

	_adminAuthDept.fillFieldMap()

	return _adminAuthDept
}

// adminAuthDept 管理后台部门
type adminAuthDept struct {
	adminAuthDeptDo

	ALL       field.Asterisk
	ID        field.Int32
	TenantID  field.Int32  // 租户唯一标识
	AccountID field.Int64  // 添加账号
	Name      field.String // 部门名称
	Pid       field.Int32  // 上级部门
	Weigh     field.Int32  // 排序
	Status    field.Int8   // 状态:0=正常;1=禁用
	Remark    field.String // 备注
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (a adminAuthDept) Table(newTableName string) *adminAuthDept {
	a.adminAuthDeptDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a adminAuthDept) As(alias string) *adminAuthDept {
	a.adminAuthDeptDo.DO = *(a.adminAuthDeptDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *adminAuthDept) updateTableName(table string) *adminAuthDept {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt32(table, "id")
	a.TenantID = field.NewInt32(table, "tenant_id")
	a.AccountID = field.NewInt64(table, "account_id")
	a.Name = field.NewString(table, "name")
	a.Pid = field.NewInt32(table, "pid")
	a.Weigh = field.NewInt32(table, "weigh")
	a.Status = field.NewInt8(table, "status")
	a.Remark = field.NewString(table, "remark")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")

	a.fillFieldMap()

	return a
}

func (a *adminAuthDept) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *adminAuthDept) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 11)
	a.fieldMap["id"] = a.ID
	a.fieldMap["tenant_id"] = a.TenantID
	a.fieldMap["account_id"] = a.AccountID
	a.fieldMap["name"] = a.Name
	a.fieldMap["pid"] = a.Pid
	a.fieldMap["weigh"] = a.Weigh
	a.fieldMap["status"] = a.Status
	a.fieldMap["remark"] = a.Remark
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
}

func (a adminAuthDept) clone(db *gorm.DB) adminAuthDept {
	a.adminAuthDeptDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a adminAuthDept) replaceDB(db *gorm.DB) adminAuthDept {
	a.adminAuthDeptDo.ReplaceDB(db)
	return a
}

type adminAuthDeptDo struct{ gen.DO }

type IAdminAuthDeptDo interface {
	gen.SubQuery
	Debug() IAdminAuthDeptDo
	WithContext(ctx context.Context) IAdminAuthDeptDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAdminAuthDeptDo
	WriteDB() IAdminAuthDeptDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAdminAuthDeptDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAdminAuthDeptDo
	Not(conds ...gen.Condition) IAdminAuthDeptDo
	Or(conds ...gen.Condition) IAdminAuthDeptDo
	Select(conds ...field.Expr) IAdminAuthDeptDo
	Where(conds ...gen.Condition) IAdminAuthDeptDo
	Order(conds ...field.Expr) IAdminAuthDeptDo
	Distinct(cols ...field.Expr) IAdminAuthDeptDo
	Omit(cols ...field.Expr) IAdminAuthDeptDo
	Join(table schema.Tabler, on ...field.Expr) IAdminAuthDeptDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAdminAuthDeptDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAdminAuthDeptDo
	Group(cols ...field.Expr) IAdminAuthDeptDo
	Having(conds ...gen.Condition) IAdminAuthDeptDo
	Limit(limit int) IAdminAuthDeptDo
	Offset(offset int) IAdminAuthDeptDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminAuthDeptDo
	Unscoped() IAdminAuthDeptDo
	Create(values ...*model.AdminAuthDept) error
	CreateInBatches(values []*model.AdminAuthDept, batchSize int) error
	Save(values ...*model.AdminAuthDept) error
	First() (*model.AdminAuthDept, error)
	Take() (*model.AdminAuthDept, error)
	Last() (*model.AdminAuthDept, error)
	Find() ([]*model.AdminAuthDept, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminAuthDept, err error)
	FindInBatches(result *[]*model.AdminAuthDept, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AdminAuthDept) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAdminAuthDeptDo
	Assign(attrs ...field.AssignExpr) IAdminAuthDeptDo
	Joins(fields ...field.RelationField) IAdminAuthDeptDo
	Preload(fields ...field.RelationField) IAdminAuthDeptDo
	FirstOrInit() (*model.AdminAuthDept, error)
	FirstOrCreate() (*model.AdminAuthDept, error)
	FindByPage(offset int, limit int) (result []*model.AdminAuthDept, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAdminAuthDeptDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a adminAuthDeptDo) Debug() IAdminAuthDeptDo {
	return a.withDO(a.DO.Debug())
}

func (a adminAuthDeptDo) WithContext(ctx context.Context) IAdminAuthDeptDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a adminAuthDeptDo) ReadDB() IAdminAuthDeptDo {
	return a.Clauses(dbresolver.Read)
}

func (a adminAuthDeptDo) WriteDB() IAdminAuthDeptDo {
	return a.Clauses(dbresolver.Write)
}

func (a adminAuthDeptDo) Session(config *gorm.Session) IAdminAuthDeptDo {
	return a.withDO(a.DO.Session(config))
}

func (a adminAuthDeptDo) Clauses(conds ...clause.Expression) IAdminAuthDeptDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a adminAuthDeptDo) Returning(value interface{}, columns ...string) IAdminAuthDeptDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a adminAuthDeptDo) Not(conds ...gen.Condition) IAdminAuthDeptDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a adminAuthDeptDo) Or(conds ...gen.Condition) IAdminAuthDeptDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a adminAuthDeptDo) Select(conds ...field.Expr) IAdminAuthDeptDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a adminAuthDeptDo) Where(conds ...gen.Condition) IAdminAuthDeptDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a adminAuthDeptDo) Order(conds ...field.Expr) IAdminAuthDeptDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a adminAuthDeptDo) Distinct(cols ...field.Expr) IAdminAuthDeptDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a adminAuthDeptDo) Omit(cols ...field.Expr) IAdminAuthDeptDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a adminAuthDeptDo) Join(table schema.Tabler, on ...field.Expr) IAdminAuthDeptDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a adminAuthDeptDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAdminAuthDeptDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a adminAuthDeptDo) RightJoin(table schema.Tabler, on ...field.Expr) IAdminAuthDeptDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a adminAuthDeptDo) Group(cols ...field.Expr) IAdminAuthDeptDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a adminAuthDeptDo) Having(conds ...gen.Condition) IAdminAuthDeptDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a adminAuthDeptDo) Limit(limit int) IAdminAuthDeptDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a adminAuthDeptDo) Offset(offset int) IAdminAuthDeptDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a adminAuthDeptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminAuthDeptDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a adminAuthDeptDo) Unscoped() IAdminAuthDeptDo {
	return a.withDO(a.DO.Unscoped())
}

func (a adminAuthDeptDo) Create(values ...*model.AdminAuthDept) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a adminAuthDeptDo) CreateInBatches(values []*model.AdminAuthDept, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a adminAuthDeptDo) Save(values ...*model.AdminAuthDept) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a adminAuthDeptDo) First() (*model.AdminAuthDept, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthDept), nil
	}
}

func (a adminAuthDeptDo) Take() (*model.AdminAuthDept, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthDept), nil
	}
}

func (a adminAuthDeptDo) Last() (*model.AdminAuthDept, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthDept), nil
	}
}

func (a adminAuthDeptDo) Find() ([]*model.AdminAuthDept, error) {
	result, err := a.DO.Find()
	return result.([]*model.AdminAuthDept), err
}

func (a adminAuthDeptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminAuthDept, err error) {
	buf := make([]*model.AdminAuthDept, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a adminAuthDeptDo) FindInBatches(result *[]*model.AdminAuthDept, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a adminAuthDeptDo) Attrs(attrs ...field.AssignExpr) IAdminAuthDeptDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a adminAuthDeptDo) Assign(attrs ...field.AssignExpr) IAdminAuthDeptDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a adminAuthDeptDo) Joins(fields ...field.RelationField) IAdminAuthDeptDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a adminAuthDeptDo) Preload(fields ...field.RelationField) IAdminAuthDeptDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a adminAuthDeptDo) FirstOrInit() (*model.AdminAuthDept, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthDept), nil
	}
}

func (a adminAuthDeptDo) FirstOrCreate() (*model.AdminAuthDept, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthDept), nil
	}
}

func (a adminAuthDeptDo) FindByPage(offset int, limit int) (result []*model.AdminAuthDept, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a adminAuthDeptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a adminAuthDeptDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a adminAuthDeptDo) Delete(models ...*model.AdminAuthDept) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *adminAuthDeptDo) withDO(do gen.Dao) *adminAuthDeptDo {
	a.DO = *do.(*gen.DO)
	return a
}
