// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newAdminAuthRoleAccess(db *gorm.DB, opts ...gen.DOOption) adminAuthRoleAccess {
	_adminAuthRoleAccess := adminAuthRoleAccess{}

	_adminAuthRoleAccess.adminAuthRoleAccessDo.UseDB(db, opts...)
	_adminAuthRoleAccess.adminAuthRoleAccessDo.UseModel(&model.AdminAuthRoleAccess{})

	tableName := _adminAuthRoleAccess.adminAuthRoleAccessDo.TableName()
	_adminAuthRoleAccess.ALL = field.NewAsterisk(tableName)
	_adminAuthRoleAccess.UID = field.NewInt64(tableName, "uid")
	_adminAuthRoleAccess.RoleID = field.NewInt32(tableName, "role_id")

	_adminAuthRoleAccess.fillFieldMap()

	return _adminAuthRoleAccess
}

// adminAuthRoleAccess 业务后台菜单授权
type adminAuthRoleAccess struct {
	adminAuthRoleAccessDo

	ALL    field.Asterisk
	UID    field.Int64 // 账号id
	RoleID field.Int32 // 授权id

	fieldMap map[string]field.Expr
}

func (a adminAuthRoleAccess) Table(newTableName string) *adminAuthRoleAccess {
	a.adminAuthRoleAccessDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a adminAuthRoleAccess) As(alias string) *adminAuthRoleAccess {
	a.adminAuthRoleAccessDo.DO = *(a.adminAuthRoleAccessDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *adminAuthRoleAccess) updateTableName(table string) *adminAuthRoleAccess {
	a.ALL = field.NewAsterisk(table)
	a.UID = field.NewInt64(table, "uid")
	a.RoleID = field.NewInt32(table, "role_id")

	a.fillFieldMap()

	return a
}

func (a *adminAuthRoleAccess) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *adminAuthRoleAccess) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 2)
	a.fieldMap["uid"] = a.UID
	a.fieldMap["role_id"] = a.RoleID
}

func (a adminAuthRoleAccess) clone(db *gorm.DB) adminAuthRoleAccess {
	a.adminAuthRoleAccessDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a adminAuthRoleAccess) replaceDB(db *gorm.DB) adminAuthRoleAccess {
	a.adminAuthRoleAccessDo.ReplaceDB(db)
	return a
}

type adminAuthRoleAccessDo struct{ gen.DO }

type IAdminAuthRoleAccessDo interface {
	gen.SubQuery
	Debug() IAdminAuthRoleAccessDo
	WithContext(ctx context.Context) IAdminAuthRoleAccessDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAdminAuthRoleAccessDo
	WriteDB() IAdminAuthRoleAccessDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAdminAuthRoleAccessDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAdminAuthRoleAccessDo
	Not(conds ...gen.Condition) IAdminAuthRoleAccessDo
	Or(conds ...gen.Condition) IAdminAuthRoleAccessDo
	Select(conds ...field.Expr) IAdminAuthRoleAccessDo
	Where(conds ...gen.Condition) IAdminAuthRoleAccessDo
	Order(conds ...field.Expr) IAdminAuthRoleAccessDo
	Distinct(cols ...field.Expr) IAdminAuthRoleAccessDo
	Omit(cols ...field.Expr) IAdminAuthRoleAccessDo
	Join(table schema.Tabler, on ...field.Expr) IAdminAuthRoleAccessDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAdminAuthRoleAccessDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAdminAuthRoleAccessDo
	Group(cols ...field.Expr) IAdminAuthRoleAccessDo
	Having(conds ...gen.Condition) IAdminAuthRoleAccessDo
	Limit(limit int) IAdminAuthRoleAccessDo
	Offset(offset int) IAdminAuthRoleAccessDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminAuthRoleAccessDo
	Unscoped() IAdminAuthRoleAccessDo
	Create(values ...*model.AdminAuthRoleAccess) error
	CreateInBatches(values []*model.AdminAuthRoleAccess, batchSize int) error
	Save(values ...*model.AdminAuthRoleAccess) error
	First() (*model.AdminAuthRoleAccess, error)
	Take() (*model.AdminAuthRoleAccess, error)
	Last() (*model.AdminAuthRoleAccess, error)
	Find() ([]*model.AdminAuthRoleAccess, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminAuthRoleAccess, err error)
	FindInBatches(result *[]*model.AdminAuthRoleAccess, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AdminAuthRoleAccess) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAdminAuthRoleAccessDo
	Assign(attrs ...field.AssignExpr) IAdminAuthRoleAccessDo
	Joins(fields ...field.RelationField) IAdminAuthRoleAccessDo
	Preload(fields ...field.RelationField) IAdminAuthRoleAccessDo
	FirstOrInit() (*model.AdminAuthRoleAccess, error)
	FirstOrCreate() (*model.AdminAuthRoleAccess, error)
	FindByPage(offset int, limit int) (result []*model.AdminAuthRoleAccess, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAdminAuthRoleAccessDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a adminAuthRoleAccessDo) Debug() IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Debug())
}

func (a adminAuthRoleAccessDo) WithContext(ctx context.Context) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a adminAuthRoleAccessDo) ReadDB() IAdminAuthRoleAccessDo {
	return a.Clauses(dbresolver.Read)
}

func (a adminAuthRoleAccessDo) WriteDB() IAdminAuthRoleAccessDo {
	return a.Clauses(dbresolver.Write)
}

func (a adminAuthRoleAccessDo) Session(config *gorm.Session) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Session(config))
}

func (a adminAuthRoleAccessDo) Clauses(conds ...clause.Expression) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a adminAuthRoleAccessDo) Returning(value interface{}, columns ...string) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a adminAuthRoleAccessDo) Not(conds ...gen.Condition) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a adminAuthRoleAccessDo) Or(conds ...gen.Condition) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a adminAuthRoleAccessDo) Select(conds ...field.Expr) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a adminAuthRoleAccessDo) Where(conds ...gen.Condition) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a adminAuthRoleAccessDo) Order(conds ...field.Expr) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a adminAuthRoleAccessDo) Distinct(cols ...field.Expr) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a adminAuthRoleAccessDo) Omit(cols ...field.Expr) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a adminAuthRoleAccessDo) Join(table schema.Tabler, on ...field.Expr) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a adminAuthRoleAccessDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a adminAuthRoleAccessDo) RightJoin(table schema.Tabler, on ...field.Expr) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a adminAuthRoleAccessDo) Group(cols ...field.Expr) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a adminAuthRoleAccessDo) Having(conds ...gen.Condition) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a adminAuthRoleAccessDo) Limit(limit int) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a adminAuthRoleAccessDo) Offset(offset int) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a adminAuthRoleAccessDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a adminAuthRoleAccessDo) Unscoped() IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Unscoped())
}

func (a adminAuthRoleAccessDo) Create(values ...*model.AdminAuthRoleAccess) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a adminAuthRoleAccessDo) CreateInBatches(values []*model.AdminAuthRoleAccess, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a adminAuthRoleAccessDo) Save(values ...*model.AdminAuthRoleAccess) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a adminAuthRoleAccessDo) First() (*model.AdminAuthRoleAccess, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRoleAccess), nil
	}
}

func (a adminAuthRoleAccessDo) Take() (*model.AdminAuthRoleAccess, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRoleAccess), nil
	}
}

func (a adminAuthRoleAccessDo) Last() (*model.AdminAuthRoleAccess, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRoleAccess), nil
	}
}

func (a adminAuthRoleAccessDo) Find() ([]*model.AdminAuthRoleAccess, error) {
	result, err := a.DO.Find()
	return result.([]*model.AdminAuthRoleAccess), err
}

func (a adminAuthRoleAccessDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminAuthRoleAccess, err error) {
	buf := make([]*model.AdminAuthRoleAccess, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a adminAuthRoleAccessDo) FindInBatches(result *[]*model.AdminAuthRoleAccess, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a adminAuthRoleAccessDo) Attrs(attrs ...field.AssignExpr) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a adminAuthRoleAccessDo) Assign(attrs ...field.AssignExpr) IAdminAuthRoleAccessDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a adminAuthRoleAccessDo) Joins(fields ...field.RelationField) IAdminAuthRoleAccessDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a adminAuthRoleAccessDo) Preload(fields ...field.RelationField) IAdminAuthRoleAccessDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a adminAuthRoleAccessDo) FirstOrInit() (*model.AdminAuthRoleAccess, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRoleAccess), nil
	}
}

func (a adminAuthRoleAccessDo) FirstOrCreate() (*model.AdminAuthRoleAccess, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRoleAccess), nil
	}
}

func (a adminAuthRoleAccessDo) FindByPage(offset int, limit int) (result []*model.AdminAuthRoleAccess, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a adminAuthRoleAccessDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a adminAuthRoleAccessDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a adminAuthRoleAccessDo) Delete(models ...*model.AdminAuthRoleAccess) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *adminAuthRoleAccessDo) withDO(do gen.Dao) *adminAuthRoleAccessDo {
	a.DO = *do.(*gen.DO)
	return a
}
