// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newAdminAuthRole(db *gorm.DB, opts ...gen.DOOption) adminAuthRole {
	_adminAuthRole := adminAuthRole{}

	_adminAuthRole.adminAuthRoleDo.UseDB(db, opts...)
	_adminAuthRole.adminAuthRoleDo.UseModel(&model.AdminAuthRole{})

	tableName := _adminAuthRole.adminAuthRoleDo.TableName()
	_adminAuthRole.ALL = field.NewAsterisk(tableName)
	_adminAuthRole.ID = field.NewInt32(tableName, "id")
	_adminAuthRole.TenantID = field.NewInt32(tableName, "tenant_id")
	_adminAuthRole.AccountID = field.NewInt64(tableName, "account_id")
	_adminAuthRole.Pid = field.NewInt32(tableName, "pid")
	_adminAuthRole.Name = field.NewString(tableName, "name")
	_adminAuthRole.Rules = field.NewString(tableName, "rules")
	_adminAuthRole.Menu = field.NewString(tableName, "menu")
	_adminAuthRole.Btns = field.NewString(tableName, "btns")
	_adminAuthRole.Status = field.NewInt8(tableName, "status")
	_adminAuthRole.DataAccess = field.NewInt8(tableName, "data_access")
	_adminAuthRole.Remark = field.NewString(tableName, "remark")
	_adminAuthRole.Weigh = field.NewInt32(tableName, "weigh")
	_adminAuthRole.CreatedAt = field.NewTime(tableName, "created_at")

	_adminAuthRole.fillFieldMap()

	return _adminAuthRole
}

// adminAuthRole 权限分组
type adminAuthRole struct {
	adminAuthRoleDo

	ALL        field.Asterisk
	ID         field.Int32
	TenantID   field.Int32  // 租户唯一标识
	AccountID  field.Int64  // 添加用户id
	Pid        field.Int32  // 父级
	Name       field.String // 名称
	Rules      field.String // 规则ID 所拥有的权限包括父级
	Menu       field.String // 选择的id，用于编辑赋值
	Btns       field.String // 按钮id，用于编辑赋值
	Status     field.Int8   // 状态1=禁用
	DataAccess field.Int8   // 数据权限0=自己1=自己及子权限，2=全部
	Remark     field.String // 描述
	Weigh      field.Int32  // 排序
	CreatedAt  field.Time   // 添加时间

	fieldMap map[string]field.Expr
}

func (a adminAuthRole) Table(newTableName string) *adminAuthRole {
	a.adminAuthRoleDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a adminAuthRole) As(alias string) *adminAuthRole {
	a.adminAuthRoleDo.DO = *(a.adminAuthRoleDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *adminAuthRole) updateTableName(table string) *adminAuthRole {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt32(table, "id")
	a.TenantID = field.NewInt32(table, "tenant_id")
	a.AccountID = field.NewInt64(table, "account_id")
	a.Pid = field.NewInt32(table, "pid")
	a.Name = field.NewString(table, "name")
	a.Rules = field.NewString(table, "rules")
	a.Menu = field.NewString(table, "menu")
	a.Btns = field.NewString(table, "btns")
	a.Status = field.NewInt8(table, "status")
	a.DataAccess = field.NewInt8(table, "data_access")
	a.Remark = field.NewString(table, "remark")
	a.Weigh = field.NewInt32(table, "weigh")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *adminAuthRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *adminAuthRole) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 13)
	a.fieldMap["id"] = a.ID
	a.fieldMap["tenant_id"] = a.TenantID
	a.fieldMap["account_id"] = a.AccountID
	a.fieldMap["pid"] = a.Pid
	a.fieldMap["name"] = a.Name
	a.fieldMap["rules"] = a.Rules
	a.fieldMap["menu"] = a.Menu
	a.fieldMap["btns"] = a.Btns
	a.fieldMap["status"] = a.Status
	a.fieldMap["data_access"] = a.DataAccess
	a.fieldMap["remark"] = a.Remark
	a.fieldMap["weigh"] = a.Weigh
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a adminAuthRole) clone(db *gorm.DB) adminAuthRole {
	a.adminAuthRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a adminAuthRole) replaceDB(db *gorm.DB) adminAuthRole {
	a.adminAuthRoleDo.ReplaceDB(db)
	return a
}

type adminAuthRoleDo struct{ gen.DO }

type IAdminAuthRoleDo interface {
	gen.SubQuery
	Debug() IAdminAuthRoleDo
	WithContext(ctx context.Context) IAdminAuthRoleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAdminAuthRoleDo
	WriteDB() IAdminAuthRoleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAdminAuthRoleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAdminAuthRoleDo
	Not(conds ...gen.Condition) IAdminAuthRoleDo
	Or(conds ...gen.Condition) IAdminAuthRoleDo
	Select(conds ...field.Expr) IAdminAuthRoleDo
	Where(conds ...gen.Condition) IAdminAuthRoleDo
	Order(conds ...field.Expr) IAdminAuthRoleDo
	Distinct(cols ...field.Expr) IAdminAuthRoleDo
	Omit(cols ...field.Expr) IAdminAuthRoleDo
	Join(table schema.Tabler, on ...field.Expr) IAdminAuthRoleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAdminAuthRoleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAdminAuthRoleDo
	Group(cols ...field.Expr) IAdminAuthRoleDo
	Having(conds ...gen.Condition) IAdminAuthRoleDo
	Limit(limit int) IAdminAuthRoleDo
	Offset(offset int) IAdminAuthRoleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminAuthRoleDo
	Unscoped() IAdminAuthRoleDo
	Create(values ...*model.AdminAuthRole) error
	CreateInBatches(values []*model.AdminAuthRole, batchSize int) error
	Save(values ...*model.AdminAuthRole) error
	First() (*model.AdminAuthRole, error)
	Take() (*model.AdminAuthRole, error)
	Last() (*model.AdminAuthRole, error)
	Find() ([]*model.AdminAuthRole, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminAuthRole, err error)
	FindInBatches(result *[]*model.AdminAuthRole, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AdminAuthRole) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAdminAuthRoleDo
	Assign(attrs ...field.AssignExpr) IAdminAuthRoleDo
	Joins(fields ...field.RelationField) IAdminAuthRoleDo
	Preload(fields ...field.RelationField) IAdminAuthRoleDo
	FirstOrInit() (*model.AdminAuthRole, error)
	FirstOrCreate() (*model.AdminAuthRole, error)
	FindByPage(offset int, limit int) (result []*model.AdminAuthRole, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAdminAuthRoleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a adminAuthRoleDo) Debug() IAdminAuthRoleDo {
	return a.withDO(a.DO.Debug())
}

func (a adminAuthRoleDo) WithContext(ctx context.Context) IAdminAuthRoleDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a adminAuthRoleDo) ReadDB() IAdminAuthRoleDo {
	return a.Clauses(dbresolver.Read)
}

func (a adminAuthRoleDo) WriteDB() IAdminAuthRoleDo {
	return a.Clauses(dbresolver.Write)
}

func (a adminAuthRoleDo) Session(config *gorm.Session) IAdminAuthRoleDo {
	return a.withDO(a.DO.Session(config))
}

func (a adminAuthRoleDo) Clauses(conds ...clause.Expression) IAdminAuthRoleDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a adminAuthRoleDo) Returning(value interface{}, columns ...string) IAdminAuthRoleDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a adminAuthRoleDo) Not(conds ...gen.Condition) IAdminAuthRoleDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a adminAuthRoleDo) Or(conds ...gen.Condition) IAdminAuthRoleDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a adminAuthRoleDo) Select(conds ...field.Expr) IAdminAuthRoleDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a adminAuthRoleDo) Where(conds ...gen.Condition) IAdminAuthRoleDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a adminAuthRoleDo) Order(conds ...field.Expr) IAdminAuthRoleDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a adminAuthRoleDo) Distinct(cols ...field.Expr) IAdminAuthRoleDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a adminAuthRoleDo) Omit(cols ...field.Expr) IAdminAuthRoleDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a adminAuthRoleDo) Join(table schema.Tabler, on ...field.Expr) IAdminAuthRoleDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a adminAuthRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAdminAuthRoleDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a adminAuthRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) IAdminAuthRoleDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a adminAuthRoleDo) Group(cols ...field.Expr) IAdminAuthRoleDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a adminAuthRoleDo) Having(conds ...gen.Condition) IAdminAuthRoleDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a adminAuthRoleDo) Limit(limit int) IAdminAuthRoleDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a adminAuthRoleDo) Offset(offset int) IAdminAuthRoleDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a adminAuthRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminAuthRoleDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a adminAuthRoleDo) Unscoped() IAdminAuthRoleDo {
	return a.withDO(a.DO.Unscoped())
}

func (a adminAuthRoleDo) Create(values ...*model.AdminAuthRole) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a adminAuthRoleDo) CreateInBatches(values []*model.AdminAuthRole, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a adminAuthRoleDo) Save(values ...*model.AdminAuthRole) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a adminAuthRoleDo) First() (*model.AdminAuthRole, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRole), nil
	}
}

func (a adminAuthRoleDo) Take() (*model.AdminAuthRole, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRole), nil
	}
}

func (a adminAuthRoleDo) Last() (*model.AdminAuthRole, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRole), nil
	}
}

func (a adminAuthRoleDo) Find() ([]*model.AdminAuthRole, error) {
	result, err := a.DO.Find()
	return result.([]*model.AdminAuthRole), err
}

func (a adminAuthRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminAuthRole, err error) {
	buf := make([]*model.AdminAuthRole, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a adminAuthRoleDo) FindInBatches(result *[]*model.AdminAuthRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a adminAuthRoleDo) Attrs(attrs ...field.AssignExpr) IAdminAuthRoleDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a adminAuthRoleDo) Assign(attrs ...field.AssignExpr) IAdminAuthRoleDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a adminAuthRoleDo) Joins(fields ...field.RelationField) IAdminAuthRoleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a adminAuthRoleDo) Preload(fields ...field.RelationField) IAdminAuthRoleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a adminAuthRoleDo) FirstOrInit() (*model.AdminAuthRole, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRole), nil
	}
}

func (a adminAuthRoleDo) FirstOrCreate() (*model.AdminAuthRole, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRole), nil
	}
}

func (a adminAuthRoleDo) FindByPage(offset int, limit int) (result []*model.AdminAuthRole, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a adminAuthRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a adminAuthRoleDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a adminAuthRoleDo) Delete(models ...*model.AdminAuthRole) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *adminAuthRoleDo) withDO(do gen.Dao) *adminAuthRoleDo {
	a.DO = *do.(*gen.DO)
	return a
}
