// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newAdminAuthRule(db *gorm.DB, opts ...gen.DOOption) adminAuthRule {
	_adminAuthRule := adminAuthRule{}

	_adminAuthRule.adminAuthRuleDo.UseDB(db, opts...)
	_adminAuthRule.adminAuthRuleDo.UseModel(&model.AdminAuthRule{})

	tableName := _adminAuthRule.adminAuthRuleDo.TableName()
	_adminAuthRule.ALL = field.NewAsterisk(tableName)
	_adminAuthRule.ID = field.NewInt32(tableName, "id")
	_adminAuthRule.UID = field.NewInt64(tableName, "uid")
	_adminAuthRule.Title = field.NewString(tableName, "title")
	_adminAuthRule.Des = field.NewString(tableName, "des")
	_adminAuthRule.Locale = field.NewString(tableName, "locale")
	_adminAuthRule.Weigh = field.NewInt32(tableName, "weigh")
	_adminAuthRule.Type = field.NewInt8(tableName, "type")
	_adminAuthRule.Pid = field.NewInt32(tableName, "pid")
	_adminAuthRule.Icon = field.NewString(tableName, "icon")
	_adminAuthRule.Routepath = field.NewString(tableName, "routepath")
	_adminAuthRule.Routename = field.NewString(tableName, "routename")
	_adminAuthRule.Component = field.NewString(tableName, "component")
	_adminAuthRule.Redirect = field.NewString(tableName, "redirect")
	_adminAuthRule.Path = field.NewString(tableName, "path")
	_adminAuthRule.Permission = field.NewString(tableName, "permission")
	_adminAuthRule.Status = field.NewInt8(tableName, "status")
	_adminAuthRule.Isext = field.NewInt8(tableName, "isext")
	_adminAuthRule.Keepalive = field.NewInt8(tableName, "keepalive")
	_adminAuthRule.Requiresauth = field.NewInt8(tableName, "requiresauth")
	_adminAuthRule.Hideinmenu = field.NewInt8(tableName, "hideinmenu")
	_adminAuthRule.Hidechildreninmenu = field.NewInt8(tableName, "hidechildreninmenu")
	_adminAuthRule.Activemenu = field.NewInt8(tableName, "activemenu")
	_adminAuthRule.Noaffix = field.NewInt8(tableName, "noaffix")
	_adminAuthRule.Onlypage = field.NewInt8(tableName, "onlypage")
	_adminAuthRule.CreatedAt = field.NewTime(tableName, "created_at")
	_adminAuthRule.UpdatedAt = field.NewTime(tableName, "updated_at")
	_adminAuthRule.DeletedAt = field.NewField(tableName, "deleted_at")

	_adminAuthRule.fillFieldMap()

	return _adminAuthRule
}

// adminAuthRule 业务后台菜单
type adminAuthRule struct {
	adminAuthRuleDo

	ALL                field.Asterisk
	ID                 field.Int32
	UID                field.Int64  // 添加用户
	Title              field.String // 菜单名称
	Des                field.String // 描述
	Locale             field.String // 中英文标题key
	Weigh              field.Int32  // 排序
	Type               field.Int8   // 类型 0=目录，1=菜单，2=按钮
	Pid                field.Int32  // 上一级
	Icon               field.String // 图标
	Routepath          field.String // 路由地址
	Routename          field.String // 路由名称
	Component          field.String // 组件路径
	Redirect           field.String // 重定向地址
	Path               field.String // 接口路径
	Permission         field.String // 权限标识
	Status             field.Int8   // 状态 0=启用1=禁用
	Isext              field.Int8   // 是否外链 0=否1=是
	Keepalive          field.Int8   // 是否缓存 0=否1=是
	Requiresauth       field.Int8   // 是否需要登录鉴权 0=否1=是
	Hideinmenu         field.Int8   // 是否在左侧菜单中隐藏该项 0=否1=是
	Hidechildreninmenu field.Int8   // 强制在左侧菜单中显示单项 0=否1=是
	Activemenu         field.Int8   // 高亮设置的菜单项 0=否1=是
	Noaffix            field.Int8   // 如果设置为true，标签将不会添加到tab-bar中 0=否1=是
	Onlypage           field.Int8   // 独立页面不需layout和登录，如登录页、数据大屏
	CreatedAt          field.Time   // 创建时间
	UpdatedAt          field.Time   // 更新时间
	DeletedAt          field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (a adminAuthRule) Table(newTableName string) *adminAuthRule {
	a.adminAuthRuleDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a adminAuthRule) As(alias string) *adminAuthRule {
	a.adminAuthRuleDo.DO = *(a.adminAuthRuleDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *adminAuthRule) updateTableName(table string) *adminAuthRule {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt32(table, "id")
	a.UID = field.NewInt64(table, "uid")
	a.Title = field.NewString(table, "title")
	a.Des = field.NewString(table, "des")
	a.Locale = field.NewString(table, "locale")
	a.Weigh = field.NewInt32(table, "weigh")
	a.Type = field.NewInt8(table, "type")
	a.Pid = field.NewInt32(table, "pid")
	a.Icon = field.NewString(table, "icon")
	a.Routepath = field.NewString(table, "routepath")
	a.Routename = field.NewString(table, "routename")
	a.Component = field.NewString(table, "component")
	a.Redirect = field.NewString(table, "redirect")
	a.Path = field.NewString(table, "path")
	a.Permission = field.NewString(table, "permission")
	a.Status = field.NewInt8(table, "status")
	a.Isext = field.NewInt8(table, "isext")
	a.Keepalive = field.NewInt8(table, "keepalive")
	a.Requiresauth = field.NewInt8(table, "requiresauth")
	a.Hideinmenu = field.NewInt8(table, "hideinmenu")
	a.Hidechildreninmenu = field.NewInt8(table, "hidechildreninmenu")
	a.Activemenu = field.NewInt8(table, "activemenu")
	a.Noaffix = field.NewInt8(table, "noaffix")
	a.Onlypage = field.NewInt8(table, "onlypage")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")

	a.fillFieldMap()

	return a
}

func (a *adminAuthRule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *adminAuthRule) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 27)
	a.fieldMap["id"] = a.ID
	a.fieldMap["uid"] = a.UID
	a.fieldMap["title"] = a.Title
	a.fieldMap["des"] = a.Des
	a.fieldMap["locale"] = a.Locale
	a.fieldMap["weigh"] = a.Weigh
	a.fieldMap["type"] = a.Type
	a.fieldMap["pid"] = a.Pid
	a.fieldMap["icon"] = a.Icon
	a.fieldMap["routepath"] = a.Routepath
	a.fieldMap["routename"] = a.Routename
	a.fieldMap["component"] = a.Component
	a.fieldMap["redirect"] = a.Redirect
	a.fieldMap["path"] = a.Path
	a.fieldMap["permission"] = a.Permission
	a.fieldMap["status"] = a.Status
	a.fieldMap["isext"] = a.Isext
	a.fieldMap["keepalive"] = a.Keepalive
	a.fieldMap["requiresauth"] = a.Requiresauth
	a.fieldMap["hideinmenu"] = a.Hideinmenu
	a.fieldMap["hidechildreninmenu"] = a.Hidechildreninmenu
	a.fieldMap["activemenu"] = a.Activemenu
	a.fieldMap["noaffix"] = a.Noaffix
	a.fieldMap["onlypage"] = a.Onlypage
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
}

func (a adminAuthRule) clone(db *gorm.DB) adminAuthRule {
	a.adminAuthRuleDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a adminAuthRule) replaceDB(db *gorm.DB) adminAuthRule {
	a.adminAuthRuleDo.ReplaceDB(db)
	return a
}

type adminAuthRuleDo struct{ gen.DO }

type IAdminAuthRuleDo interface {
	gen.SubQuery
	Debug() IAdminAuthRuleDo
	WithContext(ctx context.Context) IAdminAuthRuleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAdminAuthRuleDo
	WriteDB() IAdminAuthRuleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAdminAuthRuleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAdminAuthRuleDo
	Not(conds ...gen.Condition) IAdminAuthRuleDo
	Or(conds ...gen.Condition) IAdminAuthRuleDo
	Select(conds ...field.Expr) IAdminAuthRuleDo
	Where(conds ...gen.Condition) IAdminAuthRuleDo
	Order(conds ...field.Expr) IAdminAuthRuleDo
	Distinct(cols ...field.Expr) IAdminAuthRuleDo
	Omit(cols ...field.Expr) IAdminAuthRuleDo
	Join(table schema.Tabler, on ...field.Expr) IAdminAuthRuleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAdminAuthRuleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAdminAuthRuleDo
	Group(cols ...field.Expr) IAdminAuthRuleDo
	Having(conds ...gen.Condition) IAdminAuthRuleDo
	Limit(limit int) IAdminAuthRuleDo
	Offset(offset int) IAdminAuthRuleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminAuthRuleDo
	Unscoped() IAdminAuthRuleDo
	Create(values ...*model.AdminAuthRule) error
	CreateInBatches(values []*model.AdminAuthRule, batchSize int) error
	Save(values ...*model.AdminAuthRule) error
	First() (*model.AdminAuthRule, error)
	Take() (*model.AdminAuthRule, error)
	Last() (*model.AdminAuthRule, error)
	Find() ([]*model.AdminAuthRule, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminAuthRule, err error)
	FindInBatches(result *[]*model.AdminAuthRule, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AdminAuthRule) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAdminAuthRuleDo
	Assign(attrs ...field.AssignExpr) IAdminAuthRuleDo
	Joins(fields ...field.RelationField) IAdminAuthRuleDo
	Preload(fields ...field.RelationField) IAdminAuthRuleDo
	FirstOrInit() (*model.AdminAuthRule, error)
	FirstOrCreate() (*model.AdminAuthRule, error)
	FindByPage(offset int, limit int) (result []*model.AdminAuthRule, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAdminAuthRuleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a adminAuthRuleDo) Debug() IAdminAuthRuleDo {
	return a.withDO(a.DO.Debug())
}

func (a adminAuthRuleDo) WithContext(ctx context.Context) IAdminAuthRuleDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a adminAuthRuleDo) ReadDB() IAdminAuthRuleDo {
	return a.Clauses(dbresolver.Read)
}

func (a adminAuthRuleDo) WriteDB() IAdminAuthRuleDo {
	return a.Clauses(dbresolver.Write)
}

func (a adminAuthRuleDo) Session(config *gorm.Session) IAdminAuthRuleDo {
	return a.withDO(a.DO.Session(config))
}

func (a adminAuthRuleDo) Clauses(conds ...clause.Expression) IAdminAuthRuleDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a adminAuthRuleDo) Returning(value interface{}, columns ...string) IAdminAuthRuleDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a adminAuthRuleDo) Not(conds ...gen.Condition) IAdminAuthRuleDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a adminAuthRuleDo) Or(conds ...gen.Condition) IAdminAuthRuleDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a adminAuthRuleDo) Select(conds ...field.Expr) IAdminAuthRuleDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a adminAuthRuleDo) Where(conds ...gen.Condition) IAdminAuthRuleDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a adminAuthRuleDo) Order(conds ...field.Expr) IAdminAuthRuleDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a adminAuthRuleDo) Distinct(cols ...field.Expr) IAdminAuthRuleDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a adminAuthRuleDo) Omit(cols ...field.Expr) IAdminAuthRuleDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a adminAuthRuleDo) Join(table schema.Tabler, on ...field.Expr) IAdminAuthRuleDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a adminAuthRuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAdminAuthRuleDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a adminAuthRuleDo) RightJoin(table schema.Tabler, on ...field.Expr) IAdminAuthRuleDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a adminAuthRuleDo) Group(cols ...field.Expr) IAdminAuthRuleDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a adminAuthRuleDo) Having(conds ...gen.Condition) IAdminAuthRuleDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a adminAuthRuleDo) Limit(limit int) IAdminAuthRuleDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a adminAuthRuleDo) Offset(offset int) IAdminAuthRuleDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a adminAuthRuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminAuthRuleDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a adminAuthRuleDo) Unscoped() IAdminAuthRuleDo {
	return a.withDO(a.DO.Unscoped())
}

func (a adminAuthRuleDo) Create(values ...*model.AdminAuthRule) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a adminAuthRuleDo) CreateInBatches(values []*model.AdminAuthRule, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a adminAuthRuleDo) Save(values ...*model.AdminAuthRule) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a adminAuthRuleDo) First() (*model.AdminAuthRule, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRule), nil
	}
}

func (a adminAuthRuleDo) Take() (*model.AdminAuthRule, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRule), nil
	}
}

func (a adminAuthRuleDo) Last() (*model.AdminAuthRule, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRule), nil
	}
}

func (a adminAuthRuleDo) Find() ([]*model.AdminAuthRule, error) {
	result, err := a.DO.Find()
	return result.([]*model.AdminAuthRule), err
}

func (a adminAuthRuleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminAuthRule, err error) {
	buf := make([]*model.AdminAuthRule, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a adminAuthRuleDo) FindInBatches(result *[]*model.AdminAuthRule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a adminAuthRuleDo) Attrs(attrs ...field.AssignExpr) IAdminAuthRuleDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a adminAuthRuleDo) Assign(attrs ...field.AssignExpr) IAdminAuthRuleDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a adminAuthRuleDo) Joins(fields ...field.RelationField) IAdminAuthRuleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a adminAuthRuleDo) Preload(fields ...field.RelationField) IAdminAuthRuleDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a adminAuthRuleDo) FirstOrInit() (*model.AdminAuthRule, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRule), nil
	}
}

func (a adminAuthRuleDo) FirstOrCreate() (*model.AdminAuthRule, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminAuthRule), nil
	}
}

func (a adminAuthRuleDo) FindByPage(offset int, limit int) (result []*model.AdminAuthRule, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a adminAuthRuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a adminAuthRuleDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a adminAuthRuleDo) Delete(models ...*model.AdminAuthRule) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *adminAuthRuleDo) withDO(do gen.Dao) *adminAuthRuleDo {
	a.DO = *do.(*gen.DO)
	return a
}
