// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newCommonMessage(db *gorm.DB, opts ...gen.DOOption) commonMessage {
	_commonMessage := commonMessage{}

	_commonMessage.commonMessageDo.UseDB(db, opts...)
	_commonMessage.commonMessageDo.UseModel(&model.CommonMessage{})

	tableName := _commonMessage.commonMessageDo.TableName()
	_commonMessage.ALL = field.NewAsterisk(tableName)
	_commonMessage.ID = field.NewInt32(tableName, "id")
	_commonMessage.Usertype = field.NewInt8(tableName, "usertype")
	_commonMessage.AccountID = field.NewInt64(tableName, "account_id")
	_commonMessage.Adduid = field.NewInt32(tableName, "adduid")
	_commonMessage.Touid = field.NewInt32(tableName, "touid")
	_commonMessage.Type = field.NewInt8(tableName, "type")
	_commonMessage.Title = field.NewString(tableName, "title")
	_commonMessage.Path = field.NewString(tableName, "path")
	_commonMessage.Content = field.NewString(tableName, "content")
	_commonMessage.Isread = field.NewInt8(tableName, "isread")
	_commonMessage.CreatedAt = field.NewTime(tableName, "created_at")

	_commonMessage.fillFieldMap()

	return _commonMessage
}

// commonMessage 系统通用消息
type commonMessage struct {
	commonMessageDo

	ALL       field.Asterisk
	ID        field.Int32
	Usertype  field.Int8   // 用户类型0=全部，1=系统-2=boss端，3=C端
	AccountID field.Int64  // 账号id
	Adduid    field.Int32  // 添加用户
	Touid     field.Int32  // 接收用户
	Type      field.Int8   // 类型1=通知，2=消息，3=代办
	Title     field.String // 消息标题
	Path      field.String // 跳转路由
	Content   field.String // 消息内容
	Isread    field.Int8   // 是否已读1=已读
	CreatedAt field.Time   // 发送时间

	fieldMap map[string]field.Expr
}

func (c commonMessage) Table(newTableName string) *commonMessage {
	c.commonMessageDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c commonMessage) As(alias string) *commonMessage {
	c.commonMessageDo.DO = *(c.commonMessageDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *commonMessage) updateTableName(table string) *commonMessage {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.Usertype = field.NewInt8(table, "usertype")
	c.AccountID = field.NewInt64(table, "account_id")
	c.Adduid = field.NewInt32(table, "adduid")
	c.Touid = field.NewInt32(table, "touid")
	c.Type = field.NewInt8(table, "type")
	c.Title = field.NewString(table, "title")
	c.Path = field.NewString(table, "path")
	c.Content = field.NewString(table, "content")
	c.Isread = field.NewInt8(table, "isread")
	c.CreatedAt = field.NewTime(table, "created_at")

	c.fillFieldMap()

	return c
}

func (c *commonMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *commonMessage) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 11)
	c.fieldMap["id"] = c.ID
	c.fieldMap["usertype"] = c.Usertype
	c.fieldMap["account_id"] = c.AccountID
	c.fieldMap["adduid"] = c.Adduid
	c.fieldMap["touid"] = c.Touid
	c.fieldMap["type"] = c.Type
	c.fieldMap["title"] = c.Title
	c.fieldMap["path"] = c.Path
	c.fieldMap["content"] = c.Content
	c.fieldMap["isread"] = c.Isread
	c.fieldMap["created_at"] = c.CreatedAt
}

func (c commonMessage) clone(db *gorm.DB) commonMessage {
	c.commonMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c commonMessage) replaceDB(db *gorm.DB) commonMessage {
	c.commonMessageDo.ReplaceDB(db)
	return c
}

type commonMessageDo struct{ gen.DO }

type ICommonMessageDo interface {
	gen.SubQuery
	Debug() ICommonMessageDo
	WithContext(ctx context.Context) ICommonMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICommonMessageDo
	WriteDB() ICommonMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICommonMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICommonMessageDo
	Not(conds ...gen.Condition) ICommonMessageDo
	Or(conds ...gen.Condition) ICommonMessageDo
	Select(conds ...field.Expr) ICommonMessageDo
	Where(conds ...gen.Condition) ICommonMessageDo
	Order(conds ...field.Expr) ICommonMessageDo
	Distinct(cols ...field.Expr) ICommonMessageDo
	Omit(cols ...field.Expr) ICommonMessageDo
	Join(table schema.Tabler, on ...field.Expr) ICommonMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICommonMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICommonMessageDo
	Group(cols ...field.Expr) ICommonMessageDo
	Having(conds ...gen.Condition) ICommonMessageDo
	Limit(limit int) ICommonMessageDo
	Offset(offset int) ICommonMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICommonMessageDo
	Unscoped() ICommonMessageDo
	Create(values ...*model.CommonMessage) error
	CreateInBatches(values []*model.CommonMessage, batchSize int) error
	Save(values ...*model.CommonMessage) error
	First() (*model.CommonMessage, error)
	Take() (*model.CommonMessage, error)
	Last() (*model.CommonMessage, error)
	Find() ([]*model.CommonMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CommonMessage, err error)
	FindInBatches(result *[]*model.CommonMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CommonMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICommonMessageDo
	Assign(attrs ...field.AssignExpr) ICommonMessageDo
	Joins(fields ...field.RelationField) ICommonMessageDo
	Preload(fields ...field.RelationField) ICommonMessageDo
	FirstOrInit() (*model.CommonMessage, error)
	FirstOrCreate() (*model.CommonMessage, error)
	FindByPage(offset int, limit int) (result []*model.CommonMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICommonMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c commonMessageDo) Debug() ICommonMessageDo {
	return c.withDO(c.DO.Debug())
}

func (c commonMessageDo) WithContext(ctx context.Context) ICommonMessageDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c commonMessageDo) ReadDB() ICommonMessageDo {
	return c.Clauses(dbresolver.Read)
}

func (c commonMessageDo) WriteDB() ICommonMessageDo {
	return c.Clauses(dbresolver.Write)
}

func (c commonMessageDo) Session(config *gorm.Session) ICommonMessageDo {
	return c.withDO(c.DO.Session(config))
}

func (c commonMessageDo) Clauses(conds ...clause.Expression) ICommonMessageDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c commonMessageDo) Returning(value interface{}, columns ...string) ICommonMessageDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c commonMessageDo) Not(conds ...gen.Condition) ICommonMessageDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c commonMessageDo) Or(conds ...gen.Condition) ICommonMessageDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c commonMessageDo) Select(conds ...field.Expr) ICommonMessageDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c commonMessageDo) Where(conds ...gen.Condition) ICommonMessageDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c commonMessageDo) Order(conds ...field.Expr) ICommonMessageDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c commonMessageDo) Distinct(cols ...field.Expr) ICommonMessageDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c commonMessageDo) Omit(cols ...field.Expr) ICommonMessageDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c commonMessageDo) Join(table schema.Tabler, on ...field.Expr) ICommonMessageDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c commonMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICommonMessageDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c commonMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) ICommonMessageDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c commonMessageDo) Group(cols ...field.Expr) ICommonMessageDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c commonMessageDo) Having(conds ...gen.Condition) ICommonMessageDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c commonMessageDo) Limit(limit int) ICommonMessageDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c commonMessageDo) Offset(offset int) ICommonMessageDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c commonMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICommonMessageDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c commonMessageDo) Unscoped() ICommonMessageDo {
	return c.withDO(c.DO.Unscoped())
}

func (c commonMessageDo) Create(values ...*model.CommonMessage) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c commonMessageDo) CreateInBatches(values []*model.CommonMessage, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c commonMessageDo) Save(values ...*model.CommonMessage) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c commonMessageDo) First() (*model.CommonMessage, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonMessage), nil
	}
}

func (c commonMessageDo) Take() (*model.CommonMessage, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonMessage), nil
	}
}

func (c commonMessageDo) Last() (*model.CommonMessage, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonMessage), nil
	}
}

func (c commonMessageDo) Find() ([]*model.CommonMessage, error) {
	result, err := c.DO.Find()
	return result.([]*model.CommonMessage), err
}

func (c commonMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CommonMessage, err error) {
	buf := make([]*model.CommonMessage, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c commonMessageDo) FindInBatches(result *[]*model.CommonMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c commonMessageDo) Attrs(attrs ...field.AssignExpr) ICommonMessageDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c commonMessageDo) Assign(attrs ...field.AssignExpr) ICommonMessageDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c commonMessageDo) Joins(fields ...field.RelationField) ICommonMessageDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c commonMessageDo) Preload(fields ...field.RelationField) ICommonMessageDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c commonMessageDo) FirstOrInit() (*model.CommonMessage, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonMessage), nil
	}
}

func (c commonMessageDo) FirstOrCreate() (*model.CommonMessage, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonMessage), nil
	}
}

func (c commonMessageDo) FindByPage(offset int, limit int) (result []*model.CommonMessage, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c commonMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c commonMessageDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c commonMessageDo) Delete(models ...*model.CommonMessage) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *commonMessageDo) withDO(do gen.Dao) *commonMessageDo {
	c.DO = *do.(*gen.DO)
	return c
}
