// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newCreatecodeProduct(db *gorm.DB, opts ...gen.DOOption) createcodeProduct {
	_createcodeProduct := createcodeProduct{}

	_createcodeProduct.createcodeProductDo.UseDB(db, opts...)
	_createcodeProduct.createcodeProductDo.UseModel(&model.CreatecodeProduct{})

	tableName := _createcodeProduct.createcodeProductDo.TableName()
	_createcodeProduct.ALL = field.NewAsterisk(tableName)
	_createcodeProduct.ID = field.NewInt32(tableName, "id")
	_createcodeProduct.AccountID = field.NewInt64(tableName, "account_id")
	_createcodeProduct.TenantID = field.NewInt64(tableName, "tenant_id")
	_createcodeProduct.Cid = field.NewInt32(tableName, "cid")
	_createcodeProduct.Title = field.NewString(tableName, "title")
	_createcodeProduct.Num = field.NewInt32(tableName, "num")
	_createcodeProduct.Price = field.NewFloat64(tableName, "price")
	_createcodeProduct.Sex = field.NewInt8(tableName, "sex")
	_createcodeProduct.Desc = field.NewString(tableName, "desc")
	_createcodeProduct.Content = field.NewString(tableName, "content")
	_createcodeProduct.LikeColor = field.NewString(tableName, "likeColor")
	_createcodeProduct.BallType = field.NewString(tableName, "ballType")
	_createcodeProduct.UserType = field.NewString(tableName, "userType")
	_createcodeProduct.Image = field.NewString(tableName, "image")
	_createcodeProduct.Images = field.NewString(tableName, "images")
	_createcodeProduct.Moreimgs = field.NewString(tableName, "moreimgs")
	_createcodeProduct.Contenttow = field.NewString(tableName, "contenttow")
	_createcodeProduct.RecordAudio = field.NewString(tableName, "record_audio")
	_createcodeProduct.File = field.NewString(tableName, "file")
	_createcodeProduct.Workerway = field.NewString(tableName, "workerway")
	_createcodeProduct.Status = field.NewInt8(tableName, "status")
	_createcodeProduct.CreatedAt = field.NewTime(tableName, "created_at")
	_createcodeProduct.UpdatedAt = field.NewTime(tableName, "updated_at")
	_createcodeProduct.DeletedAt = field.NewField(tableName, "deleted_at")

	_createcodeProduct.fillFieldMap()

	return _createcodeProduct
}

// createcodeProduct 测试代码产品
type createcodeProduct struct {
	createcodeProductDo

	ALL         field.Asterisk
	ID          field.Int32
	AccountID   field.Int64   // 账号id/记录那个账号添加
	TenantID    field.Int64   // 租户唯一标识
	Cid         field.Int32   // 分类
	Title       field.String  // 标题
	Num         field.Int32   // 库存
	Price       field.Float64 // 价格
	Sex         field.Int8    // 性别:0=未知,1=男,2=女
	Desc        field.String  // 描述
	Content     field.String  // 内容详情
	LikeColor   field.String  // 喜欢的颜色
	BallType    field.String  // 球类
	UserType    field.String  // 用户类型
	Image       field.String  // 单张图
	Images      field.String  // 多张图
	Moreimgs    field.String  // 图组
	Contenttow  field.String  // 注意内容
	RecordAudio field.String  // 记录录音
	File        field.String  // 附件
	Workerway   field.String  // 出行方式:car=汽车,bus=公交,air=飞机
	Status      field.Int8    // 状态:0=正常,1=隐藏
	CreatedAt   field.Time    // 创建时间
	UpdatedAt   field.Time    // 更新时间
	DeletedAt   field.Field   // 删除时间

	fieldMap map[string]field.Expr
}

func (c createcodeProduct) Table(newTableName string) *createcodeProduct {
	c.createcodeProductDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c createcodeProduct) As(alias string) *createcodeProduct {
	c.createcodeProductDo.DO = *(c.createcodeProductDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *createcodeProduct) updateTableName(table string) *createcodeProduct {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.AccountID = field.NewInt64(table, "account_id")
	c.TenantID = field.NewInt64(table, "tenant_id")
	c.Cid = field.NewInt32(table, "cid")
	c.Title = field.NewString(table, "title")
	c.Num = field.NewInt32(table, "num")
	c.Price = field.NewFloat64(table, "price")
	c.Sex = field.NewInt8(table, "sex")
	c.Desc = field.NewString(table, "desc")
	c.Content = field.NewString(table, "content")
	c.LikeColor = field.NewString(table, "likeColor")
	c.BallType = field.NewString(table, "ballType")
	c.UserType = field.NewString(table, "userType")
	c.Image = field.NewString(table, "image")
	c.Images = field.NewString(table, "images")
	c.Moreimgs = field.NewString(table, "moreimgs")
	c.Contenttow = field.NewString(table, "contenttow")
	c.RecordAudio = field.NewString(table, "record_audio")
	c.File = field.NewString(table, "file")
	c.Workerway = field.NewString(table, "workerway")
	c.Status = field.NewInt8(table, "status")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *createcodeProduct) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *createcodeProduct) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 24)
	c.fieldMap["id"] = c.ID
	c.fieldMap["account_id"] = c.AccountID
	c.fieldMap["tenant_id"] = c.TenantID
	c.fieldMap["cid"] = c.Cid
	c.fieldMap["title"] = c.Title
	c.fieldMap["num"] = c.Num
	c.fieldMap["price"] = c.Price
	c.fieldMap["sex"] = c.Sex
	c.fieldMap["desc"] = c.Desc
	c.fieldMap["content"] = c.Content
	c.fieldMap["likeColor"] = c.LikeColor
	c.fieldMap["ballType"] = c.BallType
	c.fieldMap["userType"] = c.UserType
	c.fieldMap["image"] = c.Image
	c.fieldMap["images"] = c.Images
	c.fieldMap["moreimgs"] = c.Moreimgs
	c.fieldMap["contenttow"] = c.Contenttow
	c.fieldMap["record_audio"] = c.RecordAudio
	c.fieldMap["file"] = c.File
	c.fieldMap["workerway"] = c.Workerway
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c createcodeProduct) clone(db *gorm.DB) createcodeProduct {
	c.createcodeProductDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c createcodeProduct) replaceDB(db *gorm.DB) createcodeProduct {
	c.createcodeProductDo.ReplaceDB(db)
	return c
}

type createcodeProductDo struct{ gen.DO }

type ICreatecodeProductDo interface {
	gen.SubQuery
	Debug() ICreatecodeProductDo
	WithContext(ctx context.Context) ICreatecodeProductDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICreatecodeProductDo
	WriteDB() ICreatecodeProductDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICreatecodeProductDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICreatecodeProductDo
	Not(conds ...gen.Condition) ICreatecodeProductDo
	Or(conds ...gen.Condition) ICreatecodeProductDo
	Select(conds ...field.Expr) ICreatecodeProductDo
	Where(conds ...gen.Condition) ICreatecodeProductDo
	Order(conds ...field.Expr) ICreatecodeProductDo
	Distinct(cols ...field.Expr) ICreatecodeProductDo
	Omit(cols ...field.Expr) ICreatecodeProductDo
	Join(table schema.Tabler, on ...field.Expr) ICreatecodeProductDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICreatecodeProductDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICreatecodeProductDo
	Group(cols ...field.Expr) ICreatecodeProductDo
	Having(conds ...gen.Condition) ICreatecodeProductDo
	Limit(limit int) ICreatecodeProductDo
	Offset(offset int) ICreatecodeProductDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICreatecodeProductDo
	Unscoped() ICreatecodeProductDo
	Create(values ...*model.CreatecodeProduct) error
	CreateInBatches(values []*model.CreatecodeProduct, batchSize int) error
	Save(values ...*model.CreatecodeProduct) error
	First() (*model.CreatecodeProduct, error)
	Take() (*model.CreatecodeProduct, error)
	Last() (*model.CreatecodeProduct, error)
	Find() ([]*model.CreatecodeProduct, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CreatecodeProduct, err error)
	FindInBatches(result *[]*model.CreatecodeProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CreatecodeProduct) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICreatecodeProductDo
	Assign(attrs ...field.AssignExpr) ICreatecodeProductDo
	Joins(fields ...field.RelationField) ICreatecodeProductDo
	Preload(fields ...field.RelationField) ICreatecodeProductDo
	FirstOrInit() (*model.CreatecodeProduct, error)
	FirstOrCreate() (*model.CreatecodeProduct, error)
	FindByPage(offset int, limit int) (result []*model.CreatecodeProduct, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICreatecodeProductDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c createcodeProductDo) Debug() ICreatecodeProductDo {
	return c.withDO(c.DO.Debug())
}

func (c createcodeProductDo) WithContext(ctx context.Context) ICreatecodeProductDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c createcodeProductDo) ReadDB() ICreatecodeProductDo {
	return c.Clauses(dbresolver.Read)
}

func (c createcodeProductDo) WriteDB() ICreatecodeProductDo {
	return c.Clauses(dbresolver.Write)
}

func (c createcodeProductDo) Session(config *gorm.Session) ICreatecodeProductDo {
	return c.withDO(c.DO.Session(config))
}

func (c createcodeProductDo) Clauses(conds ...clause.Expression) ICreatecodeProductDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c createcodeProductDo) Returning(value interface{}, columns ...string) ICreatecodeProductDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c createcodeProductDo) Not(conds ...gen.Condition) ICreatecodeProductDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c createcodeProductDo) Or(conds ...gen.Condition) ICreatecodeProductDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c createcodeProductDo) Select(conds ...field.Expr) ICreatecodeProductDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c createcodeProductDo) Where(conds ...gen.Condition) ICreatecodeProductDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c createcodeProductDo) Order(conds ...field.Expr) ICreatecodeProductDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c createcodeProductDo) Distinct(cols ...field.Expr) ICreatecodeProductDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c createcodeProductDo) Omit(cols ...field.Expr) ICreatecodeProductDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c createcodeProductDo) Join(table schema.Tabler, on ...field.Expr) ICreatecodeProductDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c createcodeProductDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICreatecodeProductDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c createcodeProductDo) RightJoin(table schema.Tabler, on ...field.Expr) ICreatecodeProductDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c createcodeProductDo) Group(cols ...field.Expr) ICreatecodeProductDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c createcodeProductDo) Having(conds ...gen.Condition) ICreatecodeProductDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c createcodeProductDo) Limit(limit int) ICreatecodeProductDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c createcodeProductDo) Offset(offset int) ICreatecodeProductDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c createcodeProductDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICreatecodeProductDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c createcodeProductDo) Unscoped() ICreatecodeProductDo {
	return c.withDO(c.DO.Unscoped())
}

func (c createcodeProductDo) Create(values ...*model.CreatecodeProduct) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c createcodeProductDo) CreateInBatches(values []*model.CreatecodeProduct, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c createcodeProductDo) Save(values ...*model.CreatecodeProduct) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c createcodeProductDo) First() (*model.CreatecodeProduct, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreatecodeProduct), nil
	}
}

func (c createcodeProductDo) Take() (*model.CreatecodeProduct, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreatecodeProduct), nil
	}
}

func (c createcodeProductDo) Last() (*model.CreatecodeProduct, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreatecodeProduct), nil
	}
}

func (c createcodeProductDo) Find() ([]*model.CreatecodeProduct, error) {
	result, err := c.DO.Find()
	return result.([]*model.CreatecodeProduct), err
}

func (c createcodeProductDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CreatecodeProduct, err error) {
	buf := make([]*model.CreatecodeProduct, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c createcodeProductDo) FindInBatches(result *[]*model.CreatecodeProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c createcodeProductDo) Attrs(attrs ...field.AssignExpr) ICreatecodeProductDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c createcodeProductDo) Assign(attrs ...field.AssignExpr) ICreatecodeProductDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c createcodeProductDo) Joins(fields ...field.RelationField) ICreatecodeProductDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c createcodeProductDo) Preload(fields ...field.RelationField) ICreatecodeProductDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c createcodeProductDo) FirstOrInit() (*model.CreatecodeProduct, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreatecodeProduct), nil
	}
}

func (c createcodeProductDo) FirstOrCreate() (*model.CreatecodeProduct, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreatecodeProduct), nil
	}
}

func (c createcodeProductDo) FindByPage(offset int, limit int) (result []*model.CreatecodeProduct, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c createcodeProductDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c createcodeProductDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c createcodeProductDo) Delete(models ...*model.CreatecodeProduct) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *createcodeProductDo) withDO(do gen.Dao) *createcodeProductDo {
	c.DO = *do.(*gen.DO)
	return c
}
