// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newCreatecodeProductCate(db *gorm.DB, opts ...gen.DOOption) createcodeProductCate {
	_createcodeProductCate := createcodeProductCate{}

	_createcodeProductCate.createcodeProductCateDo.UseDB(db, opts...)
	_createcodeProductCate.createcodeProductCateDo.UseModel(&model.CreatecodeProductCate{})

	tableName := _createcodeProductCate.createcodeProductCateDo.TableName()
	_createcodeProductCate.ALL = field.NewAsterisk(tableName)
	_createcodeProductCate.ID = field.NewInt32(tableName, "id")
	_createcodeProductCate.AccountID = field.NewInt64(tableName, "account_id")
	_createcodeProductCate.TenantID = field.NewInt64(tableName, "tenant_id")
	_createcodeProductCate.Pid = field.NewInt32(tableName, "pid")
	_createcodeProductCate.Name = field.NewString(tableName, "name")
	_createcodeProductCate.Remark = field.NewString(tableName, "remark")
	_createcodeProductCate.Weigh = field.NewInt32(tableName, "weigh")
	_createcodeProductCate.Status = field.NewInt8(tableName, "status")
	_createcodeProductCate.CreatedAt = field.NewTime(tableName, "created_at")
	_createcodeProductCate.UpdatedAt = field.NewTime(tableName, "updated_at")
	_createcodeProductCate.DeletedAt = field.NewField(tableName, "deleted_at")

	_createcodeProductCate.fillFieldMap()

	return _createcodeProductCate
}

// createcodeProductCate 测试代码产品分类
type createcodeProductCate struct {
	createcodeProductCateDo

	ALL       field.Asterisk
	ID        field.Int32
	AccountID field.Int64  // 账号id/记录那个账号添加
	TenantID  field.Int64  // 租户唯一标识
	Pid       field.Int32  // 父级
	Name      field.String // 名称
	Remark    field.String // 备注
	Weigh     field.Int32  // 排序
	Status    field.Int8   // 状态:0=正常,1=隐藏
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (c createcodeProductCate) Table(newTableName string) *createcodeProductCate {
	c.createcodeProductCateDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c createcodeProductCate) As(alias string) *createcodeProductCate {
	c.createcodeProductCateDo.DO = *(c.createcodeProductCateDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *createcodeProductCate) updateTableName(table string) *createcodeProductCate {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.AccountID = field.NewInt64(table, "account_id")
	c.TenantID = field.NewInt64(table, "tenant_id")
	c.Pid = field.NewInt32(table, "pid")
	c.Name = field.NewString(table, "name")
	c.Remark = field.NewString(table, "remark")
	c.Weigh = field.NewInt32(table, "weigh")
	c.Status = field.NewInt8(table, "status")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *createcodeProductCate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *createcodeProductCate) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 11)
	c.fieldMap["id"] = c.ID
	c.fieldMap["account_id"] = c.AccountID
	c.fieldMap["tenant_id"] = c.TenantID
	c.fieldMap["pid"] = c.Pid
	c.fieldMap["name"] = c.Name
	c.fieldMap["remark"] = c.Remark
	c.fieldMap["weigh"] = c.Weigh
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c createcodeProductCate) clone(db *gorm.DB) createcodeProductCate {
	c.createcodeProductCateDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c createcodeProductCate) replaceDB(db *gorm.DB) createcodeProductCate {
	c.createcodeProductCateDo.ReplaceDB(db)
	return c
}

type createcodeProductCateDo struct{ gen.DO }

type ICreatecodeProductCateDo interface {
	gen.SubQuery
	Debug() ICreatecodeProductCateDo
	WithContext(ctx context.Context) ICreatecodeProductCateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICreatecodeProductCateDo
	WriteDB() ICreatecodeProductCateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICreatecodeProductCateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICreatecodeProductCateDo
	Not(conds ...gen.Condition) ICreatecodeProductCateDo
	Or(conds ...gen.Condition) ICreatecodeProductCateDo
	Select(conds ...field.Expr) ICreatecodeProductCateDo
	Where(conds ...gen.Condition) ICreatecodeProductCateDo
	Order(conds ...field.Expr) ICreatecodeProductCateDo
	Distinct(cols ...field.Expr) ICreatecodeProductCateDo
	Omit(cols ...field.Expr) ICreatecodeProductCateDo
	Join(table schema.Tabler, on ...field.Expr) ICreatecodeProductCateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICreatecodeProductCateDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICreatecodeProductCateDo
	Group(cols ...field.Expr) ICreatecodeProductCateDo
	Having(conds ...gen.Condition) ICreatecodeProductCateDo
	Limit(limit int) ICreatecodeProductCateDo
	Offset(offset int) ICreatecodeProductCateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICreatecodeProductCateDo
	Unscoped() ICreatecodeProductCateDo
	Create(values ...*model.CreatecodeProductCate) error
	CreateInBatches(values []*model.CreatecodeProductCate, batchSize int) error
	Save(values ...*model.CreatecodeProductCate) error
	First() (*model.CreatecodeProductCate, error)
	Take() (*model.CreatecodeProductCate, error)
	Last() (*model.CreatecodeProductCate, error)
	Find() ([]*model.CreatecodeProductCate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CreatecodeProductCate, err error)
	FindInBatches(result *[]*model.CreatecodeProductCate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CreatecodeProductCate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICreatecodeProductCateDo
	Assign(attrs ...field.AssignExpr) ICreatecodeProductCateDo
	Joins(fields ...field.RelationField) ICreatecodeProductCateDo
	Preload(fields ...field.RelationField) ICreatecodeProductCateDo
	FirstOrInit() (*model.CreatecodeProductCate, error)
	FirstOrCreate() (*model.CreatecodeProductCate, error)
	FindByPage(offset int, limit int) (result []*model.CreatecodeProductCate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICreatecodeProductCateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c createcodeProductCateDo) Debug() ICreatecodeProductCateDo {
	return c.withDO(c.DO.Debug())
}

func (c createcodeProductCateDo) WithContext(ctx context.Context) ICreatecodeProductCateDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c createcodeProductCateDo) ReadDB() ICreatecodeProductCateDo {
	return c.Clauses(dbresolver.Read)
}

func (c createcodeProductCateDo) WriteDB() ICreatecodeProductCateDo {
	return c.Clauses(dbresolver.Write)
}

func (c createcodeProductCateDo) Session(config *gorm.Session) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Session(config))
}

func (c createcodeProductCateDo) Clauses(conds ...clause.Expression) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c createcodeProductCateDo) Returning(value interface{}, columns ...string) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c createcodeProductCateDo) Not(conds ...gen.Condition) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c createcodeProductCateDo) Or(conds ...gen.Condition) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c createcodeProductCateDo) Select(conds ...field.Expr) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c createcodeProductCateDo) Where(conds ...gen.Condition) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c createcodeProductCateDo) Order(conds ...field.Expr) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c createcodeProductCateDo) Distinct(cols ...field.Expr) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c createcodeProductCateDo) Omit(cols ...field.Expr) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c createcodeProductCateDo) Join(table schema.Tabler, on ...field.Expr) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c createcodeProductCateDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICreatecodeProductCateDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c createcodeProductCateDo) RightJoin(table schema.Tabler, on ...field.Expr) ICreatecodeProductCateDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c createcodeProductCateDo) Group(cols ...field.Expr) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c createcodeProductCateDo) Having(conds ...gen.Condition) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c createcodeProductCateDo) Limit(limit int) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c createcodeProductCateDo) Offset(offset int) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c createcodeProductCateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c createcodeProductCateDo) Unscoped() ICreatecodeProductCateDo {
	return c.withDO(c.DO.Unscoped())
}

func (c createcodeProductCateDo) Create(values ...*model.CreatecodeProductCate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c createcodeProductCateDo) CreateInBatches(values []*model.CreatecodeProductCate, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c createcodeProductCateDo) Save(values ...*model.CreatecodeProductCate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c createcodeProductCateDo) First() (*model.CreatecodeProductCate, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreatecodeProductCate), nil
	}
}

func (c createcodeProductCateDo) Take() (*model.CreatecodeProductCate, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreatecodeProductCate), nil
	}
}

func (c createcodeProductCateDo) Last() (*model.CreatecodeProductCate, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreatecodeProductCate), nil
	}
}

func (c createcodeProductCateDo) Find() ([]*model.CreatecodeProductCate, error) {
	result, err := c.DO.Find()
	return result.([]*model.CreatecodeProductCate), err
}

func (c createcodeProductCateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CreatecodeProductCate, err error) {
	buf := make([]*model.CreatecodeProductCate, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c createcodeProductCateDo) FindInBatches(result *[]*model.CreatecodeProductCate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c createcodeProductCateDo) Attrs(attrs ...field.AssignExpr) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c createcodeProductCateDo) Assign(attrs ...field.AssignExpr) ICreatecodeProductCateDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c createcodeProductCateDo) Joins(fields ...field.RelationField) ICreatecodeProductCateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c createcodeProductCateDo) Preload(fields ...field.RelationField) ICreatecodeProductCateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c createcodeProductCateDo) FirstOrInit() (*model.CreatecodeProductCate, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreatecodeProductCate), nil
	}
}

func (c createcodeProductCateDo) FirstOrCreate() (*model.CreatecodeProductCate, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreatecodeProductCate), nil
	}
}

func (c createcodeProductCateDo) FindByPage(offset int, limit int) (result []*model.CreatecodeProductCate, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c createcodeProductCateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c createcodeProductCateDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c createcodeProductCateDo) Delete(models ...*model.CreatecodeProductCate) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *createcodeProductCateDo) withDO(do gen.Dao) *createcodeProductCateDo {
	c.DO = *do.(*gen.DO)
	return c
}
