// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newDictionaryData(db *gorm.DB, opts ...gen.DOOption) dictionaryData {
	_dictionaryData := dictionaryData{}

	_dictionaryData.dictionaryDataDo.UseDB(db, opts...)
	_dictionaryData.dictionaryDataDo.UseModel(&model.DictionaryData{})

	tableName := _dictionaryData.dictionaryDataDo.TableName()
	_dictionaryData.ALL = field.NewAsterisk(tableName)
	_dictionaryData.ID = field.NewInt32(tableName, "id")
	_dictionaryData.DataFrom = field.NewString(tableName, "data_from")
	_dictionaryData.GroupID = field.NewInt32(tableName, "group_id")
	_dictionaryData.Keyname = field.NewString(tableName, "keyname")
	_dictionaryData.Keyvalue = field.NewString(tableName, "keyvalue")
	_dictionaryData.Tagcolor = field.NewString(tableName, "tagcolor")
	_dictionaryData.Des = field.NewString(tableName, "des")
	_dictionaryData.Status = field.NewInt8(tableName, "status")
	_dictionaryData.Weigh = field.NewInt32(tableName, "weigh")
	_dictionaryData.CreatedAt = field.NewTime(tableName, "created_at")
	_dictionaryData.UpdatedAt = field.NewTime(tableName, "updated_at")

	_dictionaryData.fillFieldMap()

	return _dictionaryData
}

// dictionaryData 字典数据-公共表
type dictionaryData struct {
	dictionaryDataDo

	ALL       field.Asterisk
	ID        field.Int32
	DataFrom  field.String // 数据来源:common=公共,admin=管理后台
	GroupID   field.Int32  // 数据分组id
	Keyname   field.String // 字典名称
	Keyvalue  field.String // 字典项值
	Tagcolor  field.String // 标签颜色
	Des       field.String // 字典描述
	Status    field.Int8   // 状态
	Weigh     field.Int32  // 排序
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (d dictionaryData) Table(newTableName string) *dictionaryData {
	d.dictionaryDataDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dictionaryData) As(alias string) *dictionaryData {
	d.dictionaryDataDo.DO = *(d.dictionaryDataDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dictionaryData) updateTableName(table string) *dictionaryData {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt32(table, "id")
	d.DataFrom = field.NewString(table, "data_from")
	d.GroupID = field.NewInt32(table, "group_id")
	d.Keyname = field.NewString(table, "keyname")
	d.Keyvalue = field.NewString(table, "keyvalue")
	d.Tagcolor = field.NewString(table, "tagcolor")
	d.Des = field.NewString(table, "des")
	d.Status = field.NewInt8(table, "status")
	d.Weigh = field.NewInt32(table, "weigh")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *dictionaryData) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dictionaryData) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 11)
	d.fieldMap["id"] = d.ID
	d.fieldMap["data_from"] = d.DataFrom
	d.fieldMap["group_id"] = d.GroupID
	d.fieldMap["keyname"] = d.Keyname
	d.fieldMap["keyvalue"] = d.Keyvalue
	d.fieldMap["tagcolor"] = d.Tagcolor
	d.fieldMap["des"] = d.Des
	d.fieldMap["status"] = d.Status
	d.fieldMap["weigh"] = d.Weigh
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d dictionaryData) clone(db *gorm.DB) dictionaryData {
	d.dictionaryDataDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dictionaryData) replaceDB(db *gorm.DB) dictionaryData {
	d.dictionaryDataDo.ReplaceDB(db)
	return d
}

type dictionaryDataDo struct{ gen.DO }

type IDictionaryDataDo interface {
	gen.SubQuery
	Debug() IDictionaryDataDo
	WithContext(ctx context.Context) IDictionaryDataDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDictionaryDataDo
	WriteDB() IDictionaryDataDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDictionaryDataDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDictionaryDataDo
	Not(conds ...gen.Condition) IDictionaryDataDo
	Or(conds ...gen.Condition) IDictionaryDataDo
	Select(conds ...field.Expr) IDictionaryDataDo
	Where(conds ...gen.Condition) IDictionaryDataDo
	Order(conds ...field.Expr) IDictionaryDataDo
	Distinct(cols ...field.Expr) IDictionaryDataDo
	Omit(cols ...field.Expr) IDictionaryDataDo
	Join(table schema.Tabler, on ...field.Expr) IDictionaryDataDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDictionaryDataDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDictionaryDataDo
	Group(cols ...field.Expr) IDictionaryDataDo
	Having(conds ...gen.Condition) IDictionaryDataDo
	Limit(limit int) IDictionaryDataDo
	Offset(offset int) IDictionaryDataDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDictionaryDataDo
	Unscoped() IDictionaryDataDo
	Create(values ...*model.DictionaryData) error
	CreateInBatches(values []*model.DictionaryData, batchSize int) error
	Save(values ...*model.DictionaryData) error
	First() (*model.DictionaryData, error)
	Take() (*model.DictionaryData, error)
	Last() (*model.DictionaryData, error)
	Find() ([]*model.DictionaryData, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DictionaryData, err error)
	FindInBatches(result *[]*model.DictionaryData, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DictionaryData) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDictionaryDataDo
	Assign(attrs ...field.AssignExpr) IDictionaryDataDo
	Joins(fields ...field.RelationField) IDictionaryDataDo
	Preload(fields ...field.RelationField) IDictionaryDataDo
	FirstOrInit() (*model.DictionaryData, error)
	FirstOrCreate() (*model.DictionaryData, error)
	FindByPage(offset int, limit int) (result []*model.DictionaryData, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDictionaryDataDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dictionaryDataDo) Debug() IDictionaryDataDo {
	return d.withDO(d.DO.Debug())
}

func (d dictionaryDataDo) WithContext(ctx context.Context) IDictionaryDataDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dictionaryDataDo) ReadDB() IDictionaryDataDo {
	return d.Clauses(dbresolver.Read)
}

func (d dictionaryDataDo) WriteDB() IDictionaryDataDo {
	return d.Clauses(dbresolver.Write)
}

func (d dictionaryDataDo) Session(config *gorm.Session) IDictionaryDataDo {
	return d.withDO(d.DO.Session(config))
}

func (d dictionaryDataDo) Clauses(conds ...clause.Expression) IDictionaryDataDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dictionaryDataDo) Returning(value interface{}, columns ...string) IDictionaryDataDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dictionaryDataDo) Not(conds ...gen.Condition) IDictionaryDataDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dictionaryDataDo) Or(conds ...gen.Condition) IDictionaryDataDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dictionaryDataDo) Select(conds ...field.Expr) IDictionaryDataDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dictionaryDataDo) Where(conds ...gen.Condition) IDictionaryDataDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dictionaryDataDo) Order(conds ...field.Expr) IDictionaryDataDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dictionaryDataDo) Distinct(cols ...field.Expr) IDictionaryDataDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dictionaryDataDo) Omit(cols ...field.Expr) IDictionaryDataDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dictionaryDataDo) Join(table schema.Tabler, on ...field.Expr) IDictionaryDataDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dictionaryDataDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDictionaryDataDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dictionaryDataDo) RightJoin(table schema.Tabler, on ...field.Expr) IDictionaryDataDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dictionaryDataDo) Group(cols ...field.Expr) IDictionaryDataDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dictionaryDataDo) Having(conds ...gen.Condition) IDictionaryDataDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dictionaryDataDo) Limit(limit int) IDictionaryDataDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dictionaryDataDo) Offset(offset int) IDictionaryDataDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dictionaryDataDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDictionaryDataDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dictionaryDataDo) Unscoped() IDictionaryDataDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dictionaryDataDo) Create(values ...*model.DictionaryData) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dictionaryDataDo) CreateInBatches(values []*model.DictionaryData, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dictionaryDataDo) Save(values ...*model.DictionaryData) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dictionaryDataDo) First() (*model.DictionaryData, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryData), nil
	}
}

func (d dictionaryDataDo) Take() (*model.DictionaryData, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryData), nil
	}
}

func (d dictionaryDataDo) Last() (*model.DictionaryData, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryData), nil
	}
}

func (d dictionaryDataDo) Find() ([]*model.DictionaryData, error) {
	result, err := d.DO.Find()
	return result.([]*model.DictionaryData), err
}

func (d dictionaryDataDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DictionaryData, err error) {
	buf := make([]*model.DictionaryData, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dictionaryDataDo) FindInBatches(result *[]*model.DictionaryData, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dictionaryDataDo) Attrs(attrs ...field.AssignExpr) IDictionaryDataDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dictionaryDataDo) Assign(attrs ...field.AssignExpr) IDictionaryDataDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dictionaryDataDo) Joins(fields ...field.RelationField) IDictionaryDataDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dictionaryDataDo) Preload(fields ...field.RelationField) IDictionaryDataDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dictionaryDataDo) FirstOrInit() (*model.DictionaryData, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryData), nil
	}
}

func (d dictionaryDataDo) FirstOrCreate() (*model.DictionaryData, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryData), nil
	}
}

func (d dictionaryDataDo) FindByPage(offset int, limit int) (result []*model.DictionaryData, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dictionaryDataDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dictionaryDataDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dictionaryDataDo) Delete(models ...*model.DictionaryData) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dictionaryDataDo) withDO(do gen.Dao) *dictionaryDataDo {
	d.DO = *do.(*gen.DO)
	return d
}
