// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newDictionaryGroup(db *gorm.DB, opts ...gen.DOOption) dictionaryGroup {
	_dictionaryGroup := dictionaryGroup{}

	_dictionaryGroup.dictionaryGroupDo.UseDB(db, opts...)
	_dictionaryGroup.dictionaryGroupDo.UseModel(&model.DictionaryGroup{})

	tableName := _dictionaryGroup.dictionaryGroupDo.TableName()
	_dictionaryGroup.ALL = field.NewAsterisk(tableName)
	_dictionaryGroup.ID = field.NewInt32(tableName, "id")
	_dictionaryGroup.TenantID = field.NewInt32(tableName, "tenant_id")
	_dictionaryGroup.Title = field.NewString(tableName, "title")
	_dictionaryGroup.Remark = field.NewString(tableName, "remark")
	_dictionaryGroup.DataFrom = field.NewString(tableName, "data_from")
	_dictionaryGroup.DbWay = field.NewString(tableName, "db_way")
	_dictionaryGroup.Tablename = field.NewString(tableName, "tablename")
	_dictionaryGroup.Status = field.NewInt8(tableName, "status")
	_dictionaryGroup.Weigh = field.NewInt32(tableName, "weigh")
	_dictionaryGroup.CreatedAt = field.NewTime(tableName, "created_at")

	_dictionaryGroup.fillFieldMap()

	return _dictionaryGroup
}

// dictionaryGroup 字典分组
type dictionaryGroup struct {
	dictionaryGroupDo

	ALL       field.Asterisk
	ID        field.Int32
	TenantID  field.Int32  // 租户唯一标识
	Title     field.String // 字典分组名称
	Remark    field.String // 备注
	DataFrom  field.String // 数据来源:common=公共,admin=管理后台
	DbWay     field.String // 数据存储位置:sys=公共表,alone=单独建表
	Tablename field.String // 数据表名称
	Status    field.Int8   // 状态
	Weigh     field.Int32  // 排序
	CreatedAt field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (d dictionaryGroup) Table(newTableName string) *dictionaryGroup {
	d.dictionaryGroupDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dictionaryGroup) As(alias string) *dictionaryGroup {
	d.dictionaryGroupDo.DO = *(d.dictionaryGroupDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dictionaryGroup) updateTableName(table string) *dictionaryGroup {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt32(table, "id")
	d.TenantID = field.NewInt32(table, "tenant_id")
	d.Title = field.NewString(table, "title")
	d.Remark = field.NewString(table, "remark")
	d.DataFrom = field.NewString(table, "data_from")
	d.DbWay = field.NewString(table, "db_way")
	d.Tablename = field.NewString(table, "tablename")
	d.Status = field.NewInt8(table, "status")
	d.Weigh = field.NewInt32(table, "weigh")
	d.CreatedAt = field.NewTime(table, "created_at")

	d.fillFieldMap()

	return d
}

func (d *dictionaryGroup) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dictionaryGroup) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 10)
	d.fieldMap["id"] = d.ID
	d.fieldMap["tenant_id"] = d.TenantID
	d.fieldMap["title"] = d.Title
	d.fieldMap["remark"] = d.Remark
	d.fieldMap["data_from"] = d.DataFrom
	d.fieldMap["db_way"] = d.DbWay
	d.fieldMap["tablename"] = d.Tablename
	d.fieldMap["status"] = d.Status
	d.fieldMap["weigh"] = d.Weigh
	d.fieldMap["created_at"] = d.CreatedAt
}

func (d dictionaryGroup) clone(db *gorm.DB) dictionaryGroup {
	d.dictionaryGroupDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dictionaryGroup) replaceDB(db *gorm.DB) dictionaryGroup {
	d.dictionaryGroupDo.ReplaceDB(db)
	return d
}

type dictionaryGroupDo struct{ gen.DO }

type IDictionaryGroupDo interface {
	gen.SubQuery
	Debug() IDictionaryGroupDo
	WithContext(ctx context.Context) IDictionaryGroupDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDictionaryGroupDo
	WriteDB() IDictionaryGroupDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDictionaryGroupDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDictionaryGroupDo
	Not(conds ...gen.Condition) IDictionaryGroupDo
	Or(conds ...gen.Condition) IDictionaryGroupDo
	Select(conds ...field.Expr) IDictionaryGroupDo
	Where(conds ...gen.Condition) IDictionaryGroupDo
	Order(conds ...field.Expr) IDictionaryGroupDo
	Distinct(cols ...field.Expr) IDictionaryGroupDo
	Omit(cols ...field.Expr) IDictionaryGroupDo
	Join(table schema.Tabler, on ...field.Expr) IDictionaryGroupDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDictionaryGroupDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDictionaryGroupDo
	Group(cols ...field.Expr) IDictionaryGroupDo
	Having(conds ...gen.Condition) IDictionaryGroupDo
	Limit(limit int) IDictionaryGroupDo
	Offset(offset int) IDictionaryGroupDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDictionaryGroupDo
	Unscoped() IDictionaryGroupDo
	Create(values ...*model.DictionaryGroup) error
	CreateInBatches(values []*model.DictionaryGroup, batchSize int) error
	Save(values ...*model.DictionaryGroup) error
	First() (*model.DictionaryGroup, error)
	Take() (*model.DictionaryGroup, error)
	Last() (*model.DictionaryGroup, error)
	Find() ([]*model.DictionaryGroup, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DictionaryGroup, err error)
	FindInBatches(result *[]*model.DictionaryGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DictionaryGroup) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDictionaryGroupDo
	Assign(attrs ...field.AssignExpr) IDictionaryGroupDo
	Joins(fields ...field.RelationField) IDictionaryGroupDo
	Preload(fields ...field.RelationField) IDictionaryGroupDo
	FirstOrInit() (*model.DictionaryGroup, error)
	FirstOrCreate() (*model.DictionaryGroup, error)
	FindByPage(offset int, limit int) (result []*model.DictionaryGroup, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDictionaryGroupDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dictionaryGroupDo) Debug() IDictionaryGroupDo {
	return d.withDO(d.DO.Debug())
}

func (d dictionaryGroupDo) WithContext(ctx context.Context) IDictionaryGroupDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dictionaryGroupDo) ReadDB() IDictionaryGroupDo {
	return d.Clauses(dbresolver.Read)
}

func (d dictionaryGroupDo) WriteDB() IDictionaryGroupDo {
	return d.Clauses(dbresolver.Write)
}

func (d dictionaryGroupDo) Session(config *gorm.Session) IDictionaryGroupDo {
	return d.withDO(d.DO.Session(config))
}

func (d dictionaryGroupDo) Clauses(conds ...clause.Expression) IDictionaryGroupDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dictionaryGroupDo) Returning(value interface{}, columns ...string) IDictionaryGroupDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dictionaryGroupDo) Not(conds ...gen.Condition) IDictionaryGroupDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dictionaryGroupDo) Or(conds ...gen.Condition) IDictionaryGroupDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dictionaryGroupDo) Select(conds ...field.Expr) IDictionaryGroupDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dictionaryGroupDo) Where(conds ...gen.Condition) IDictionaryGroupDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dictionaryGroupDo) Order(conds ...field.Expr) IDictionaryGroupDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dictionaryGroupDo) Distinct(cols ...field.Expr) IDictionaryGroupDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dictionaryGroupDo) Omit(cols ...field.Expr) IDictionaryGroupDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dictionaryGroupDo) Join(table schema.Tabler, on ...field.Expr) IDictionaryGroupDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dictionaryGroupDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDictionaryGroupDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dictionaryGroupDo) RightJoin(table schema.Tabler, on ...field.Expr) IDictionaryGroupDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dictionaryGroupDo) Group(cols ...field.Expr) IDictionaryGroupDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dictionaryGroupDo) Having(conds ...gen.Condition) IDictionaryGroupDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dictionaryGroupDo) Limit(limit int) IDictionaryGroupDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dictionaryGroupDo) Offset(offset int) IDictionaryGroupDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dictionaryGroupDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDictionaryGroupDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dictionaryGroupDo) Unscoped() IDictionaryGroupDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dictionaryGroupDo) Create(values ...*model.DictionaryGroup) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dictionaryGroupDo) CreateInBatches(values []*model.DictionaryGroup, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dictionaryGroupDo) Save(values ...*model.DictionaryGroup) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dictionaryGroupDo) First() (*model.DictionaryGroup, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryGroup), nil
	}
}

func (d dictionaryGroupDo) Take() (*model.DictionaryGroup, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryGroup), nil
	}
}

func (d dictionaryGroupDo) Last() (*model.DictionaryGroup, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryGroup), nil
	}
}

func (d dictionaryGroupDo) Find() ([]*model.DictionaryGroup, error) {
	result, err := d.DO.Find()
	return result.([]*model.DictionaryGroup), err
}

func (d dictionaryGroupDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DictionaryGroup, err error) {
	buf := make([]*model.DictionaryGroup, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dictionaryGroupDo) FindInBatches(result *[]*model.DictionaryGroup, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dictionaryGroupDo) Attrs(attrs ...field.AssignExpr) IDictionaryGroupDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dictionaryGroupDo) Assign(attrs ...field.AssignExpr) IDictionaryGroupDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dictionaryGroupDo) Joins(fields ...field.RelationField) IDictionaryGroupDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dictionaryGroupDo) Preload(fields ...field.RelationField) IDictionaryGroupDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dictionaryGroupDo) FirstOrInit() (*model.DictionaryGroup, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryGroup), nil
	}
}

func (d dictionaryGroupDo) FirstOrCreate() (*model.DictionaryGroup, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryGroup), nil
	}
}

func (d dictionaryGroupDo) FindByPage(offset int, limit int) (result []*model.DictionaryGroup, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dictionaryGroupDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dictionaryGroupDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dictionaryGroupDo) Delete(models ...*model.DictionaryGroup) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dictionaryGroupDo) withDO(do gen.Dao) *dictionaryGroupDo {
	d.DO = *do.(*gen.DO)
	return d
}
