// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                     = new(Query)
	Admin                 *admin
	AdminAuthDept         *adminAuthDept
	AdminAuthRole         *adminAuthRole
	AdminAuthRoleAccess   *adminAuthRoleAccess
	AdminAuthRule         *adminAuthRule
	Attachment            *attachment
	CommonMessage         *commonMessage
	DictionaryData        *dictionaryData
	DictionaryGroup       *dictionaryGroup
	HomeQuickop           *homeQuickop
	LoginLog              *loginLog
	Member                *member
	OperationLog          *operationLog
	RobotdogDog           *robotdogDog
	RobotdogMap           *robotdogMap
	RobotdogRoute         *robotdogRoute
	RobotdogRouteWaypoint *robotdogRouteWaypoint
	RobotdogTask          *robotdogTask
	RobotdogWaypoint      *robotdogWaypoint
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Admin = &Q.Admin
	AdminAuthDept = &Q.AdminAuthDept
	AdminAuthRole = &Q.AdminAuthRole
	AdminAuthRoleAccess = &Q.AdminAuthRoleAccess
	AdminAuthRule = &Q.AdminAuthRule
	Attachment = &Q.Attachment
	CommonMessage = &Q.CommonMessage
	DictionaryData = &Q.DictionaryData
	DictionaryGroup = &Q.DictionaryGroup
	HomeQuickop = &Q.HomeQuickop
	LoginLog = &Q.LoginLog
	Member = &Q.Member
	OperationLog = &Q.OperationLog
	RobotdogDog = &Q.RobotdogDog
	RobotdogMap = &Q.RobotdogMap
	RobotdogRoute = &Q.RobotdogRoute
	RobotdogRouteWaypoint = &Q.RobotdogRouteWaypoint
	RobotdogTask = &Q.RobotdogTask
	RobotdogWaypoint = &Q.RobotdogWaypoint
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                    db,
		Admin:                 newAdmin(db, opts...),
		AdminAuthDept:         newAdminAuthDept(db, opts...),
		AdminAuthRole:         newAdminAuthRole(db, opts...),
		AdminAuthRoleAccess:   newAdminAuthRoleAccess(db, opts...),
		AdminAuthRule:         newAdminAuthRule(db, opts...),
		Attachment:            newAttachment(db, opts...),
		CommonMessage:         newCommonMessage(db, opts...),
		DictionaryData:        newDictionaryData(db, opts...),
		DictionaryGroup:       newDictionaryGroup(db, opts...),
		HomeQuickop:           newHomeQuickop(db, opts...),
		LoginLog:              newLoginLog(db, opts...),
		Member:                newMember(db, opts...),
		OperationLog:          newOperationLog(db, opts...),
		RobotdogDog:           newRobotdogDog(db, opts...),
		RobotdogMap:           newRobotdogMap(db, opts...),
		RobotdogRoute:         newRobotdogRoute(db, opts...),
		RobotdogRouteWaypoint: newRobotdogRouteWaypoint(db, opts...),
		RobotdogTask:          newRobotdogTask(db, opts...),
		RobotdogWaypoint:      newRobotdogWaypoint(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Admin                 admin
	AdminAuthDept         adminAuthDept
	AdminAuthRole         adminAuthRole
	AdminAuthRoleAccess   adminAuthRoleAccess
	AdminAuthRule         adminAuthRule
	Attachment            attachment
	CommonMessage         commonMessage
	DictionaryData        dictionaryData
	DictionaryGroup       dictionaryGroup
	HomeQuickop           homeQuickop
	LoginLog              loginLog
	Member                member
	OperationLog          operationLog
	RobotdogDog           robotdogDog
	RobotdogMap           robotdogMap
	RobotdogRoute         robotdogRoute
	RobotdogRouteWaypoint robotdogRouteWaypoint
	RobotdogTask          robotdogTask
	RobotdogWaypoint      robotdogWaypoint
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Admin:                 q.Admin.clone(db),
		AdminAuthDept:         q.AdminAuthDept.clone(db),
		AdminAuthRole:         q.AdminAuthRole.clone(db),
		AdminAuthRoleAccess:   q.AdminAuthRoleAccess.clone(db),
		AdminAuthRule:         q.AdminAuthRule.clone(db),
		Attachment:            q.Attachment.clone(db),
		CommonMessage:         q.CommonMessage.clone(db),
		DictionaryData:        q.DictionaryData.clone(db),
		DictionaryGroup:       q.DictionaryGroup.clone(db),
		HomeQuickop:           q.HomeQuickop.clone(db),
		LoginLog:              q.LoginLog.clone(db),
		Member:                q.Member.clone(db),
		OperationLog:          q.OperationLog.clone(db),
		RobotdogDog:           q.RobotdogDog.clone(db),
		RobotdogMap:           q.RobotdogMap.clone(db),
		RobotdogRoute:         q.RobotdogRoute.clone(db),
		RobotdogRouteWaypoint: q.RobotdogRouteWaypoint.clone(db),
		RobotdogTask:          q.RobotdogTask.clone(db),
		RobotdogWaypoint:      q.RobotdogWaypoint.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Admin:                 q.Admin.replaceDB(db),
		AdminAuthDept:         q.AdminAuthDept.replaceDB(db),
		AdminAuthRole:         q.AdminAuthRole.replaceDB(db),
		AdminAuthRoleAccess:   q.AdminAuthRoleAccess.replaceDB(db),
		AdminAuthRule:         q.AdminAuthRule.replaceDB(db),
		Attachment:            q.Attachment.replaceDB(db),
		CommonMessage:         q.CommonMessage.replaceDB(db),
		DictionaryData:        q.DictionaryData.replaceDB(db),
		DictionaryGroup:       q.DictionaryGroup.replaceDB(db),
		HomeQuickop:           q.HomeQuickop.replaceDB(db),
		LoginLog:              q.LoginLog.replaceDB(db),
		Member:                q.Member.replaceDB(db),
		OperationLog:          q.OperationLog.replaceDB(db),
		RobotdogDog:           q.RobotdogDog.replaceDB(db),
		RobotdogMap:           q.RobotdogMap.replaceDB(db),
		RobotdogRoute:         q.RobotdogRoute.replaceDB(db),
		RobotdogRouteWaypoint: q.RobotdogRouteWaypoint.replaceDB(db),
		RobotdogTask:          q.RobotdogTask.replaceDB(db),
		RobotdogWaypoint:      q.RobotdogWaypoint.replaceDB(db),
	}
}

type queryCtx struct {
	Admin                 IAdminDo
	AdminAuthDept         IAdminAuthDeptDo
	AdminAuthRole         IAdminAuthRoleDo
	AdminAuthRoleAccess   IAdminAuthRoleAccessDo
	AdminAuthRule         IAdminAuthRuleDo
	Attachment            IAttachmentDo
	CommonMessage         ICommonMessageDo
	DictionaryData        IDictionaryDataDo
	DictionaryGroup       IDictionaryGroupDo
	HomeQuickop           IHomeQuickopDo
	LoginLog              ILoginLogDo
	Member                IMemberDo
	OperationLog          IOperationLogDo
	RobotdogDog           IRobotdogDogDo
	RobotdogMap           IRobotdogMapDo
	RobotdogRoute         IRobotdogRouteDo
	RobotdogRouteWaypoint IRobotdogRouteWaypointDo
	RobotdogTask          IRobotdogTaskDo
	RobotdogWaypoint      IRobotdogWaypointDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Admin:                 q.Admin.WithContext(ctx),
		AdminAuthDept:         q.AdminAuthDept.WithContext(ctx),
		AdminAuthRole:         q.AdminAuthRole.WithContext(ctx),
		AdminAuthRoleAccess:   q.AdminAuthRoleAccess.WithContext(ctx),
		AdminAuthRule:         q.AdminAuthRule.WithContext(ctx),
		Attachment:            q.Attachment.WithContext(ctx),
		CommonMessage:         q.CommonMessage.WithContext(ctx),
		DictionaryData:        q.DictionaryData.WithContext(ctx),
		DictionaryGroup:       q.DictionaryGroup.WithContext(ctx),
		HomeQuickop:           q.HomeQuickop.WithContext(ctx),
		LoginLog:              q.LoginLog.WithContext(ctx),
		Member:                q.Member.WithContext(ctx),
		OperationLog:          q.OperationLog.WithContext(ctx),
		RobotdogDog:           q.RobotdogDog.WithContext(ctx),
		RobotdogMap:           q.RobotdogMap.WithContext(ctx),
		RobotdogRoute:         q.RobotdogRoute.WithContext(ctx),
		RobotdogRouteWaypoint: q.RobotdogRouteWaypoint.WithContext(ctx),
		RobotdogTask:          q.RobotdogTask.WithContext(ctx),
		RobotdogWaypoint:      q.RobotdogWaypoint.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
