// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newGeneratecodeField(db *gorm.DB, opts ...gen.DOOption) generatecodeField {
	_generatecodeField := generatecodeField{}

	_generatecodeField.generatecodeFieldDo.UseDB(db, opts...)
	_generatecodeField.generatecodeFieldDo.UseModel(&model.GeneratecodeField{})

	tableName := _generatecodeField.generatecodeFieldDo.TableName()
	_generatecodeField.ALL = field.NewAsterisk(tableName)
	_generatecodeField.ID = field.NewInt32(tableName, "id")
	_generatecodeField.GeneratecodeID = field.NewInt32(tableName, "generatecode_id")
	_generatecodeField.Islist = field.NewInt8(tableName, "islist")
	_generatecodeField.Name = field.NewString(tableName, "name")
	_generatecodeField.Field = field.NewString(tableName, "field")
	_generatecodeField.DataType = field.NewString(tableName, "data_type")
	_generatecodeField.Isorder = field.NewInt8(tableName, "isorder")
	_generatecodeField.Align = field.NewString(tableName, "align")
	_generatecodeField.Width = field.NewInt32(tableName, "width")
	_generatecodeField.ShowUI = field.NewString(tableName, "show_ui")
	_generatecodeField.Isform = field.NewInt8(tableName, "isform")
	_generatecodeField.Required = field.NewInt8(tableName, "required")
	_generatecodeField.Formtype = field.NewString(tableName, "formtype")
	_generatecodeField.Datatable = field.NewString(tableName, "datatable")
	_generatecodeField.Datatablename = field.NewString(tableName, "datatablename")
	_generatecodeField.DicGroupID = field.NewInt32(tableName, "dic_group_id")
	_generatecodeField.Issearch = field.NewInt8(tableName, "issearch")
	_generatecodeField.Searchway = field.NewString(tableName, "searchway")
	_generatecodeField.Searchtype = field.NewString(tableName, "searchtype")
	_generatecodeField.FieldWeigh = field.NewInt32(tableName, "field_weigh")
	_generatecodeField.ListWeigh = field.NewInt32(tableName, "list_weigh")
	_generatecodeField.SearchWeigh = field.NewInt32(tableName, "search_weigh")
	_generatecodeField.DefValue = field.NewString(tableName, "def_value")
	_generatecodeField.OptionValue = field.NewString(tableName, "option_value")
	_generatecodeField.Gridwidth = field.NewInt32(tableName, "gridwidth")
	_generatecodeField.Searchwidth = field.NewInt32(tableName, "searchwidth")

	_generatecodeField.fillFieldMap()

	return _generatecodeField
}

// generatecodeField 生成代码字段管理
type generatecodeField struct {
	generatecodeFieldDo

	ALL            field.Asterisk
	ID             field.Int32
	GeneratecodeID field.Int32  // 关联列表
	Islist         field.Int8   // 是否是列表1=是
	Name           field.String // 字段名称
	Field          field.String // 字段
	DataType       field.String // 数据库原生字段类型
	Isorder        field.Int8   // 是否参与排序
	Align          field.String // 对齐方向
	Width          field.Int32  // 宽度
	ShowUI         field.String // 显示UI
	Isform         field.Int8   // 是否为表单字段
	Required       field.Int8   // 是否为必填项
	Formtype       field.String // 表单类型
	Datatable      field.String // 关联数据表
	Datatablename  field.String // 关联显示字段
	DicGroupID     field.Int32  // 关联字典分组id
	Issearch       field.Int8   // 是否查询
	Searchway      field.String // 查询方式
	Searchtype     field.String // 查询文本类型
	FieldWeigh     field.Int32  // 表单排序
	ListWeigh      field.Int32  // 列表排序
	SearchWeigh    field.Int32  // 搜索排序
	DefValue       field.String // 默认值
	OptionValue    field.String // 选项值
	Gridwidth      field.Int32  // 布局栅格
	Searchwidth    field.Int32  // 搜索表单宽

	fieldMap map[string]field.Expr
}

func (g generatecodeField) Table(newTableName string) *generatecodeField {
	g.generatecodeFieldDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g generatecodeField) As(alias string) *generatecodeField {
	g.generatecodeFieldDo.DO = *(g.generatecodeFieldDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *generatecodeField) updateTableName(table string) *generatecodeField {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt32(table, "id")
	g.GeneratecodeID = field.NewInt32(table, "generatecode_id")
	g.Islist = field.NewInt8(table, "islist")
	g.Name = field.NewString(table, "name")
	g.Field = field.NewString(table, "field")
	g.DataType = field.NewString(table, "data_type")
	g.Isorder = field.NewInt8(table, "isorder")
	g.Align = field.NewString(table, "align")
	g.Width = field.NewInt32(table, "width")
	g.ShowUI = field.NewString(table, "show_ui")
	g.Isform = field.NewInt8(table, "isform")
	g.Required = field.NewInt8(table, "required")
	g.Formtype = field.NewString(table, "formtype")
	g.Datatable = field.NewString(table, "datatable")
	g.Datatablename = field.NewString(table, "datatablename")
	g.DicGroupID = field.NewInt32(table, "dic_group_id")
	g.Issearch = field.NewInt8(table, "issearch")
	g.Searchway = field.NewString(table, "searchway")
	g.Searchtype = field.NewString(table, "searchtype")
	g.FieldWeigh = field.NewInt32(table, "field_weigh")
	g.ListWeigh = field.NewInt32(table, "list_weigh")
	g.SearchWeigh = field.NewInt32(table, "search_weigh")
	g.DefValue = field.NewString(table, "def_value")
	g.OptionValue = field.NewString(table, "option_value")
	g.Gridwidth = field.NewInt32(table, "gridwidth")
	g.Searchwidth = field.NewInt32(table, "searchwidth")

	g.fillFieldMap()

	return g
}

func (g *generatecodeField) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *generatecodeField) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 26)
	g.fieldMap["id"] = g.ID
	g.fieldMap["generatecode_id"] = g.GeneratecodeID
	g.fieldMap["islist"] = g.Islist
	g.fieldMap["name"] = g.Name
	g.fieldMap["field"] = g.Field
	g.fieldMap["data_type"] = g.DataType
	g.fieldMap["isorder"] = g.Isorder
	g.fieldMap["align"] = g.Align
	g.fieldMap["width"] = g.Width
	g.fieldMap["show_ui"] = g.ShowUI
	g.fieldMap["isform"] = g.Isform
	g.fieldMap["required"] = g.Required
	g.fieldMap["formtype"] = g.Formtype
	g.fieldMap["datatable"] = g.Datatable
	g.fieldMap["datatablename"] = g.Datatablename
	g.fieldMap["dic_group_id"] = g.DicGroupID
	g.fieldMap["issearch"] = g.Issearch
	g.fieldMap["searchway"] = g.Searchway
	g.fieldMap["searchtype"] = g.Searchtype
	g.fieldMap["field_weigh"] = g.FieldWeigh
	g.fieldMap["list_weigh"] = g.ListWeigh
	g.fieldMap["search_weigh"] = g.SearchWeigh
	g.fieldMap["def_value"] = g.DefValue
	g.fieldMap["option_value"] = g.OptionValue
	g.fieldMap["gridwidth"] = g.Gridwidth
	g.fieldMap["searchwidth"] = g.Searchwidth
}

func (g generatecodeField) clone(db *gorm.DB) generatecodeField {
	g.generatecodeFieldDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g generatecodeField) replaceDB(db *gorm.DB) generatecodeField {
	g.generatecodeFieldDo.ReplaceDB(db)
	return g
}

type generatecodeFieldDo struct{ gen.DO }

type IGeneratecodeFieldDo interface {
	gen.SubQuery
	Debug() IGeneratecodeFieldDo
	WithContext(ctx context.Context) IGeneratecodeFieldDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGeneratecodeFieldDo
	WriteDB() IGeneratecodeFieldDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGeneratecodeFieldDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGeneratecodeFieldDo
	Not(conds ...gen.Condition) IGeneratecodeFieldDo
	Or(conds ...gen.Condition) IGeneratecodeFieldDo
	Select(conds ...field.Expr) IGeneratecodeFieldDo
	Where(conds ...gen.Condition) IGeneratecodeFieldDo
	Order(conds ...field.Expr) IGeneratecodeFieldDo
	Distinct(cols ...field.Expr) IGeneratecodeFieldDo
	Omit(cols ...field.Expr) IGeneratecodeFieldDo
	Join(table schema.Tabler, on ...field.Expr) IGeneratecodeFieldDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGeneratecodeFieldDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGeneratecodeFieldDo
	Group(cols ...field.Expr) IGeneratecodeFieldDo
	Having(conds ...gen.Condition) IGeneratecodeFieldDo
	Limit(limit int) IGeneratecodeFieldDo
	Offset(offset int) IGeneratecodeFieldDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGeneratecodeFieldDo
	Unscoped() IGeneratecodeFieldDo
	Create(values ...*model.GeneratecodeField) error
	CreateInBatches(values []*model.GeneratecodeField, batchSize int) error
	Save(values ...*model.GeneratecodeField) error
	First() (*model.GeneratecodeField, error)
	Take() (*model.GeneratecodeField, error)
	Last() (*model.GeneratecodeField, error)
	Find() ([]*model.GeneratecodeField, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GeneratecodeField, err error)
	FindInBatches(result *[]*model.GeneratecodeField, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GeneratecodeField) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGeneratecodeFieldDo
	Assign(attrs ...field.AssignExpr) IGeneratecodeFieldDo
	Joins(fields ...field.RelationField) IGeneratecodeFieldDo
	Preload(fields ...field.RelationField) IGeneratecodeFieldDo
	FirstOrInit() (*model.GeneratecodeField, error)
	FirstOrCreate() (*model.GeneratecodeField, error)
	FindByPage(offset int, limit int) (result []*model.GeneratecodeField, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGeneratecodeFieldDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g generatecodeFieldDo) Debug() IGeneratecodeFieldDo {
	return g.withDO(g.DO.Debug())
}

func (g generatecodeFieldDo) WithContext(ctx context.Context) IGeneratecodeFieldDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g generatecodeFieldDo) ReadDB() IGeneratecodeFieldDo {
	return g.Clauses(dbresolver.Read)
}

func (g generatecodeFieldDo) WriteDB() IGeneratecodeFieldDo {
	return g.Clauses(dbresolver.Write)
}

func (g generatecodeFieldDo) Session(config *gorm.Session) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Session(config))
}

func (g generatecodeFieldDo) Clauses(conds ...clause.Expression) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g generatecodeFieldDo) Returning(value interface{}, columns ...string) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g generatecodeFieldDo) Not(conds ...gen.Condition) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g generatecodeFieldDo) Or(conds ...gen.Condition) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g generatecodeFieldDo) Select(conds ...field.Expr) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g generatecodeFieldDo) Where(conds ...gen.Condition) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g generatecodeFieldDo) Order(conds ...field.Expr) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g generatecodeFieldDo) Distinct(cols ...field.Expr) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g generatecodeFieldDo) Omit(cols ...field.Expr) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g generatecodeFieldDo) Join(table schema.Tabler, on ...field.Expr) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g generatecodeFieldDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGeneratecodeFieldDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g generatecodeFieldDo) RightJoin(table schema.Tabler, on ...field.Expr) IGeneratecodeFieldDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g generatecodeFieldDo) Group(cols ...field.Expr) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g generatecodeFieldDo) Having(conds ...gen.Condition) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g generatecodeFieldDo) Limit(limit int) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g generatecodeFieldDo) Offset(offset int) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g generatecodeFieldDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g generatecodeFieldDo) Unscoped() IGeneratecodeFieldDo {
	return g.withDO(g.DO.Unscoped())
}

func (g generatecodeFieldDo) Create(values ...*model.GeneratecodeField) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g generatecodeFieldDo) CreateInBatches(values []*model.GeneratecodeField, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g generatecodeFieldDo) Save(values ...*model.GeneratecodeField) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g generatecodeFieldDo) First() (*model.GeneratecodeField, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeneratecodeField), nil
	}
}

func (g generatecodeFieldDo) Take() (*model.GeneratecodeField, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeneratecodeField), nil
	}
}

func (g generatecodeFieldDo) Last() (*model.GeneratecodeField, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeneratecodeField), nil
	}
}

func (g generatecodeFieldDo) Find() ([]*model.GeneratecodeField, error) {
	result, err := g.DO.Find()
	return result.([]*model.GeneratecodeField), err
}

func (g generatecodeFieldDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GeneratecodeField, err error) {
	buf := make([]*model.GeneratecodeField, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g generatecodeFieldDo) FindInBatches(result *[]*model.GeneratecodeField, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g generatecodeFieldDo) Attrs(attrs ...field.AssignExpr) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g generatecodeFieldDo) Assign(attrs ...field.AssignExpr) IGeneratecodeFieldDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g generatecodeFieldDo) Joins(fields ...field.RelationField) IGeneratecodeFieldDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g generatecodeFieldDo) Preload(fields ...field.RelationField) IGeneratecodeFieldDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g generatecodeFieldDo) FirstOrInit() (*model.GeneratecodeField, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeneratecodeField), nil
	}
}

func (g generatecodeFieldDo) FirstOrCreate() (*model.GeneratecodeField, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GeneratecodeField), nil
	}
}

func (g generatecodeFieldDo) FindByPage(offset int, limit int) (result []*model.GeneratecodeField, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g generatecodeFieldDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g generatecodeFieldDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g generatecodeFieldDo) Delete(models ...*model.GeneratecodeField) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *generatecodeFieldDo) withDO(do gen.Dao) *generatecodeFieldDo {
	g.DO = *do.(*gen.DO)
	return g
}
