// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newGeneratecode(db *gorm.DB, opts ...gen.DOOption) generatecode {
	_generatecode := generatecode{}

	_generatecode.generatecodeDo.UseDB(db, opts...)
	_generatecode.generatecodeDo.UseModel(&model.Generatecode{})

	tableName := _generatecode.generatecodeDo.TableName()
	_generatecode.ALL = field.NewAsterisk(tableName)
	_generatecode.ID = field.NewInt32(tableName, "id")
	_generatecode.Fromtype = field.NewInt8(tableName, "fromtype")
	_generatecode.Tablename = field.NewString(tableName, "tablename")
	_generatecode.Comment = field.NewString(tableName, "comment")
	_generatecode.Engine = field.NewString(tableName, "engine")
	_generatecode.TableRows = field.NewInt32(tableName, "table_rows")
	_generatecode.Collation = field.NewString(tableName, "collation")
	_generatecode.AutoIncrement = field.NewInt32(tableName, "auto_increment")
	_generatecode.Status = field.NewInt8(tableName, "status")
	_generatecode.Pid = field.NewInt32(tableName, "pid")
	_generatecode.Icon = field.NewString(tableName, "icon")
	_generatecode.Routepath = field.NewString(tableName, "routepath")
	_generatecode.Routename = field.NewString(tableName, "routename")
	_generatecode.Component = field.NewString(tableName, "component")
	_generatecode.Godir = field.NewString(tableName, "godir")
	_generatecode.APIPath = field.NewString(tableName, "api_path")
	_generatecode.APIFilename = field.NewString(tableName, "api_filename")
	_generatecode.Fields = field.NewString(tableName, "fields")
	_generatecode.RuleID = field.NewInt32(tableName, "rule_id")
	_generatecode.RuleName = field.NewString(tableName, "rule_name")
	_generatecode.Codelocation = field.NewString(tableName, "codelocation")
	_generatecode.IsInstall = field.NewInt8(tableName, "is_install")
	_generatecode.TplType = field.NewString(tableName, "tpl_type")
	_generatecode.CateTablename = field.NewString(tableName, "cate_tablename")
	_generatecode.CreatedAt = field.NewTime(tableName, "created_at")
	_generatecode.UpdatedAt = field.NewTime(tableName, "updated_at")

	_generatecode.fillFieldMap()

	return _generatecode
}

// generatecode 代码生成
type generatecode struct {
	generatecodeDo

	ALL           field.Asterisk
	ID            field.Int32
	Fromtype      field.Int8   // 数据类型0=数据表，1=代码工具
	Tablename     field.String // 表名称
	Comment       field.String // 表备注
	Engine        field.String // 引擎
	TableRows     field.Int32  // 记录数
	Collation     field.String // 编码
	AutoIncrement field.Int32  // 自增索引
	Status        field.Int8   // 状态1=禁用
	Pid           field.Int32  // 菜单上级
	Icon          field.String // 图标
	Routepath     field.String // 路由地址
	Routename     field.String // 路由名称
	Component     field.String // 组件路径
	Godir         field.String // 后端代码位置
	APIPath       field.String // 后端业务接口
	APIFilename   field.String // 后端文件名
	Fields        field.String // 查询字段
	RuleID        field.Int32  // 生成菜单id
	RuleName      field.String // 菜单名称
	Codelocation  field.String // 生成代码位置
	IsInstall     field.Int8   // 是否安装0=未安装，1=已安装，2=已卸载
	TplType       field.String // 模板类型list=仅一个数据，cate=数据加分类
	CateTablename field.String // 分类表名称
	CreatedAt     field.Time   // 上传时间
	UpdatedAt     field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (g generatecode) Table(newTableName string) *generatecode {
	g.generatecodeDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g generatecode) As(alias string) *generatecode {
	g.generatecodeDo.DO = *(g.generatecodeDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *generatecode) updateTableName(table string) *generatecode {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt32(table, "id")
	g.Fromtype = field.NewInt8(table, "fromtype")
	g.Tablename = field.NewString(table, "tablename")
	g.Comment = field.NewString(table, "comment")
	g.Engine = field.NewString(table, "engine")
	g.TableRows = field.NewInt32(table, "table_rows")
	g.Collation = field.NewString(table, "collation")
	g.AutoIncrement = field.NewInt32(table, "auto_increment")
	g.Status = field.NewInt8(table, "status")
	g.Pid = field.NewInt32(table, "pid")
	g.Icon = field.NewString(table, "icon")
	g.Routepath = field.NewString(table, "routepath")
	g.Routename = field.NewString(table, "routename")
	g.Component = field.NewString(table, "component")
	g.Godir = field.NewString(table, "godir")
	g.APIPath = field.NewString(table, "api_path")
	g.APIFilename = field.NewString(table, "api_filename")
	g.Fields = field.NewString(table, "fields")
	g.RuleID = field.NewInt32(table, "rule_id")
	g.RuleName = field.NewString(table, "rule_name")
	g.Codelocation = field.NewString(table, "codelocation")
	g.IsInstall = field.NewInt8(table, "is_install")
	g.TplType = field.NewString(table, "tpl_type")
	g.CateTablename = field.NewString(table, "cate_tablename")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")

	g.fillFieldMap()

	return g
}

func (g *generatecode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *generatecode) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 26)
	g.fieldMap["id"] = g.ID
	g.fieldMap["fromtype"] = g.Fromtype
	g.fieldMap["tablename"] = g.Tablename
	g.fieldMap["comment"] = g.Comment
	g.fieldMap["engine"] = g.Engine
	g.fieldMap["table_rows"] = g.TableRows
	g.fieldMap["collation"] = g.Collation
	g.fieldMap["auto_increment"] = g.AutoIncrement
	g.fieldMap["status"] = g.Status
	g.fieldMap["pid"] = g.Pid
	g.fieldMap["icon"] = g.Icon
	g.fieldMap["routepath"] = g.Routepath
	g.fieldMap["routename"] = g.Routename
	g.fieldMap["component"] = g.Component
	g.fieldMap["godir"] = g.Godir
	g.fieldMap["api_path"] = g.APIPath
	g.fieldMap["api_filename"] = g.APIFilename
	g.fieldMap["fields"] = g.Fields
	g.fieldMap["rule_id"] = g.RuleID
	g.fieldMap["rule_name"] = g.RuleName
	g.fieldMap["codelocation"] = g.Codelocation
	g.fieldMap["is_install"] = g.IsInstall
	g.fieldMap["tpl_type"] = g.TplType
	g.fieldMap["cate_tablename"] = g.CateTablename
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g generatecode) clone(db *gorm.DB) generatecode {
	g.generatecodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g generatecode) replaceDB(db *gorm.DB) generatecode {
	g.generatecodeDo.ReplaceDB(db)
	return g
}

type generatecodeDo struct{ gen.DO }

type IGeneratecodeDo interface {
	gen.SubQuery
	Debug() IGeneratecodeDo
	WithContext(ctx context.Context) IGeneratecodeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGeneratecodeDo
	WriteDB() IGeneratecodeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGeneratecodeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGeneratecodeDo
	Not(conds ...gen.Condition) IGeneratecodeDo
	Or(conds ...gen.Condition) IGeneratecodeDo
	Select(conds ...field.Expr) IGeneratecodeDo
	Where(conds ...gen.Condition) IGeneratecodeDo
	Order(conds ...field.Expr) IGeneratecodeDo
	Distinct(cols ...field.Expr) IGeneratecodeDo
	Omit(cols ...field.Expr) IGeneratecodeDo
	Join(table schema.Tabler, on ...field.Expr) IGeneratecodeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGeneratecodeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGeneratecodeDo
	Group(cols ...field.Expr) IGeneratecodeDo
	Having(conds ...gen.Condition) IGeneratecodeDo
	Limit(limit int) IGeneratecodeDo
	Offset(offset int) IGeneratecodeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGeneratecodeDo
	Unscoped() IGeneratecodeDo
	Create(values ...*model.Generatecode) error
	CreateInBatches(values []*model.Generatecode, batchSize int) error
	Save(values ...*model.Generatecode) error
	First() (*model.Generatecode, error)
	Take() (*model.Generatecode, error)
	Last() (*model.Generatecode, error)
	Find() ([]*model.Generatecode, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Generatecode, err error)
	FindInBatches(result *[]*model.Generatecode, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Generatecode) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGeneratecodeDo
	Assign(attrs ...field.AssignExpr) IGeneratecodeDo
	Joins(fields ...field.RelationField) IGeneratecodeDo
	Preload(fields ...field.RelationField) IGeneratecodeDo
	FirstOrInit() (*model.Generatecode, error)
	FirstOrCreate() (*model.Generatecode, error)
	FindByPage(offset int, limit int) (result []*model.Generatecode, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGeneratecodeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g generatecodeDo) Debug() IGeneratecodeDo {
	return g.withDO(g.DO.Debug())
}

func (g generatecodeDo) WithContext(ctx context.Context) IGeneratecodeDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g generatecodeDo) ReadDB() IGeneratecodeDo {
	return g.Clauses(dbresolver.Read)
}

func (g generatecodeDo) WriteDB() IGeneratecodeDo {
	return g.Clauses(dbresolver.Write)
}

func (g generatecodeDo) Session(config *gorm.Session) IGeneratecodeDo {
	return g.withDO(g.DO.Session(config))
}

func (g generatecodeDo) Clauses(conds ...clause.Expression) IGeneratecodeDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g generatecodeDo) Returning(value interface{}, columns ...string) IGeneratecodeDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g generatecodeDo) Not(conds ...gen.Condition) IGeneratecodeDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g generatecodeDo) Or(conds ...gen.Condition) IGeneratecodeDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g generatecodeDo) Select(conds ...field.Expr) IGeneratecodeDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g generatecodeDo) Where(conds ...gen.Condition) IGeneratecodeDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g generatecodeDo) Order(conds ...field.Expr) IGeneratecodeDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g generatecodeDo) Distinct(cols ...field.Expr) IGeneratecodeDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g generatecodeDo) Omit(cols ...field.Expr) IGeneratecodeDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g generatecodeDo) Join(table schema.Tabler, on ...field.Expr) IGeneratecodeDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g generatecodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGeneratecodeDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g generatecodeDo) RightJoin(table schema.Tabler, on ...field.Expr) IGeneratecodeDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g generatecodeDo) Group(cols ...field.Expr) IGeneratecodeDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g generatecodeDo) Having(conds ...gen.Condition) IGeneratecodeDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g generatecodeDo) Limit(limit int) IGeneratecodeDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g generatecodeDo) Offset(offset int) IGeneratecodeDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g generatecodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGeneratecodeDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g generatecodeDo) Unscoped() IGeneratecodeDo {
	return g.withDO(g.DO.Unscoped())
}

func (g generatecodeDo) Create(values ...*model.Generatecode) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g generatecodeDo) CreateInBatches(values []*model.Generatecode, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g generatecodeDo) Save(values ...*model.Generatecode) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g generatecodeDo) First() (*model.Generatecode, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Generatecode), nil
	}
}

func (g generatecodeDo) Take() (*model.Generatecode, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Generatecode), nil
	}
}

func (g generatecodeDo) Last() (*model.Generatecode, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Generatecode), nil
	}
}

func (g generatecodeDo) Find() ([]*model.Generatecode, error) {
	result, err := g.DO.Find()
	return result.([]*model.Generatecode), err
}

func (g generatecodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Generatecode, err error) {
	buf := make([]*model.Generatecode, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g generatecodeDo) FindInBatches(result *[]*model.Generatecode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g generatecodeDo) Attrs(attrs ...field.AssignExpr) IGeneratecodeDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g generatecodeDo) Assign(attrs ...field.AssignExpr) IGeneratecodeDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g generatecodeDo) Joins(fields ...field.RelationField) IGeneratecodeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g generatecodeDo) Preload(fields ...field.RelationField) IGeneratecodeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g generatecodeDo) FirstOrInit() (*model.Generatecode, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Generatecode), nil
	}
}

func (g generatecodeDo) FirstOrCreate() (*model.Generatecode, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Generatecode), nil
	}
}

func (g generatecodeDo) FindByPage(offset int, limit int) (result []*model.Generatecode, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g generatecodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g generatecodeDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g generatecodeDo) Delete(models ...*model.Generatecode) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *generatecodeDo) withDO(do gen.Dao) *generatecodeDo {
	g.DO = *do.(*gen.DO)
	return g
}
