// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newHomeQuickop(db *gorm.DB, opts ...gen.DOOption) homeQuickop {
	_homeQuickop := homeQuickop{}

	_homeQuickop.homeQuickopDo.UseDB(db, opts...)
	_homeQuickop.homeQuickopDo.UseModel(&model.HomeQuickop{})

	tableName := _homeQuickop.homeQuickopDo.TableName()
	_homeQuickop.ALL = field.NewAsterisk(tableName)
	_homeQuickop.ID = field.NewInt32(tableName, "id")
	_homeQuickop.TenantID = field.NewInt32(tableName, "tenant_id")
	_homeQuickop.UID = field.NewInt32(tableName, "uid")
	_homeQuickop.IsCommon = field.NewInt8(tableName, "is_common")
	_homeQuickop.Type = field.NewInt8(tableName, "type")
	_homeQuickop.Name = field.NewString(tableName, "name")
	_homeQuickop.PathURL = field.NewString(tableName, "path_url")
	_homeQuickop.Icon = field.NewString(tableName, "icon")
	_homeQuickop.Weigh = field.NewInt32(tableName, "weigh")

	_homeQuickop.fillFieldMap()

	return _homeQuickop
}

// homeQuickop 首页快捷操作
type homeQuickop struct {
	homeQuickopDo

	ALL      field.Asterisk
	ID       field.Int32
	TenantID field.Int32  // 租户唯一标识
	UID      field.Int32  // 添加人
	IsCommon field.Int8   // 公共1=是
	Type     field.Int8   // 类型1=外部
	Name     field.String // 快捷名称
	PathURL  field.String // 跳转路径
	Icon     field.String // 图标
	Weigh    field.Int32  // 权重

	fieldMap map[string]field.Expr
}

func (h homeQuickop) Table(newTableName string) *homeQuickop {
	h.homeQuickopDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h homeQuickop) As(alias string) *homeQuickop {
	h.homeQuickopDo.DO = *(h.homeQuickopDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *homeQuickop) updateTableName(table string) *homeQuickop {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt32(table, "id")
	h.TenantID = field.NewInt32(table, "tenant_id")
	h.UID = field.NewInt32(table, "uid")
	h.IsCommon = field.NewInt8(table, "is_common")
	h.Type = field.NewInt8(table, "type")
	h.Name = field.NewString(table, "name")
	h.PathURL = field.NewString(table, "path_url")
	h.Icon = field.NewString(table, "icon")
	h.Weigh = field.NewInt32(table, "weigh")

	h.fillFieldMap()

	return h
}

func (h *homeQuickop) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *homeQuickop) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 9)
	h.fieldMap["id"] = h.ID
	h.fieldMap["tenant_id"] = h.TenantID
	h.fieldMap["uid"] = h.UID
	h.fieldMap["is_common"] = h.IsCommon
	h.fieldMap["type"] = h.Type
	h.fieldMap["name"] = h.Name
	h.fieldMap["path_url"] = h.PathURL
	h.fieldMap["icon"] = h.Icon
	h.fieldMap["weigh"] = h.Weigh
}

func (h homeQuickop) clone(db *gorm.DB) homeQuickop {
	h.homeQuickopDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h homeQuickop) replaceDB(db *gorm.DB) homeQuickop {
	h.homeQuickopDo.ReplaceDB(db)
	return h
}

type homeQuickopDo struct{ gen.DO }

type IHomeQuickopDo interface {
	gen.SubQuery
	Debug() IHomeQuickopDo
	WithContext(ctx context.Context) IHomeQuickopDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHomeQuickopDo
	WriteDB() IHomeQuickopDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHomeQuickopDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHomeQuickopDo
	Not(conds ...gen.Condition) IHomeQuickopDo
	Or(conds ...gen.Condition) IHomeQuickopDo
	Select(conds ...field.Expr) IHomeQuickopDo
	Where(conds ...gen.Condition) IHomeQuickopDo
	Order(conds ...field.Expr) IHomeQuickopDo
	Distinct(cols ...field.Expr) IHomeQuickopDo
	Omit(cols ...field.Expr) IHomeQuickopDo
	Join(table schema.Tabler, on ...field.Expr) IHomeQuickopDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHomeQuickopDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHomeQuickopDo
	Group(cols ...field.Expr) IHomeQuickopDo
	Having(conds ...gen.Condition) IHomeQuickopDo
	Limit(limit int) IHomeQuickopDo
	Offset(offset int) IHomeQuickopDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHomeQuickopDo
	Unscoped() IHomeQuickopDo
	Create(values ...*model.HomeQuickop) error
	CreateInBatches(values []*model.HomeQuickop, batchSize int) error
	Save(values ...*model.HomeQuickop) error
	First() (*model.HomeQuickop, error)
	Take() (*model.HomeQuickop, error)
	Last() (*model.HomeQuickop, error)
	Find() ([]*model.HomeQuickop, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HomeQuickop, err error)
	FindInBatches(result *[]*model.HomeQuickop, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HomeQuickop) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHomeQuickopDo
	Assign(attrs ...field.AssignExpr) IHomeQuickopDo
	Joins(fields ...field.RelationField) IHomeQuickopDo
	Preload(fields ...field.RelationField) IHomeQuickopDo
	FirstOrInit() (*model.HomeQuickop, error)
	FirstOrCreate() (*model.HomeQuickop, error)
	FindByPage(offset int, limit int) (result []*model.HomeQuickop, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHomeQuickopDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h homeQuickopDo) Debug() IHomeQuickopDo {
	return h.withDO(h.DO.Debug())
}

func (h homeQuickopDo) WithContext(ctx context.Context) IHomeQuickopDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h homeQuickopDo) ReadDB() IHomeQuickopDo {
	return h.Clauses(dbresolver.Read)
}

func (h homeQuickopDo) WriteDB() IHomeQuickopDo {
	return h.Clauses(dbresolver.Write)
}

func (h homeQuickopDo) Session(config *gorm.Session) IHomeQuickopDo {
	return h.withDO(h.DO.Session(config))
}

func (h homeQuickopDo) Clauses(conds ...clause.Expression) IHomeQuickopDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h homeQuickopDo) Returning(value interface{}, columns ...string) IHomeQuickopDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h homeQuickopDo) Not(conds ...gen.Condition) IHomeQuickopDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h homeQuickopDo) Or(conds ...gen.Condition) IHomeQuickopDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h homeQuickopDo) Select(conds ...field.Expr) IHomeQuickopDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h homeQuickopDo) Where(conds ...gen.Condition) IHomeQuickopDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h homeQuickopDo) Order(conds ...field.Expr) IHomeQuickopDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h homeQuickopDo) Distinct(cols ...field.Expr) IHomeQuickopDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h homeQuickopDo) Omit(cols ...field.Expr) IHomeQuickopDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h homeQuickopDo) Join(table schema.Tabler, on ...field.Expr) IHomeQuickopDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h homeQuickopDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHomeQuickopDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h homeQuickopDo) RightJoin(table schema.Tabler, on ...field.Expr) IHomeQuickopDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h homeQuickopDo) Group(cols ...field.Expr) IHomeQuickopDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h homeQuickopDo) Having(conds ...gen.Condition) IHomeQuickopDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h homeQuickopDo) Limit(limit int) IHomeQuickopDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h homeQuickopDo) Offset(offset int) IHomeQuickopDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h homeQuickopDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHomeQuickopDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h homeQuickopDo) Unscoped() IHomeQuickopDo {
	return h.withDO(h.DO.Unscoped())
}

func (h homeQuickopDo) Create(values ...*model.HomeQuickop) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h homeQuickopDo) CreateInBatches(values []*model.HomeQuickop, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h homeQuickopDo) Save(values ...*model.HomeQuickop) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h homeQuickopDo) First() (*model.HomeQuickop, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HomeQuickop), nil
	}
}

func (h homeQuickopDo) Take() (*model.HomeQuickop, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HomeQuickop), nil
	}
}

func (h homeQuickopDo) Last() (*model.HomeQuickop, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HomeQuickop), nil
	}
}

func (h homeQuickopDo) Find() ([]*model.HomeQuickop, error) {
	result, err := h.DO.Find()
	return result.([]*model.HomeQuickop), err
}

func (h homeQuickopDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HomeQuickop, err error) {
	buf := make([]*model.HomeQuickop, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h homeQuickopDo) FindInBatches(result *[]*model.HomeQuickop, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h homeQuickopDo) Attrs(attrs ...field.AssignExpr) IHomeQuickopDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h homeQuickopDo) Assign(attrs ...field.AssignExpr) IHomeQuickopDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h homeQuickopDo) Joins(fields ...field.RelationField) IHomeQuickopDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h homeQuickopDo) Preload(fields ...field.RelationField) IHomeQuickopDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h homeQuickopDo) FirstOrInit() (*model.HomeQuickop, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HomeQuickop), nil
	}
}

func (h homeQuickopDo) FirstOrCreate() (*model.HomeQuickop, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HomeQuickop), nil
	}
}

func (h homeQuickopDo) FindByPage(offset int, limit int) (result []*model.HomeQuickop, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h homeQuickopDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h homeQuickopDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h homeQuickopDo) Delete(models ...*model.HomeQuickop) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *homeQuickopDo) withDO(do gen.Dao) *homeQuickopDo {
	h.DO = *do.(*gen.DO)
	return h
}
