// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newRobotdogWaypoint(db *gorm.DB, opts ...gen.DOOption) robotdogWaypoint {
	_robotdogWaypoint := robotdogWaypoint{}

	_robotdogWaypoint.robotdogWaypointDo.UseDB(db, opts...)
	_robotdogWaypoint.robotdogWaypointDo.UseModel(&model.RobotdogWaypoint{})

	tableName := _robotdogWaypoint.robotdogWaypointDo.TableName()
	_robotdogWaypoint.ALL = field.NewAsterisk(tableName)
	_robotdogWaypoint.ID = field.NewInt64(tableName, "id")
	_robotdogWaypoint.TenantID = field.NewInt32(tableName, "tenant_id")
	_robotdogWaypoint.MapID = field.NewInt64(tableName, "map_id")
	_robotdogWaypoint.Name = field.NewString(tableName, "name")
	_robotdogWaypoint.X = field.NewFloat64(tableName, "x")
	_robotdogWaypoint.Y = field.NewFloat64(tableName, "y")
	_robotdogWaypoint.Z = field.NewFloat64(tableName, "z")
	_robotdogWaypoint.Yaw = field.NewFloat64(tableName, "yaw")
	_robotdogWaypoint.Remark = field.NewString(tableName, "remark")
	_robotdogWaypoint.CreatedAt = field.NewTime(tableName, "created_at")
	_robotdogWaypoint.UpdatedAt = field.NewTime(tableName, "updated_at")
	_robotdogWaypoint.DeletedAt = field.NewField(tableName, "deleted_at")

	_robotdogWaypoint.fillFieldMap()

	return _robotdogWaypoint
}

// robotdogWaypoint 机械狗航点
type robotdogWaypoint struct {
	robotdogWaypointDo

	ALL       field.Asterisk
	ID        field.Int64   // ID
	TenantID  field.Int32   // 租户唯一标识
	MapID     field.Int64   // 地图ID
	Name      field.String  // 航点名称
	X         field.Float64 // X坐标
	Y         field.Float64 // Y坐标
	Z         field.Float64 // Z坐标
	Yaw       field.Float64 // 航向角
	Remark    field.String  // 备注
	CreatedAt field.Time    // 创建时间
	UpdatedAt field.Time    // 更新时间
	DeletedAt field.Field   // 删除时间

	fieldMap map[string]field.Expr
}

func (r robotdogWaypoint) Table(newTableName string) *robotdogWaypoint {
	r.robotdogWaypointDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r robotdogWaypoint) As(alias string) *robotdogWaypoint {
	r.robotdogWaypointDo.DO = *(r.robotdogWaypointDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *robotdogWaypoint) updateTableName(table string) *robotdogWaypoint {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.TenantID = field.NewInt32(table, "tenant_id")
	r.MapID = field.NewInt64(table, "map_id")
	r.Name = field.NewString(table, "name")
	r.X = field.NewFloat64(table, "x")
	r.Y = field.NewFloat64(table, "y")
	r.Z = field.NewFloat64(table, "z")
	r.Yaw = field.NewFloat64(table, "yaw")
	r.Remark = field.NewString(table, "remark")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *robotdogWaypoint) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *robotdogWaypoint) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 12)
	r.fieldMap["id"] = r.ID
	r.fieldMap["tenant_id"] = r.TenantID
	r.fieldMap["map_id"] = r.MapID
	r.fieldMap["name"] = r.Name
	r.fieldMap["x"] = r.X
	r.fieldMap["y"] = r.Y
	r.fieldMap["z"] = r.Z
	r.fieldMap["yaw"] = r.Yaw
	r.fieldMap["remark"] = r.Remark
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r robotdogWaypoint) clone(db *gorm.DB) robotdogWaypoint {
	r.robotdogWaypointDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r robotdogWaypoint) replaceDB(db *gorm.DB) robotdogWaypoint {
	r.robotdogWaypointDo.ReplaceDB(db)
	return r
}

type robotdogWaypointDo struct{ gen.DO }

type IRobotdogWaypointDo interface {
	gen.SubQuery
	Debug() IRobotdogWaypointDo
	WithContext(ctx context.Context) IRobotdogWaypointDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRobotdogWaypointDo
	WriteDB() IRobotdogWaypointDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRobotdogWaypointDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRobotdogWaypointDo
	Not(conds ...gen.Condition) IRobotdogWaypointDo
	Or(conds ...gen.Condition) IRobotdogWaypointDo
	Select(conds ...field.Expr) IRobotdogWaypointDo
	Where(conds ...gen.Condition) IRobotdogWaypointDo
	Order(conds ...field.Expr) IRobotdogWaypointDo
	Distinct(cols ...field.Expr) IRobotdogWaypointDo
	Omit(cols ...field.Expr) IRobotdogWaypointDo
	Join(table schema.Tabler, on ...field.Expr) IRobotdogWaypointDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogWaypointDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogWaypointDo
	Group(cols ...field.Expr) IRobotdogWaypointDo
	Having(conds ...gen.Condition) IRobotdogWaypointDo
	Limit(limit int) IRobotdogWaypointDo
	Offset(offset int) IRobotdogWaypointDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogWaypointDo
	Unscoped() IRobotdogWaypointDo
	Create(values ...*model.RobotdogWaypoint) error
	CreateInBatches(values []*model.RobotdogWaypoint, batchSize int) error
	Save(values ...*model.RobotdogWaypoint) error
	First() (*model.RobotdogWaypoint, error)
	Take() (*model.RobotdogWaypoint, error)
	Last() (*model.RobotdogWaypoint, error)
	Find() ([]*model.RobotdogWaypoint, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogWaypoint, err error)
	FindInBatches(result *[]*model.RobotdogWaypoint, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RobotdogWaypoint) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRobotdogWaypointDo
	Assign(attrs ...field.AssignExpr) IRobotdogWaypointDo
	Joins(fields ...field.RelationField) IRobotdogWaypointDo
	Preload(fields ...field.RelationField) IRobotdogWaypointDo
	FirstOrInit() (*model.RobotdogWaypoint, error)
	FirstOrCreate() (*model.RobotdogWaypoint, error)
	FindByPage(offset int, limit int) (result []*model.RobotdogWaypoint, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRobotdogWaypointDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r robotdogWaypointDo) Debug() IRobotdogWaypointDo {
	return r.withDO(r.DO.Debug())
}

func (r robotdogWaypointDo) WithContext(ctx context.Context) IRobotdogWaypointDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r robotdogWaypointDo) ReadDB() IRobotdogWaypointDo {
	return r.Clauses(dbresolver.Read)
}

func (r robotdogWaypointDo) WriteDB() IRobotdogWaypointDo {
	return r.Clauses(dbresolver.Write)
}

func (r robotdogWaypointDo) Session(config *gorm.Session) IRobotdogWaypointDo {
	return r.withDO(r.DO.Session(config))
}

func (r robotdogWaypointDo) Clauses(conds ...clause.Expression) IRobotdogWaypointDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r robotdogWaypointDo) Returning(value interface{}, columns ...string) IRobotdogWaypointDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r robotdogWaypointDo) Not(conds ...gen.Condition) IRobotdogWaypointDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r robotdogWaypointDo) Or(conds ...gen.Condition) IRobotdogWaypointDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r robotdogWaypointDo) Select(conds ...field.Expr) IRobotdogWaypointDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r robotdogWaypointDo) Where(conds ...gen.Condition) IRobotdogWaypointDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r robotdogWaypointDo) Order(conds ...field.Expr) IRobotdogWaypointDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r robotdogWaypointDo) Distinct(cols ...field.Expr) IRobotdogWaypointDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r robotdogWaypointDo) Omit(cols ...field.Expr) IRobotdogWaypointDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r robotdogWaypointDo) Join(table schema.Tabler, on ...field.Expr) IRobotdogWaypointDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r robotdogWaypointDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogWaypointDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r robotdogWaypointDo) RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogWaypointDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r robotdogWaypointDo) Group(cols ...field.Expr) IRobotdogWaypointDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r robotdogWaypointDo) Having(conds ...gen.Condition) IRobotdogWaypointDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r robotdogWaypointDo) Limit(limit int) IRobotdogWaypointDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r robotdogWaypointDo) Offset(offset int) IRobotdogWaypointDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r robotdogWaypointDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogWaypointDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r robotdogWaypointDo) Unscoped() IRobotdogWaypointDo {
	return r.withDO(r.DO.Unscoped())
}

func (r robotdogWaypointDo) Create(values ...*model.RobotdogWaypoint) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r robotdogWaypointDo) CreateInBatches(values []*model.RobotdogWaypoint, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r robotdogWaypointDo) Save(values ...*model.RobotdogWaypoint) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r robotdogWaypointDo) First() (*model.RobotdogWaypoint, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogWaypoint), nil
	}
}

func (r robotdogWaypointDo) Take() (*model.RobotdogWaypoint, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogWaypoint), nil
	}
}

func (r robotdogWaypointDo) Last() (*model.RobotdogWaypoint, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogWaypoint), nil
	}
}

func (r robotdogWaypointDo) Find() ([]*model.RobotdogWaypoint, error) {
	result, err := r.DO.Find()
	return result.([]*model.RobotdogWaypoint), err
}

func (r robotdogWaypointDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogWaypoint, err error) {
	buf := make([]*model.RobotdogWaypoint, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r robotdogWaypointDo) FindInBatches(result *[]*model.RobotdogWaypoint, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r robotdogWaypointDo) Attrs(attrs ...field.AssignExpr) IRobotdogWaypointDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r robotdogWaypointDo) Assign(attrs ...field.AssignExpr) IRobotdogWaypointDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r robotdogWaypointDo) Joins(fields ...field.RelationField) IRobotdogWaypointDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r robotdogWaypointDo) Preload(fields ...field.RelationField) IRobotdogWaypointDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r robotdogWaypointDo) FirstOrInit() (*model.RobotdogWaypoint, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogWaypoint), nil
	}
}

func (r robotdogWaypointDo) FirstOrCreate() (*model.RobotdogWaypoint, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogWaypoint), nil
	}
}

func (r robotdogWaypointDo) FindByPage(offset int, limit int) (result []*model.RobotdogWaypoint, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r robotdogWaypointDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r robotdogWaypointDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r robotdogWaypointDo) Delete(models ...*model.RobotdogWaypoint) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *robotdogWaypointDo) withDO(do gen.Dao) *robotdogWaypointDo {
	r.DO = *do.(*gen.DO)
	return r
}
