// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newRobotdogDog(db *gorm.DB, opts ...gen.DOOption) robotdogDog {
	_robotdogDog := robotdogDog{}

	_robotdogDog.robotdogDogDo.UseDB(db, opts...)
	_robotdogDog.robotdogDogDo.UseModel(&model.RobotdogDog{})

	tableName := _robotdogDog.robotdogDogDo.TableName()
	_robotdogDog.ALL = field.NewAsterisk(tableName)
	_robotdogDog.ID = field.NewInt64(tableName, "id")
	_robotdogDog.TenantID = field.NewInt32(tableName, "tenant_id")
	_robotdogDog.Name = field.NewString(tableName, "name")
	_robotdogDog.Sn = field.NewString(tableName, "sn")
	_robotdogDog.Model = field.NewString(tableName, "model")
	_robotdogDog.Status = field.NewString(tableName, "status")
	_robotdogDog.MaxSpeed = field.NewFloat64(tableName, "max_speed")
	_robotdogDog.Battery = field.NewInt32(tableName, "battery")
	_robotdogDog.StreamURL = field.NewString(tableName, "stream_url")
	_robotdogDog.RtspURL = field.NewString(tableName, "rtsp_url")
	_robotdogDog.MapID = field.NewInt64(tableName, "map_id")
	_robotdogDog.UdpHost = field.NewString(tableName, "udp_host")
	_robotdogDog.UdpPort = field.NewInt32(tableName, "udp_port")
	_robotdogDog.Remark = field.NewString(tableName, "remark")
	_robotdogDog.CreatedAt = field.NewTime(tableName, "created_at")
	_robotdogDog.UpdatedAt = field.NewTime(tableName, "updated_at")
	_robotdogDog.DeletedAt = field.NewField(tableName, "deleted_at")

	_robotdogDog.fillFieldMap()

	return _robotdogDog
}

// robotdogDog 机械狗
type robotdogDog struct {
	robotdogDogDo

	ALL       field.Asterisk
	ID        field.Int64   // ID
	TenantID  field.Int32   // 租户唯一标识
	Name      field.String  // 机械狗名称
	Sn        field.String  // 机械狗序列号
	Model     field.String  // 型号
	Status    field.String  // 状态:online/offline/busy
	MaxSpeed  field.Float64 // 最大速度
	Battery   field.Int32   // 电量
	StreamURL field.String  // 视频播放地址
	RtspURL   field.String  // RTSP地址
	MapID     field.Int64   // 默认地图ID
	UdpHost   field.String  // UDP主机地址
	UdpPort   field.Int32   // UDP端口
	Remark    field.String  // 备注
	CreatedAt field.Time    // 创建时间
	UpdatedAt field.Time    // 更新时间
	DeletedAt field.Field   // 删除时间

	fieldMap map[string]field.Expr
}

func (r robotdogDog) Table(newTableName string) *robotdogDog {
	r.robotdogDogDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r robotdogDog) As(alias string) *robotdogDog {
	r.robotdogDogDo.DO = *(r.robotdogDogDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *robotdogDog) updateTableName(table string) *robotdogDog {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.TenantID = field.NewInt32(table, "tenant_id")
	r.Name = field.NewString(table, "name")
	r.Sn = field.NewString(table, "sn")
	r.Model = field.NewString(table, "model")
	r.Status = field.NewString(table, "status")
	r.MaxSpeed = field.NewFloat64(table, "max_speed")
	r.Battery = field.NewInt32(table, "battery")
	r.StreamURL = field.NewString(table, "stream_url")
	r.RtspURL = field.NewString(table, "rtsp_url")
	r.MapID = field.NewInt64(table, "map_id")
	r.UdpHost = field.NewString(table, "udp_host")
	r.UdpPort = field.NewInt32(table, "udp_port")
	r.Remark = field.NewString(table, "remark")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *robotdogDog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *robotdogDog) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 17)
	r.fieldMap["id"] = r.ID
	r.fieldMap["tenant_id"] = r.TenantID
	r.fieldMap["name"] = r.Name
	r.fieldMap["sn"] = r.Sn
	r.fieldMap["model"] = r.Model
	r.fieldMap["status"] = r.Status
	r.fieldMap["max_speed"] = r.MaxSpeed
	r.fieldMap["battery"] = r.Battery
	r.fieldMap["stream_url"] = r.StreamURL
	r.fieldMap["rtsp_url"] = r.RtspURL
	r.fieldMap["map_id"] = r.MapID
	r.fieldMap["udp_host"] = r.UdpHost
	r.fieldMap["udp_port"] = r.UdpPort
	r.fieldMap["remark"] = r.Remark
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r robotdogDog) clone(db *gorm.DB) robotdogDog {
	r.robotdogDogDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r robotdogDog) replaceDB(db *gorm.DB) robotdogDog {
	r.robotdogDogDo.ReplaceDB(db)
	return r
}

type robotdogDogDo struct{ gen.DO }

type IRobotdogDogDo interface {
	gen.SubQuery
	Debug() IRobotdogDogDo
	WithContext(ctx context.Context) IRobotdogDogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRobotdogDogDo
	WriteDB() IRobotdogDogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRobotdogDogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRobotdogDogDo
	Not(conds ...gen.Condition) IRobotdogDogDo
	Or(conds ...gen.Condition) IRobotdogDogDo
	Select(conds ...field.Expr) IRobotdogDogDo
	Where(conds ...gen.Condition) IRobotdogDogDo
	Order(conds ...field.Expr) IRobotdogDogDo
	Distinct(cols ...field.Expr) IRobotdogDogDo
	Omit(cols ...field.Expr) IRobotdogDogDo
	Join(table schema.Tabler, on ...field.Expr) IRobotdogDogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogDogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogDogDo
	Group(cols ...field.Expr) IRobotdogDogDo
	Having(conds ...gen.Condition) IRobotdogDogDo
	Limit(limit int) IRobotdogDogDo
	Offset(offset int) IRobotdogDogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogDogDo
	Unscoped() IRobotdogDogDo
	Create(values ...*model.RobotdogDog) error
	CreateInBatches(values []*model.RobotdogDog, batchSize int) error
	Save(values ...*model.RobotdogDog) error
	First() (*model.RobotdogDog, error)
	Take() (*model.RobotdogDog, error)
	Last() (*model.RobotdogDog, error)
	Find() ([]*model.RobotdogDog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogDog, err error)
	FindInBatches(result *[]*model.RobotdogDog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RobotdogDog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRobotdogDogDo
	Assign(attrs ...field.AssignExpr) IRobotdogDogDo
	Joins(fields ...field.RelationField) IRobotdogDogDo
	Preload(fields ...field.RelationField) IRobotdogDogDo
	FirstOrInit() (*model.RobotdogDog, error)
	FirstOrCreate() (*model.RobotdogDog, error)
	FindByPage(offset int, limit int) (result []*model.RobotdogDog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRobotdogDogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r robotdogDogDo) Debug() IRobotdogDogDo {
	return r.withDO(r.DO.Debug())
}

func (r robotdogDogDo) WithContext(ctx context.Context) IRobotdogDogDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r robotdogDogDo) ReadDB() IRobotdogDogDo {
	return r.Clauses(dbresolver.Read)
}

func (r robotdogDogDo) WriteDB() IRobotdogDogDo {
	return r.Clauses(dbresolver.Write)
}

func (r robotdogDogDo) Session(config *gorm.Session) IRobotdogDogDo {
	return r.withDO(r.DO.Session(config))
}

func (r robotdogDogDo) Clauses(conds ...clause.Expression) IRobotdogDogDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r robotdogDogDo) Returning(value interface{}, columns ...string) IRobotdogDogDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r robotdogDogDo) Not(conds ...gen.Condition) IRobotdogDogDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r robotdogDogDo) Or(conds ...gen.Condition) IRobotdogDogDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r robotdogDogDo) Select(conds ...field.Expr) IRobotdogDogDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r robotdogDogDo) Where(conds ...gen.Condition) IRobotdogDogDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r robotdogDogDo) Order(conds ...field.Expr) IRobotdogDogDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r robotdogDogDo) Distinct(cols ...field.Expr) IRobotdogDogDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r robotdogDogDo) Omit(cols ...field.Expr) IRobotdogDogDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r robotdogDogDo) Join(table schema.Tabler, on ...field.Expr) IRobotdogDogDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r robotdogDogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogDogDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r robotdogDogDo) RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogDogDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r robotdogDogDo) Group(cols ...field.Expr) IRobotdogDogDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r robotdogDogDo) Having(conds ...gen.Condition) IRobotdogDogDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r robotdogDogDo) Limit(limit int) IRobotdogDogDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r robotdogDogDo) Offset(offset int) IRobotdogDogDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r robotdogDogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogDogDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r robotdogDogDo) Unscoped() IRobotdogDogDo {
	return r.withDO(r.DO.Unscoped())
}

func (r robotdogDogDo) Create(values ...*model.RobotdogDog) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r robotdogDogDo) CreateInBatches(values []*model.RobotdogDog, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r robotdogDogDo) Save(values ...*model.RobotdogDog) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r robotdogDogDo) First() (*model.RobotdogDog, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogDog), nil
	}
}

func (r robotdogDogDo) Take() (*model.RobotdogDog, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogDog), nil
	}
}

func (r robotdogDogDo) Last() (*model.RobotdogDog, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogDog), nil
	}
}

func (r robotdogDogDo) Find() ([]*model.RobotdogDog, error) {
	result, err := r.DO.Find()
	return result.([]*model.RobotdogDog), err
}

func (r robotdogDogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogDog, err error) {
	buf := make([]*model.RobotdogDog, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r robotdogDogDo) FindInBatches(result *[]*model.RobotdogDog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r robotdogDogDo) Attrs(attrs ...field.AssignExpr) IRobotdogDogDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r robotdogDogDo) Assign(attrs ...field.AssignExpr) IRobotdogDogDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r robotdogDogDo) Joins(fields ...field.RelationField) IRobotdogDogDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r robotdogDogDo) Preload(fields ...field.RelationField) IRobotdogDogDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r robotdogDogDo) FirstOrInit() (*model.RobotdogDog, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogDog), nil
	}
}

func (r robotdogDogDo) FirstOrCreate() (*model.RobotdogDog, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogDog), nil
	}
}

func (r robotdogDogDo) FindByPage(offset int, limit int) (result []*model.RobotdogDog, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r robotdogDogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r robotdogDogDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r robotdogDogDo) Delete(models ...*model.RobotdogDog) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *robotdogDogDo) withDO(do gen.Dao) *robotdogDogDo {
	r.DO = *do.(*gen.DO)
	return r
}
