// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newRobotdogRouteTask(db *gorm.DB, opts ...gen.DOOption) robotdogRouteTask {
	_robotdogRouteTask := robotdogRouteTask{}

	_robotdogRouteTask.robotdogRouteTaskDo.UseDB(db, opts...)
	_robotdogRouteTask.robotdogRouteTaskDo.UseModel(&model.RobotdogRouteTask{})

	tableName := _robotdogRouteTask.robotdogRouteTaskDo.TableName()
	_robotdogRouteTask.ALL = field.NewAsterisk(tableName)
	_robotdogRouteTask.ID = field.NewInt64(tableName, "id")
	_robotdogRouteTask.TenantID = field.NewInt32(tableName, "tenant_id")
	_robotdogRouteTask.RouteID = field.NewInt64(tableName, "route_id")
	_robotdogRouteTask.Seq = field.NewInt32(tableName, "seq")
	_robotdogRouteTask.Action = field.NewString(tableName, "action")
	_robotdogRouteTask.WaitSec = field.NewFloat64(tableName, "wait_sec")
	_robotdogRouteTask.Params = field.NewString(tableName, "params")
	_robotdogRouteTask.CreatedAt = field.NewTime(tableName, "created_at")
	_robotdogRouteTask.UpdatedAt = field.NewTime(tableName, "updated_at")
	_robotdogRouteTask.DeletedAt = field.NewField(tableName, "deleted_at")

	_robotdogRouteTask.fillFieldMap()

	return _robotdogRouteTask
}

// robotdogRouteTask 机械狗航线子任务
type robotdogRouteTask struct {
	robotdogRouteTaskDo

	ALL       field.Asterisk
	ID        field.Int64   // ID
	TenantID  field.Int32   // 租户唯一标识
	RouteID   field.Int64   // 航线ID
	Seq       field.Int32   // 执行序号
	Action    field.String  // 动作
	WaitSec   field.Float64 // 等待秒数
	Params    field.String  // 动作参数JSON
	CreatedAt field.Time    // 创建时间
	UpdatedAt field.Time    // 更新时间
	DeletedAt field.Field   // 删除时间

	fieldMap map[string]field.Expr
}

func (r robotdogRouteTask) Table(newTableName string) *robotdogRouteTask {
	r.robotdogRouteTaskDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r robotdogRouteTask) As(alias string) *robotdogRouteTask {
	r.robotdogRouteTaskDo.DO = *(r.robotdogRouteTaskDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *robotdogRouteTask) updateTableName(table string) *robotdogRouteTask {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.TenantID = field.NewInt32(table, "tenant_id")
	r.RouteID = field.NewInt64(table, "route_id")
	r.Seq = field.NewInt32(table, "seq")
	r.Action = field.NewString(table, "action")
	r.WaitSec = field.NewFloat64(table, "wait_sec")
	r.Params = field.NewString(table, "params")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *robotdogRouteTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *robotdogRouteTask) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 10)
	r.fieldMap["id"] = r.ID
	r.fieldMap["tenant_id"] = r.TenantID
	r.fieldMap["route_id"] = r.RouteID
	r.fieldMap["seq"] = r.Seq
	r.fieldMap["action"] = r.Action
	r.fieldMap["wait_sec"] = r.WaitSec
	r.fieldMap["params"] = r.Params
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r robotdogRouteTask) clone(db *gorm.DB) robotdogRouteTask {
	r.robotdogRouteTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r robotdogRouteTask) replaceDB(db *gorm.DB) robotdogRouteTask {
	r.robotdogRouteTaskDo.ReplaceDB(db)
	return r
}

type robotdogRouteTaskDo struct{ gen.DO }

type IRobotdogRouteTaskDo interface {
	gen.SubQuery
	Debug() IRobotdogRouteTaskDo
	WithContext(ctx context.Context) IRobotdogRouteTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRobotdogRouteTaskDo
	WriteDB() IRobotdogRouteTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRobotdogRouteTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRobotdogRouteTaskDo
	Not(conds ...gen.Condition) IRobotdogRouteTaskDo
	Or(conds ...gen.Condition) IRobotdogRouteTaskDo
	Select(conds ...field.Expr) IRobotdogRouteTaskDo
	Where(conds ...gen.Condition) IRobotdogRouteTaskDo
	Order(conds ...field.Expr) IRobotdogRouteTaskDo
	Distinct(cols ...field.Expr) IRobotdogRouteTaskDo
	Omit(cols ...field.Expr) IRobotdogRouteTaskDo
	Join(table schema.Tabler, on ...field.Expr) IRobotdogRouteTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteTaskDo
	Group(cols ...field.Expr) IRobotdogRouteTaskDo
	Having(conds ...gen.Condition) IRobotdogRouteTaskDo
	Limit(limit int) IRobotdogRouteTaskDo
	Offset(offset int) IRobotdogRouteTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogRouteTaskDo
	Unscoped() IRobotdogRouteTaskDo
	Create(values ...*model.RobotdogRouteTask) error
	CreateInBatches(values []*model.RobotdogRouteTask, batchSize int) error
	Save(values ...*model.RobotdogRouteTask) error
	First() (*model.RobotdogRouteTask, error)
	Take() (*model.RobotdogRouteTask, error)
	Last() (*model.RobotdogRouteTask, error)
	Find() ([]*model.RobotdogRouteTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogRouteTask, err error)
	FindInBatches(result *[]*model.RobotdogRouteTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RobotdogRouteTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRobotdogRouteTaskDo
	Assign(attrs ...field.AssignExpr) IRobotdogRouteTaskDo
	Joins(fields ...field.RelationField) IRobotdogRouteTaskDo
	Preload(fields ...field.RelationField) IRobotdogRouteTaskDo
	FirstOrInit() (*model.RobotdogRouteTask, error)
	FirstOrCreate() (*model.RobotdogRouteTask, error)
	FindByPage(offset int, limit int) (result []*model.RobotdogRouteTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRobotdogRouteTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r robotdogRouteTaskDo) Debug() IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Debug())
}

func (r robotdogRouteTaskDo) WithContext(ctx context.Context) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r robotdogRouteTaskDo) ReadDB() IRobotdogRouteTaskDo {
	return r.Clauses(dbresolver.Read)
}

func (r robotdogRouteTaskDo) WriteDB() IRobotdogRouteTaskDo {
	return r.Clauses(dbresolver.Write)
}

func (r robotdogRouteTaskDo) Session(config *gorm.Session) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Session(config))
}

func (r robotdogRouteTaskDo) Clauses(conds ...clause.Expression) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r robotdogRouteTaskDo) Returning(value interface{}, columns ...string) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r robotdogRouteTaskDo) Not(conds ...gen.Condition) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r robotdogRouteTaskDo) Or(conds ...gen.Condition) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r robotdogRouteTaskDo) Select(conds ...field.Expr) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r robotdogRouteTaskDo) Where(conds ...gen.Condition) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r robotdogRouteTaskDo) Order(conds ...field.Expr) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r robotdogRouteTaskDo) Distinct(cols ...field.Expr) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r robotdogRouteTaskDo) Omit(cols ...field.Expr) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r robotdogRouteTaskDo) Join(table schema.Tabler, on ...field.Expr) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r robotdogRouteTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r robotdogRouteTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r robotdogRouteTaskDo) Group(cols ...field.Expr) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r robotdogRouteTaskDo) Having(conds ...gen.Condition) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r robotdogRouteTaskDo) Limit(limit int) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r robotdogRouteTaskDo) Offset(offset int) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r robotdogRouteTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r robotdogRouteTaskDo) Unscoped() IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Unscoped())
}

func (r robotdogRouteTaskDo) Create(values ...*model.RobotdogRouteTask) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r robotdogRouteTaskDo) CreateInBatches(values []*model.RobotdogRouteTask, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r robotdogRouteTaskDo) Save(values ...*model.RobotdogRouteTask) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r robotdogRouteTaskDo) First() (*model.RobotdogRouteTask, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteTask), nil
	}
}

func (r robotdogRouteTaskDo) Take() (*model.RobotdogRouteTask, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteTask), nil
	}
}

func (r robotdogRouteTaskDo) Last() (*model.RobotdogRouteTask, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteTask), nil
	}
}

func (r robotdogRouteTaskDo) Find() ([]*model.RobotdogRouteTask, error) {
	result, err := r.DO.Find()
	return result.([]*model.RobotdogRouteTask), err
}

func (r robotdogRouteTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogRouteTask, err error) {
	buf := make([]*model.RobotdogRouteTask, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r robotdogRouteTaskDo) FindInBatches(result *[]*model.RobotdogRouteTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r robotdogRouteTaskDo) Attrs(attrs ...field.AssignExpr) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r robotdogRouteTaskDo) Assign(attrs ...field.AssignExpr) IRobotdogRouteTaskDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r robotdogRouteTaskDo) Joins(fields ...field.RelationField) IRobotdogRouteTaskDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r robotdogRouteTaskDo) Preload(fields ...field.RelationField) IRobotdogRouteTaskDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r robotdogRouteTaskDo) FirstOrInit() (*model.RobotdogRouteTask, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteTask), nil
	}
}

func (r robotdogRouteTaskDo) FirstOrCreate() (*model.RobotdogRouteTask, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteTask), nil
	}
}

func (r robotdogRouteTaskDo) FindByPage(offset int, limit int) (result []*model.RobotdogRouteTask, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r robotdogRouteTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r robotdogRouteTaskDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r robotdogRouteTaskDo) Delete(models ...*model.RobotdogRouteTask) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *robotdogRouteTaskDo) withDO(do gen.Dao) *robotdogRouteTaskDo {
	r.DO = *do.(*gen.DO)
	return r
}
