// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newRobotdogPtz(db *gorm.DB, opts ...gen.DOOption) robotdogPtz {
	_robotdogPtz := robotdogPtz{}

	_robotdogPtz.robotdogPtzDo.UseDB(db, opts...)
	_robotdogPtz.robotdogPtzDo.UseModel(&model.RobotdogPtz{})

	tableName := _robotdogPtz.robotdogPtzDo.TableName()
	_robotdogPtz.ALL = field.NewAsterisk(tableName)
	_robotdogPtz.ID = field.NewInt64(tableName, "id")
	_robotdogPtz.TenantID = field.NewInt32(tableName, "tenant_id")
	_robotdogPtz.Name = field.NewString(tableName, "name")
	_robotdogPtz.Brand = field.NewString(tableName, "brand")
	_robotdogPtz.Model = field.NewString(tableName, "model")
	_robotdogPtz.Protocol = field.NewString(tableName, "protocol")
	_robotdogPtz.UdpHost = field.NewString(tableName, "udp_host")
	_robotdogPtz.UdpPort = field.NewInt32(tableName, "udp_port")
	_robotdogPtz.Status = field.NewString(tableName, "status")
	_robotdogPtz.Remark = field.NewString(tableName, "remark")
	_robotdogPtz.CreatedAt = field.NewTime(tableName, "created_at")
	_robotdogPtz.UpdatedAt = field.NewTime(tableName, "updated_at")
	_robotdogPtz.DeletedAt = field.NewField(tableName, "deleted_at")

	_robotdogPtz.fillFieldMap()

	return _robotdogPtz
}

// robotdogPtz 机械狗云台
type robotdogPtz struct {
	robotdogPtzDo

	ALL       field.Asterisk
	ID        field.Int64  // ID
	TenantID  field.Int32  // 租户唯一标识
	Name      field.String // 云台名称
	Brand     field.String // 品牌
	Model     field.String // 型号
	Protocol  field.String // 协议
	UdpHost   field.String // UDP主机地址
	UdpPort   field.Int32  // UDP端口
	Status    field.String // 状态:online/offline
	Remark    field.String // 备注
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (r robotdogPtz) Table(newTableName string) *robotdogPtz {
	r.robotdogPtzDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r robotdogPtz) As(alias string) *robotdogPtz {
	r.robotdogPtzDo.DO = *(r.robotdogPtzDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *robotdogPtz) updateTableName(table string) *robotdogPtz {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.TenantID = field.NewInt32(table, "tenant_id")
	r.Name = field.NewString(table, "name")
	r.Brand = field.NewString(table, "brand")
	r.Model = field.NewString(table, "model")
	r.Protocol = field.NewString(table, "protocol")
	r.UdpHost = field.NewString(table, "udp_host")
	r.UdpPort = field.NewInt32(table, "udp_port")
	r.Status = field.NewString(table, "status")
	r.Remark = field.NewString(table, "remark")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *robotdogPtz) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *robotdogPtz) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 13)
	r.fieldMap["id"] = r.ID
	r.fieldMap["tenant_id"] = r.TenantID
	r.fieldMap["name"] = r.Name
	r.fieldMap["brand"] = r.Brand
	r.fieldMap["model"] = r.Model
	r.fieldMap["protocol"] = r.Protocol
	r.fieldMap["udp_host"] = r.UdpHost
	r.fieldMap["udp_port"] = r.UdpPort
	r.fieldMap["status"] = r.Status
	r.fieldMap["remark"] = r.Remark
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r robotdogPtz) clone(db *gorm.DB) robotdogPtz {
	r.robotdogPtzDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r robotdogPtz) replaceDB(db *gorm.DB) robotdogPtz {
	r.robotdogPtzDo.ReplaceDB(db)
	return r
}

type robotdogPtzDo struct{ gen.DO }

type IRobotdogPtzDo interface {
	gen.SubQuery
	Debug() IRobotdogPtzDo
	WithContext(ctx context.Context) IRobotdogPtzDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRobotdogPtzDo
	WriteDB() IRobotdogPtzDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRobotdogPtzDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRobotdogPtzDo
	Not(conds ...gen.Condition) IRobotdogPtzDo
	Or(conds ...gen.Condition) IRobotdogPtzDo
	Select(conds ...field.Expr) IRobotdogPtzDo
	Where(conds ...gen.Condition) IRobotdogPtzDo
	Order(conds ...field.Expr) IRobotdogPtzDo
	Distinct(cols ...field.Expr) IRobotdogPtzDo
	Omit(cols ...field.Expr) IRobotdogPtzDo
	Join(table schema.Tabler, on ...field.Expr) IRobotdogPtzDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogPtzDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogPtzDo
	Group(cols ...field.Expr) IRobotdogPtzDo
	Having(conds ...gen.Condition) IRobotdogPtzDo
	Limit(limit int) IRobotdogPtzDo
	Offset(offset int) IRobotdogPtzDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogPtzDo
	Unscoped() IRobotdogPtzDo
	Create(values ...*model.RobotdogPtz) error
	CreateInBatches(values []*model.RobotdogPtz, batchSize int) error
	Save(values ...*model.RobotdogPtz) error
	First() (*model.RobotdogPtz, error)
	Take() (*model.RobotdogPtz, error)
	Last() (*model.RobotdogPtz, error)
	Find() ([]*model.RobotdogPtz, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogPtz, err error)
	FindInBatches(result *[]*model.RobotdogPtz, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RobotdogPtz) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRobotdogPtzDo
	Assign(attrs ...field.AssignExpr) IRobotdogPtzDo
	Joins(fields ...field.RelationField) IRobotdogPtzDo
	Preload(fields ...field.RelationField) IRobotdogPtzDo
	FirstOrInit() (*model.RobotdogPtz, error)
	FirstOrCreate() (*model.RobotdogPtz, error)
	FindByPage(offset int, limit int) (result []*model.RobotdogPtz, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRobotdogPtzDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r robotdogPtzDo) Debug() IRobotdogPtzDo {
	return r.withDO(r.DO.Debug())
}

func (r robotdogPtzDo) WithContext(ctx context.Context) IRobotdogPtzDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r robotdogPtzDo) ReadDB() IRobotdogPtzDo {
	return r.Clauses(dbresolver.Read)
}

func (r robotdogPtzDo) WriteDB() IRobotdogPtzDo {
	return r.Clauses(dbresolver.Write)
}

func (r robotdogPtzDo) Session(config *gorm.Session) IRobotdogPtzDo {
	return r.withDO(r.DO.Session(config))
}

func (r robotdogPtzDo) Clauses(conds ...clause.Expression) IRobotdogPtzDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r robotdogPtzDo) Returning(value interface{}, columns ...string) IRobotdogPtzDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r robotdogPtzDo) Not(conds ...gen.Condition) IRobotdogPtzDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r robotdogPtzDo) Or(conds ...gen.Condition) IRobotdogPtzDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r robotdogPtzDo) Select(conds ...field.Expr) IRobotdogPtzDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r robotdogPtzDo) Where(conds ...gen.Condition) IRobotdogPtzDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r robotdogPtzDo) Order(conds ...field.Expr) IRobotdogPtzDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r robotdogPtzDo) Distinct(cols ...field.Expr) IRobotdogPtzDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r robotdogPtzDo) Omit(cols ...field.Expr) IRobotdogPtzDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r robotdogPtzDo) Join(table schema.Tabler, on ...field.Expr) IRobotdogPtzDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r robotdogPtzDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogPtzDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r robotdogPtzDo) RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogPtzDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r robotdogPtzDo) Group(cols ...field.Expr) IRobotdogPtzDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r robotdogPtzDo) Having(conds ...gen.Condition) IRobotdogPtzDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r robotdogPtzDo) Limit(limit int) IRobotdogPtzDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r robotdogPtzDo) Offset(offset int) IRobotdogPtzDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r robotdogPtzDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogPtzDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r robotdogPtzDo) Unscoped() IRobotdogPtzDo {
	return r.withDO(r.DO.Unscoped())
}

func (r robotdogPtzDo) Create(values ...*model.RobotdogPtz) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r robotdogPtzDo) CreateInBatches(values []*model.RobotdogPtz, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r robotdogPtzDo) Save(values ...*model.RobotdogPtz) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r robotdogPtzDo) First() (*model.RobotdogPtz, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogPtz), nil
	}
}

func (r robotdogPtzDo) Take() (*model.RobotdogPtz, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogPtz), nil
	}
}

func (r robotdogPtzDo) Last() (*model.RobotdogPtz, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogPtz), nil
	}
}

func (r robotdogPtzDo) Find() ([]*model.RobotdogPtz, error) {
	result, err := r.DO.Find()
	return result.([]*model.RobotdogPtz), err
}

func (r robotdogPtzDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogPtz, err error) {
	buf := make([]*model.RobotdogPtz, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r robotdogPtzDo) FindInBatches(result *[]*model.RobotdogPtz, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r robotdogPtzDo) Attrs(attrs ...field.AssignExpr) IRobotdogPtzDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r robotdogPtzDo) Assign(attrs ...field.AssignExpr) IRobotdogPtzDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r robotdogPtzDo) Joins(fields ...field.RelationField) IRobotdogPtzDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r robotdogPtzDo) Preload(fields ...field.RelationField) IRobotdogPtzDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r robotdogPtzDo) FirstOrInit() (*model.RobotdogPtz, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogPtz), nil
	}
}

func (r robotdogPtzDo) FirstOrCreate() (*model.RobotdogPtz, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogPtz), nil
	}
}

func (r robotdogPtzDo) FindByPage(offset int, limit int) (result []*model.RobotdogPtz, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r robotdogPtzDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r robotdogPtzDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r robotdogPtzDo) Delete(models ...*model.RobotdogPtz) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *robotdogPtzDo) withDO(do gen.Dao) *robotdogPtzDo {
	r.DO = *do.(*gen.DO)
	return r
}
