// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newRobotdogMap(db *gorm.DB, opts ...gen.DOOption) robotdogMap {
	_robotdogMap := robotdogMap{}

	_robotdogMap.robotdogMapDo.UseDB(db, opts...)
	_robotdogMap.robotdogMapDo.UseModel(&model.RobotdogMap{})

	tableName := _robotdogMap.robotdogMapDo.TableName()
	_robotdogMap.ALL = field.NewAsterisk(tableName)
	_robotdogMap.ID = field.NewInt64(tableName, "id")
	_robotdogMap.TenantID = field.NewInt32(tableName, "tenant_id")
	_robotdogMap.Name = field.NewString(tableName, "name")
	_robotdogMap.Format = field.NewString(tableName, "format")
	_robotdogMap.URL = field.NewString(tableName, "url")
	_robotdogMap.PreviewURL = field.NewString(tableName, "preview_url")
	_robotdogMap.OriginX = field.NewFloat64(tableName, "origin_x")
	_robotdogMap.OriginY = field.NewFloat64(tableName, "origin_y")
	_robotdogMap.OriginZ = field.NewFloat64(tableName, "origin_z")
	_robotdogMap.Scale = field.NewFloat64(tableName, "scale")
	_robotdogMap.CreatedAt = field.NewTime(tableName, "created_at")
	_robotdogMap.UpdatedAt = field.NewTime(tableName, "updated_at")
	_robotdogMap.DeletedAt = field.NewField(tableName, "deleted_at")

	_robotdogMap.fillFieldMap()

	return _robotdogMap
}

// robotdogMap 机械狗点云地图
type robotdogMap struct {
	robotdogMapDo

	ALL        field.Asterisk
	ID         field.Int64   // ID
	TenantID   field.Int32   // 租户唯一标识
	Name       field.String  // 地图名称
	Format     field.String  // 格式
	URL        field.String  // 资源地址
	PreviewURL field.String  // 预览地址
	OriginX    field.Float64 // 原点X
	OriginY    field.Float64 // 原点Y
	OriginZ    field.Float64 // 原点Z
	Scale      field.Float64 // 比例
	CreatedAt  field.Time    // 创建时间
	UpdatedAt  field.Time    // 更新时间
	DeletedAt  field.Field   // 删除时间

	fieldMap map[string]field.Expr
}

func (r robotdogMap) Table(newTableName string) *robotdogMap {
	r.robotdogMapDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r robotdogMap) As(alias string) *robotdogMap {
	r.robotdogMapDo.DO = *(r.robotdogMapDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *robotdogMap) updateTableName(table string) *robotdogMap {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.TenantID = field.NewInt32(table, "tenant_id")
	r.Name = field.NewString(table, "name")
	r.Format = field.NewString(table, "format")
	r.URL = field.NewString(table, "url")
	r.PreviewURL = field.NewString(table, "preview_url")
	r.OriginX = field.NewFloat64(table, "origin_x")
	r.OriginY = field.NewFloat64(table, "origin_y")
	r.OriginZ = field.NewFloat64(table, "origin_z")
	r.Scale = field.NewFloat64(table, "scale")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *robotdogMap) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *robotdogMap) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 13)
	r.fieldMap["id"] = r.ID
	r.fieldMap["tenant_id"] = r.TenantID
	r.fieldMap["name"] = r.Name
	r.fieldMap["format"] = r.Format
	r.fieldMap["url"] = r.URL
	r.fieldMap["preview_url"] = r.PreviewURL
	r.fieldMap["origin_x"] = r.OriginX
	r.fieldMap["origin_y"] = r.OriginY
	r.fieldMap["origin_z"] = r.OriginZ
	r.fieldMap["scale"] = r.Scale
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r robotdogMap) clone(db *gorm.DB) robotdogMap {
	r.robotdogMapDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r robotdogMap) replaceDB(db *gorm.DB) robotdogMap {
	r.robotdogMapDo.ReplaceDB(db)
	return r
}

type robotdogMapDo struct{ gen.DO }

type IRobotdogMapDo interface {
	gen.SubQuery
	Debug() IRobotdogMapDo
	WithContext(ctx context.Context) IRobotdogMapDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRobotdogMapDo
	WriteDB() IRobotdogMapDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRobotdogMapDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRobotdogMapDo
	Not(conds ...gen.Condition) IRobotdogMapDo
	Or(conds ...gen.Condition) IRobotdogMapDo
	Select(conds ...field.Expr) IRobotdogMapDo
	Where(conds ...gen.Condition) IRobotdogMapDo
	Order(conds ...field.Expr) IRobotdogMapDo
	Distinct(cols ...field.Expr) IRobotdogMapDo
	Omit(cols ...field.Expr) IRobotdogMapDo
	Join(table schema.Tabler, on ...field.Expr) IRobotdogMapDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogMapDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogMapDo
	Group(cols ...field.Expr) IRobotdogMapDo
	Having(conds ...gen.Condition) IRobotdogMapDo
	Limit(limit int) IRobotdogMapDo
	Offset(offset int) IRobotdogMapDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogMapDo
	Unscoped() IRobotdogMapDo
	Create(values ...*model.RobotdogMap) error
	CreateInBatches(values []*model.RobotdogMap, batchSize int) error
	Save(values ...*model.RobotdogMap) error
	First() (*model.RobotdogMap, error)
	Take() (*model.RobotdogMap, error)
	Last() (*model.RobotdogMap, error)
	Find() ([]*model.RobotdogMap, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogMap, err error)
	FindInBatches(result *[]*model.RobotdogMap, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RobotdogMap) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRobotdogMapDo
	Assign(attrs ...field.AssignExpr) IRobotdogMapDo
	Joins(fields ...field.RelationField) IRobotdogMapDo
	Preload(fields ...field.RelationField) IRobotdogMapDo
	FirstOrInit() (*model.RobotdogMap, error)
	FirstOrCreate() (*model.RobotdogMap, error)
	FindByPage(offset int, limit int) (result []*model.RobotdogMap, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRobotdogMapDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r robotdogMapDo) Debug() IRobotdogMapDo {
	return r.withDO(r.DO.Debug())
}

func (r robotdogMapDo) WithContext(ctx context.Context) IRobotdogMapDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r robotdogMapDo) ReadDB() IRobotdogMapDo {
	return r.Clauses(dbresolver.Read)
}

func (r robotdogMapDo) WriteDB() IRobotdogMapDo {
	return r.Clauses(dbresolver.Write)
}

func (r robotdogMapDo) Session(config *gorm.Session) IRobotdogMapDo {
	return r.withDO(r.DO.Session(config))
}

func (r robotdogMapDo) Clauses(conds ...clause.Expression) IRobotdogMapDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r robotdogMapDo) Returning(value interface{}, columns ...string) IRobotdogMapDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r robotdogMapDo) Not(conds ...gen.Condition) IRobotdogMapDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r robotdogMapDo) Or(conds ...gen.Condition) IRobotdogMapDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r robotdogMapDo) Select(conds ...field.Expr) IRobotdogMapDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r robotdogMapDo) Where(conds ...gen.Condition) IRobotdogMapDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r robotdogMapDo) Order(conds ...field.Expr) IRobotdogMapDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r robotdogMapDo) Distinct(cols ...field.Expr) IRobotdogMapDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r robotdogMapDo) Omit(cols ...field.Expr) IRobotdogMapDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r robotdogMapDo) Join(table schema.Tabler, on ...field.Expr) IRobotdogMapDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r robotdogMapDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogMapDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r robotdogMapDo) RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogMapDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r robotdogMapDo) Group(cols ...field.Expr) IRobotdogMapDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r robotdogMapDo) Having(conds ...gen.Condition) IRobotdogMapDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r robotdogMapDo) Limit(limit int) IRobotdogMapDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r robotdogMapDo) Offset(offset int) IRobotdogMapDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r robotdogMapDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogMapDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r robotdogMapDo) Unscoped() IRobotdogMapDo {
	return r.withDO(r.DO.Unscoped())
}

func (r robotdogMapDo) Create(values ...*model.RobotdogMap) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r robotdogMapDo) CreateInBatches(values []*model.RobotdogMap, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r robotdogMapDo) Save(values ...*model.RobotdogMap) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r robotdogMapDo) First() (*model.RobotdogMap, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogMap), nil
	}
}

func (r robotdogMapDo) Take() (*model.RobotdogMap, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogMap), nil
	}
}

func (r robotdogMapDo) Last() (*model.RobotdogMap, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogMap), nil
	}
}

func (r robotdogMapDo) Find() ([]*model.RobotdogMap, error) {
	result, err := r.DO.Find()
	return result.([]*model.RobotdogMap), err
}

func (r robotdogMapDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogMap, err error) {
	buf := make([]*model.RobotdogMap, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r robotdogMapDo) FindInBatches(result *[]*model.RobotdogMap, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r robotdogMapDo) Attrs(attrs ...field.AssignExpr) IRobotdogMapDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r robotdogMapDo) Assign(attrs ...field.AssignExpr) IRobotdogMapDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r robotdogMapDo) Joins(fields ...field.RelationField) IRobotdogMapDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r robotdogMapDo) Preload(fields ...field.RelationField) IRobotdogMapDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r robotdogMapDo) FirstOrInit() (*model.RobotdogMap, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogMap), nil
	}
}

func (r robotdogMapDo) FirstOrCreate() (*model.RobotdogMap, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogMap), nil
	}
}

func (r robotdogMapDo) FindByPage(offset int, limit int) (result []*model.RobotdogMap, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r robotdogMapDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r robotdogMapDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r robotdogMapDo) Delete(models ...*model.RobotdogMap) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *robotdogMapDo) withDO(do gen.Dao) *robotdogMapDo {
	r.DO = *do.(*gen.DO)
	return r
}
