// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newRobotdogRouteWaypoint(db *gorm.DB, opts ...gen.DOOption) robotdogRouteWaypoint {
	_robotdogRouteWaypoint := robotdogRouteWaypoint{}

	_robotdogRouteWaypoint.robotdogRouteWaypointDo.UseDB(db, opts...)
	_robotdogRouteWaypoint.robotdogRouteWaypointDo.UseModel(&model.RobotdogRouteWaypoint{})

	tableName := _robotdogRouteWaypoint.robotdogRouteWaypointDo.TableName()
	_robotdogRouteWaypoint.ALL = field.NewAsterisk(tableName)
	_robotdogRouteWaypoint.ID = field.NewInt64(tableName, "id")
	_robotdogRouteWaypoint.TenantID = field.NewInt32(tableName, "tenant_id")
	_robotdogRouteWaypoint.RouteID = field.NewInt64(tableName, "route_id")
	_robotdogRouteWaypoint.WaypointID = field.NewInt64(tableName, "waypoint_id")
	_robotdogRouteWaypoint.Weigh = field.NewInt32(tableName, "weigh")
	_robotdogRouteWaypoint.CreatedAt = field.NewTime(tableName, "created_at")
	_robotdogRouteWaypoint.UpdatedAt = field.NewTime(tableName, "updated_at")
	_robotdogRouteWaypoint.DeletedAt = field.NewField(tableName, "deleted_at")

	_robotdogRouteWaypoint.fillFieldMap()

	return _robotdogRouteWaypoint
}

// robotdogRouteWaypoint 机械狗航线航点关系
type robotdogRouteWaypoint struct {
	robotdogRouteWaypointDo

	ALL        field.Asterisk
	ID         field.Int64 // ID
	TenantID   field.Int32 // 租户唯一标识
	RouteID    field.Int64 // 航线ID
	WaypointID field.Int64 // 航点ID
	Weigh      field.Int32 // 排序
	CreatedAt  field.Time  // 创建时间
	UpdatedAt  field.Time  // 更新时间
	DeletedAt  field.Field // 删除时间

	fieldMap map[string]field.Expr
}

func (r robotdogRouteWaypoint) Table(newTableName string) *robotdogRouteWaypoint {
	r.robotdogRouteWaypointDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r robotdogRouteWaypoint) As(alias string) *robotdogRouteWaypoint {
	r.robotdogRouteWaypointDo.DO = *(r.robotdogRouteWaypointDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *robotdogRouteWaypoint) updateTableName(table string) *robotdogRouteWaypoint {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.TenantID = field.NewInt32(table, "tenant_id")
	r.RouteID = field.NewInt64(table, "route_id")
	r.WaypointID = field.NewInt64(table, "waypoint_id")
	r.Weigh = field.NewInt32(table, "weigh")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *robotdogRouteWaypoint) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *robotdogRouteWaypoint) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 8)
	r.fieldMap["id"] = r.ID
	r.fieldMap["tenant_id"] = r.TenantID
	r.fieldMap["route_id"] = r.RouteID
	r.fieldMap["waypoint_id"] = r.WaypointID
	r.fieldMap["weigh"] = r.Weigh
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r robotdogRouteWaypoint) clone(db *gorm.DB) robotdogRouteWaypoint {
	r.robotdogRouteWaypointDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r robotdogRouteWaypoint) replaceDB(db *gorm.DB) robotdogRouteWaypoint {
	r.robotdogRouteWaypointDo.ReplaceDB(db)
	return r
}

type robotdogRouteWaypointDo struct{ gen.DO }

type IRobotdogRouteWaypointDo interface {
	gen.SubQuery
	Debug() IRobotdogRouteWaypointDo
	WithContext(ctx context.Context) IRobotdogRouteWaypointDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRobotdogRouteWaypointDo
	WriteDB() IRobotdogRouteWaypointDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRobotdogRouteWaypointDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRobotdogRouteWaypointDo
	Not(conds ...gen.Condition) IRobotdogRouteWaypointDo
	Or(conds ...gen.Condition) IRobotdogRouteWaypointDo
	Select(conds ...field.Expr) IRobotdogRouteWaypointDo
	Where(conds ...gen.Condition) IRobotdogRouteWaypointDo
	Order(conds ...field.Expr) IRobotdogRouteWaypointDo
	Distinct(cols ...field.Expr) IRobotdogRouteWaypointDo
	Omit(cols ...field.Expr) IRobotdogRouteWaypointDo
	Join(table schema.Tabler, on ...field.Expr) IRobotdogRouteWaypointDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteWaypointDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteWaypointDo
	Group(cols ...field.Expr) IRobotdogRouteWaypointDo
	Having(conds ...gen.Condition) IRobotdogRouteWaypointDo
	Limit(limit int) IRobotdogRouteWaypointDo
	Offset(offset int) IRobotdogRouteWaypointDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogRouteWaypointDo
	Unscoped() IRobotdogRouteWaypointDo
	Create(values ...*model.RobotdogRouteWaypoint) error
	CreateInBatches(values []*model.RobotdogRouteWaypoint, batchSize int) error
	Save(values ...*model.RobotdogRouteWaypoint) error
	First() (*model.RobotdogRouteWaypoint, error)
	Take() (*model.RobotdogRouteWaypoint, error)
	Last() (*model.RobotdogRouteWaypoint, error)
	Find() ([]*model.RobotdogRouteWaypoint, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogRouteWaypoint, err error)
	FindInBatches(result *[]*model.RobotdogRouteWaypoint, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RobotdogRouteWaypoint) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRobotdogRouteWaypointDo
	Assign(attrs ...field.AssignExpr) IRobotdogRouteWaypointDo
	Joins(fields ...field.RelationField) IRobotdogRouteWaypointDo
	Preload(fields ...field.RelationField) IRobotdogRouteWaypointDo
	FirstOrInit() (*model.RobotdogRouteWaypoint, error)
	FirstOrCreate() (*model.RobotdogRouteWaypoint, error)
	FindByPage(offset int, limit int) (result []*model.RobotdogRouteWaypoint, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRobotdogRouteWaypointDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r robotdogRouteWaypointDo) Debug() IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Debug())
}

func (r robotdogRouteWaypointDo) WithContext(ctx context.Context) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r robotdogRouteWaypointDo) ReadDB() IRobotdogRouteWaypointDo {
	return r.Clauses(dbresolver.Read)
}

func (r robotdogRouteWaypointDo) WriteDB() IRobotdogRouteWaypointDo {
	return r.Clauses(dbresolver.Write)
}

func (r robotdogRouteWaypointDo) Session(config *gorm.Session) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Session(config))
}

func (r robotdogRouteWaypointDo) Clauses(conds ...clause.Expression) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r robotdogRouteWaypointDo) Returning(value interface{}, columns ...string) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r robotdogRouteWaypointDo) Not(conds ...gen.Condition) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r robotdogRouteWaypointDo) Or(conds ...gen.Condition) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r robotdogRouteWaypointDo) Select(conds ...field.Expr) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r robotdogRouteWaypointDo) Where(conds ...gen.Condition) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r robotdogRouteWaypointDo) Order(conds ...field.Expr) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r robotdogRouteWaypointDo) Distinct(cols ...field.Expr) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r robotdogRouteWaypointDo) Omit(cols ...field.Expr) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r robotdogRouteWaypointDo) Join(table schema.Tabler, on ...field.Expr) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r robotdogRouteWaypointDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r robotdogRouteWaypointDo) RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r robotdogRouteWaypointDo) Group(cols ...field.Expr) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r robotdogRouteWaypointDo) Having(conds ...gen.Condition) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r robotdogRouteWaypointDo) Limit(limit int) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r robotdogRouteWaypointDo) Offset(offset int) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r robotdogRouteWaypointDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r robotdogRouteWaypointDo) Unscoped() IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Unscoped())
}

func (r robotdogRouteWaypointDo) Create(values ...*model.RobotdogRouteWaypoint) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r robotdogRouteWaypointDo) CreateInBatches(values []*model.RobotdogRouteWaypoint, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r robotdogRouteWaypointDo) Save(values ...*model.RobotdogRouteWaypoint) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r robotdogRouteWaypointDo) First() (*model.RobotdogRouteWaypoint, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteWaypoint), nil
	}
}

func (r robotdogRouteWaypointDo) Take() (*model.RobotdogRouteWaypoint, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteWaypoint), nil
	}
}

func (r robotdogRouteWaypointDo) Last() (*model.RobotdogRouteWaypoint, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteWaypoint), nil
	}
}

func (r robotdogRouteWaypointDo) Find() ([]*model.RobotdogRouteWaypoint, error) {
	result, err := r.DO.Find()
	return result.([]*model.RobotdogRouteWaypoint), err
}

func (r robotdogRouteWaypointDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogRouteWaypoint, err error) {
	buf := make([]*model.RobotdogRouteWaypoint, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r robotdogRouteWaypointDo) FindInBatches(result *[]*model.RobotdogRouteWaypoint, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r robotdogRouteWaypointDo) Attrs(attrs ...field.AssignExpr) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r robotdogRouteWaypointDo) Assign(attrs ...field.AssignExpr) IRobotdogRouteWaypointDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r robotdogRouteWaypointDo) Joins(fields ...field.RelationField) IRobotdogRouteWaypointDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r robotdogRouteWaypointDo) Preload(fields ...field.RelationField) IRobotdogRouteWaypointDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r robotdogRouteWaypointDo) FirstOrInit() (*model.RobotdogRouteWaypoint, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteWaypoint), nil
	}
}

func (r robotdogRouteWaypointDo) FirstOrCreate() (*model.RobotdogRouteWaypoint, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteWaypoint), nil
	}
}

func (r robotdogRouteWaypointDo) FindByPage(offset int, limit int) (result []*model.RobotdogRouteWaypoint, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r robotdogRouteWaypointDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r robotdogRouteWaypointDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r robotdogRouteWaypointDo) Delete(models ...*model.RobotdogRouteWaypoint) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *robotdogRouteWaypointDo) withDO(do gen.Dao) *robotdogRouteWaypointDo {
	r.DO = *do.(*gen.DO)
	return r
}
