// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newRobotdogRouteEdge(db *gorm.DB, opts ...gen.DOOption) robotdogRouteEdge {
	_robotdogRouteEdge := robotdogRouteEdge{}

	_robotdogRouteEdge.robotdogRouteEdgeDo.UseDB(db, opts...)
	_robotdogRouteEdge.robotdogRouteEdgeDo.UseModel(&model.RobotdogRouteEdge{})

	tableName := _robotdogRouteEdge.robotdogRouteEdgeDo.TableName()
	_robotdogRouteEdge.ALL = field.NewAsterisk(tableName)
	_robotdogRouteEdge.ID = field.NewInt64(tableName, "id")
	_robotdogRouteEdge.TenantID = field.NewInt32(tableName, "tenant_id")
	_robotdogRouteEdge.RouteID = field.NewInt64(tableName, "route_id")
	_robotdogRouteEdge.FromWaypointID = field.NewInt64(tableName, "from_waypoint_id")
	_robotdogRouteEdge.ToWaypointID = field.NewInt64(tableName, "to_waypoint_id")
	_robotdogRouteEdge.FromTaskSeq = field.NewInt32(tableName, "from_task_seq")
	_robotdogRouteEdge.ToTaskSeq = field.NewInt32(tableName, "to_task_seq")
	_robotdogRouteEdge.EdgeSeq = field.NewInt32(tableName, "edge_seq")
	_robotdogRouteEdge.CreatedAt = field.NewTime(tableName, "created_at")
	_robotdogRouteEdge.UpdatedAt = field.NewTime(tableName, "updated_at")
	_robotdogRouteEdge.DeletedAt = field.NewField(tableName, "deleted_at")

	_robotdogRouteEdge.fillFieldMap()

	return _robotdogRouteEdge
}

// robotdogRouteEdge 机械狗航线边
type robotdogRouteEdge struct {
	robotdogRouteEdgeDo

	ALL            field.Asterisk
	ID             field.Int64 // ID
	TenantID       field.Int32 // 租户唯一标识
	RouteID        field.Int64 // 航线ID
	FromWaypointID field.Int64 // 起点航点ID
	ToWaypointID   field.Int64 // 终点航点ID
	FromTaskSeq    field.Int32 // 起点任务序号
	ToTaskSeq      field.Int32 // 终点任务序号
	EdgeSeq        field.Int32 // 边排序
	CreatedAt      field.Time  // 创建时间
	UpdatedAt      field.Time  // 更新时间
	DeletedAt      field.Field // 删除时间

	fieldMap map[string]field.Expr
}

func (r robotdogRouteEdge) Table(newTableName string) *robotdogRouteEdge {
	r.robotdogRouteEdgeDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r robotdogRouteEdge) As(alias string) *robotdogRouteEdge {
	r.robotdogRouteEdgeDo.DO = *(r.robotdogRouteEdgeDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *robotdogRouteEdge) updateTableName(table string) *robotdogRouteEdge {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.TenantID = field.NewInt32(table, "tenant_id")
	r.RouteID = field.NewInt64(table, "route_id")
	r.FromWaypointID = field.NewInt64(table, "from_waypoint_id")
	r.ToWaypointID = field.NewInt64(table, "to_waypoint_id")
	r.FromTaskSeq = field.NewInt32(table, "from_task_seq")
	r.ToTaskSeq = field.NewInt32(table, "to_task_seq")
	r.EdgeSeq = field.NewInt32(table, "edge_seq")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *robotdogRouteEdge) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *robotdogRouteEdge) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 11)
	r.fieldMap["id"] = r.ID
	r.fieldMap["tenant_id"] = r.TenantID
	r.fieldMap["route_id"] = r.RouteID
	r.fieldMap["from_waypoint_id"] = r.FromWaypointID
	r.fieldMap["to_waypoint_id"] = r.ToWaypointID
	r.fieldMap["from_task_seq"] = r.FromTaskSeq
	r.fieldMap["to_task_seq"] = r.ToTaskSeq
	r.fieldMap["edge_seq"] = r.EdgeSeq
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r robotdogRouteEdge) clone(db *gorm.DB) robotdogRouteEdge {
	r.robotdogRouteEdgeDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r robotdogRouteEdge) replaceDB(db *gorm.DB) robotdogRouteEdge {
	r.robotdogRouteEdgeDo.ReplaceDB(db)
	return r
}

type robotdogRouteEdgeDo struct{ gen.DO }

type IRobotdogRouteEdgeDo interface {
	gen.SubQuery
	Debug() IRobotdogRouteEdgeDo
	WithContext(ctx context.Context) IRobotdogRouteEdgeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRobotdogRouteEdgeDo
	WriteDB() IRobotdogRouteEdgeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRobotdogRouteEdgeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRobotdogRouteEdgeDo
	Not(conds ...gen.Condition) IRobotdogRouteEdgeDo
	Or(conds ...gen.Condition) IRobotdogRouteEdgeDo
	Select(conds ...field.Expr) IRobotdogRouteEdgeDo
	Where(conds ...gen.Condition) IRobotdogRouteEdgeDo
	Order(conds ...field.Expr) IRobotdogRouteEdgeDo
	Distinct(cols ...field.Expr) IRobotdogRouteEdgeDo
	Omit(cols ...field.Expr) IRobotdogRouteEdgeDo
	Join(table schema.Tabler, on ...field.Expr) IRobotdogRouteEdgeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteEdgeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteEdgeDo
	Group(cols ...field.Expr) IRobotdogRouteEdgeDo
	Having(conds ...gen.Condition) IRobotdogRouteEdgeDo
	Limit(limit int) IRobotdogRouteEdgeDo
	Offset(offset int) IRobotdogRouteEdgeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogRouteEdgeDo
	Unscoped() IRobotdogRouteEdgeDo
	Create(values ...*model.RobotdogRouteEdge) error
	CreateInBatches(values []*model.RobotdogRouteEdge, batchSize int) error
	Save(values ...*model.RobotdogRouteEdge) error
	First() (*model.RobotdogRouteEdge, error)
	Take() (*model.RobotdogRouteEdge, error)
	Last() (*model.RobotdogRouteEdge, error)
	Find() ([]*model.RobotdogRouteEdge, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogRouteEdge, err error)
	FindInBatches(result *[]*model.RobotdogRouteEdge, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RobotdogRouteEdge) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRobotdogRouteEdgeDo
	Assign(attrs ...field.AssignExpr) IRobotdogRouteEdgeDo
	Joins(fields ...field.RelationField) IRobotdogRouteEdgeDo
	Preload(fields ...field.RelationField) IRobotdogRouteEdgeDo
	FirstOrInit() (*model.RobotdogRouteEdge, error)
	FirstOrCreate() (*model.RobotdogRouteEdge, error)
	FindByPage(offset int, limit int) (result []*model.RobotdogRouteEdge, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRobotdogRouteEdgeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r robotdogRouteEdgeDo) Debug() IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Debug())
}

func (r robotdogRouteEdgeDo) WithContext(ctx context.Context) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r robotdogRouteEdgeDo) ReadDB() IRobotdogRouteEdgeDo {
	return r.Clauses(dbresolver.Read)
}

func (r robotdogRouteEdgeDo) WriteDB() IRobotdogRouteEdgeDo {
	return r.Clauses(dbresolver.Write)
}

func (r robotdogRouteEdgeDo) Session(config *gorm.Session) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Session(config))
}

func (r robotdogRouteEdgeDo) Clauses(conds ...clause.Expression) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r robotdogRouteEdgeDo) Returning(value interface{}, columns ...string) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r robotdogRouteEdgeDo) Not(conds ...gen.Condition) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r robotdogRouteEdgeDo) Or(conds ...gen.Condition) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r robotdogRouteEdgeDo) Select(conds ...field.Expr) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r robotdogRouteEdgeDo) Where(conds ...gen.Condition) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r robotdogRouteEdgeDo) Order(conds ...field.Expr) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r robotdogRouteEdgeDo) Distinct(cols ...field.Expr) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r robotdogRouteEdgeDo) Omit(cols ...field.Expr) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r robotdogRouteEdgeDo) Join(table schema.Tabler, on ...field.Expr) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r robotdogRouteEdgeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r robotdogRouteEdgeDo) RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r robotdogRouteEdgeDo) Group(cols ...field.Expr) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r robotdogRouteEdgeDo) Having(conds ...gen.Condition) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r robotdogRouteEdgeDo) Limit(limit int) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r robotdogRouteEdgeDo) Offset(offset int) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r robotdogRouteEdgeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r robotdogRouteEdgeDo) Unscoped() IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Unscoped())
}

func (r robotdogRouteEdgeDo) Create(values ...*model.RobotdogRouteEdge) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r robotdogRouteEdgeDo) CreateInBatches(values []*model.RobotdogRouteEdge, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r robotdogRouteEdgeDo) Save(values ...*model.RobotdogRouteEdge) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r robotdogRouteEdgeDo) First() (*model.RobotdogRouteEdge, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteEdge), nil
	}
}

func (r robotdogRouteEdgeDo) Take() (*model.RobotdogRouteEdge, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteEdge), nil
	}
}

func (r robotdogRouteEdgeDo) Last() (*model.RobotdogRouteEdge, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteEdge), nil
	}
}

func (r robotdogRouteEdgeDo) Find() ([]*model.RobotdogRouteEdge, error) {
	result, err := r.DO.Find()
	return result.([]*model.RobotdogRouteEdge), err
}

func (r robotdogRouteEdgeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogRouteEdge, err error) {
	buf := make([]*model.RobotdogRouteEdge, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r robotdogRouteEdgeDo) FindInBatches(result *[]*model.RobotdogRouteEdge, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r robotdogRouteEdgeDo) Attrs(attrs ...field.AssignExpr) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r robotdogRouteEdgeDo) Assign(attrs ...field.AssignExpr) IRobotdogRouteEdgeDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r robotdogRouteEdgeDo) Joins(fields ...field.RelationField) IRobotdogRouteEdgeDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r robotdogRouteEdgeDo) Preload(fields ...field.RelationField) IRobotdogRouteEdgeDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r robotdogRouteEdgeDo) FirstOrInit() (*model.RobotdogRouteEdge, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteEdge), nil
	}
}

func (r robotdogRouteEdgeDo) FirstOrCreate() (*model.RobotdogRouteEdge, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRouteEdge), nil
	}
}

func (r robotdogRouteEdgeDo) FindByPage(offset int, limit int) (result []*model.RobotdogRouteEdge, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r robotdogRouteEdgeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r robotdogRouteEdgeDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r robotdogRouteEdgeDo) Delete(models ...*model.RobotdogRouteEdge) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *robotdogRouteEdgeDo) withDO(do gen.Dao) *robotdogRouteEdgeDo {
	r.DO = *do.(*gen.DO)
	return r
}
