// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newRobotdogRoute(db *gorm.DB, opts ...gen.DOOption) robotdogRoute {
	_robotdogRoute := robotdogRoute{}

	_robotdogRoute.robotdogRouteDo.UseDB(db, opts...)
	_robotdogRoute.robotdogRouteDo.UseModel(&model.RobotdogRoute{})

	tableName := _robotdogRoute.robotdogRouteDo.TableName()
	_robotdogRoute.ALL = field.NewAsterisk(tableName)
	_robotdogRoute.ID = field.NewInt64(tableName, "id")
	_robotdogRoute.TenantID = field.NewInt32(tableName, "tenant_id")
	_robotdogRoute.DogID = field.NewInt64(tableName, "dog_id")
	_robotdogRoute.Name = field.NewString(tableName, "name")
	_robotdogRoute.Status = field.NewString(tableName, "status")
	_robotdogRoute.RunStatus = field.NewString(tableName, "run_status")
	_robotdogRoute.Remark = field.NewString(tableName, "remark")
	_robotdogRoute.CreatedAt = field.NewTime(tableName, "created_at")
	_robotdogRoute.UpdatedAt = field.NewTime(tableName, "updated_at")
	_robotdogRoute.DeletedAt = field.NewField(tableName, "deleted_at")

	_robotdogRoute.fillFieldMap()

	return _robotdogRoute
}

// robotdogRoute 机械狗航线
type robotdogRoute struct {
	robotdogRouteDo

	ALL       field.Asterisk
	ID        field.Int64  // ID
	TenantID  field.Int32  // 租户唯一标识
	DogID     field.Int64  // 机械狗ID
	Name      field.String // 航线名称
	Status    field.String // 状态:draft/ready/published
	RunStatus field.String // 执行状态:idle/running/done
	Remark    field.String // 备注
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (r robotdogRoute) Table(newTableName string) *robotdogRoute {
	r.robotdogRouteDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r robotdogRoute) As(alias string) *robotdogRoute {
	r.robotdogRouteDo.DO = *(r.robotdogRouteDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *robotdogRoute) updateTableName(table string) *robotdogRoute {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.TenantID = field.NewInt32(table, "tenant_id")
	r.DogID = field.NewInt64(table, "dog_id")
	r.Name = field.NewString(table, "name")
	r.Status = field.NewString(table, "status")
	r.RunStatus = field.NewString(table, "run_status")
	r.Remark = field.NewString(table, "remark")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *robotdogRoute) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *robotdogRoute) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 10)
	r.fieldMap["id"] = r.ID
	r.fieldMap["tenant_id"] = r.TenantID
	r.fieldMap["dog_id"] = r.DogID
	r.fieldMap["name"] = r.Name
	r.fieldMap["status"] = r.Status
	r.fieldMap["run_status"] = r.RunStatus
	r.fieldMap["remark"] = r.Remark
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r robotdogRoute) clone(db *gorm.DB) robotdogRoute {
	r.robotdogRouteDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r robotdogRoute) replaceDB(db *gorm.DB) robotdogRoute {
	r.robotdogRouteDo.ReplaceDB(db)
	return r
}

type robotdogRouteDo struct{ gen.DO }

type IRobotdogRouteDo interface {
	gen.SubQuery
	Debug() IRobotdogRouteDo
	WithContext(ctx context.Context) IRobotdogRouteDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRobotdogRouteDo
	WriteDB() IRobotdogRouteDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRobotdogRouteDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRobotdogRouteDo
	Not(conds ...gen.Condition) IRobotdogRouteDo
	Or(conds ...gen.Condition) IRobotdogRouteDo
	Select(conds ...field.Expr) IRobotdogRouteDo
	Where(conds ...gen.Condition) IRobotdogRouteDo
	Order(conds ...field.Expr) IRobotdogRouteDo
	Distinct(cols ...field.Expr) IRobotdogRouteDo
	Omit(cols ...field.Expr) IRobotdogRouteDo
	Join(table schema.Tabler, on ...field.Expr) IRobotdogRouteDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteDo
	Group(cols ...field.Expr) IRobotdogRouteDo
	Having(conds ...gen.Condition) IRobotdogRouteDo
	Limit(limit int) IRobotdogRouteDo
	Offset(offset int) IRobotdogRouteDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogRouteDo
	Unscoped() IRobotdogRouteDo
	Create(values ...*model.RobotdogRoute) error
	CreateInBatches(values []*model.RobotdogRoute, batchSize int) error
	Save(values ...*model.RobotdogRoute) error
	First() (*model.RobotdogRoute, error)
	Take() (*model.RobotdogRoute, error)
	Last() (*model.RobotdogRoute, error)
	Find() ([]*model.RobotdogRoute, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogRoute, err error)
	FindInBatches(result *[]*model.RobotdogRoute, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RobotdogRoute) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRobotdogRouteDo
	Assign(attrs ...field.AssignExpr) IRobotdogRouteDo
	Joins(fields ...field.RelationField) IRobotdogRouteDo
	Preload(fields ...field.RelationField) IRobotdogRouteDo
	FirstOrInit() (*model.RobotdogRoute, error)
	FirstOrCreate() (*model.RobotdogRoute, error)
	FindByPage(offset int, limit int) (result []*model.RobotdogRoute, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRobotdogRouteDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r robotdogRouteDo) Debug() IRobotdogRouteDo {
	return r.withDO(r.DO.Debug())
}

func (r robotdogRouteDo) WithContext(ctx context.Context) IRobotdogRouteDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r robotdogRouteDo) ReadDB() IRobotdogRouteDo {
	return r.Clauses(dbresolver.Read)
}

func (r robotdogRouteDo) WriteDB() IRobotdogRouteDo {
	return r.Clauses(dbresolver.Write)
}

func (r robotdogRouteDo) Session(config *gorm.Session) IRobotdogRouteDo {
	return r.withDO(r.DO.Session(config))
}

func (r robotdogRouteDo) Clauses(conds ...clause.Expression) IRobotdogRouteDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r robotdogRouteDo) Returning(value interface{}, columns ...string) IRobotdogRouteDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r robotdogRouteDo) Not(conds ...gen.Condition) IRobotdogRouteDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r robotdogRouteDo) Or(conds ...gen.Condition) IRobotdogRouteDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r robotdogRouteDo) Select(conds ...field.Expr) IRobotdogRouteDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r robotdogRouteDo) Where(conds ...gen.Condition) IRobotdogRouteDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r robotdogRouteDo) Order(conds ...field.Expr) IRobotdogRouteDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r robotdogRouteDo) Distinct(cols ...field.Expr) IRobotdogRouteDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r robotdogRouteDo) Omit(cols ...field.Expr) IRobotdogRouteDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r robotdogRouteDo) Join(table schema.Tabler, on ...field.Expr) IRobotdogRouteDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r robotdogRouteDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r robotdogRouteDo) RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogRouteDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r robotdogRouteDo) Group(cols ...field.Expr) IRobotdogRouteDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r robotdogRouteDo) Having(conds ...gen.Condition) IRobotdogRouteDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r robotdogRouteDo) Limit(limit int) IRobotdogRouteDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r robotdogRouteDo) Offset(offset int) IRobotdogRouteDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r robotdogRouteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogRouteDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r robotdogRouteDo) Unscoped() IRobotdogRouteDo {
	return r.withDO(r.DO.Unscoped())
}

func (r robotdogRouteDo) Create(values ...*model.RobotdogRoute) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r robotdogRouteDo) CreateInBatches(values []*model.RobotdogRoute, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r robotdogRouteDo) Save(values ...*model.RobotdogRoute) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r robotdogRouteDo) First() (*model.RobotdogRoute, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRoute), nil
	}
}

func (r robotdogRouteDo) Take() (*model.RobotdogRoute, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRoute), nil
	}
}

func (r robotdogRouteDo) Last() (*model.RobotdogRoute, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRoute), nil
	}
}

func (r robotdogRouteDo) Find() ([]*model.RobotdogRoute, error) {
	result, err := r.DO.Find()
	return result.([]*model.RobotdogRoute), err
}

func (r robotdogRouteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogRoute, err error) {
	buf := make([]*model.RobotdogRoute, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r robotdogRouteDo) FindInBatches(result *[]*model.RobotdogRoute, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r robotdogRouteDo) Attrs(attrs ...field.AssignExpr) IRobotdogRouteDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r robotdogRouteDo) Assign(attrs ...field.AssignExpr) IRobotdogRouteDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r robotdogRouteDo) Joins(fields ...field.RelationField) IRobotdogRouteDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r robotdogRouteDo) Preload(fields ...field.RelationField) IRobotdogRouteDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r robotdogRouteDo) FirstOrInit() (*model.RobotdogRoute, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRoute), nil
	}
}

func (r robotdogRouteDo) FirstOrCreate() (*model.RobotdogRoute, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogRoute), nil
	}
}

func (r robotdogRouteDo) FindByPage(offset int, limit int) (result []*model.RobotdogRoute, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r robotdogRouteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r robotdogRouteDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r robotdogRouteDo) Delete(models ...*model.RobotdogRoute) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *robotdogRouteDo) withDO(do gen.Dao) *robotdogRouteDo {
	r.DO = *do.(*gen.DO)
	return r
}
