// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gofly/dao/model"
)

func newRobotdogTask(db *gorm.DB, opts ...gen.DOOption) robotdogTask {
	_robotdogTask := robotdogTask{}

	_robotdogTask.robotdogTaskDo.UseDB(db, opts...)
	_robotdogTask.robotdogTaskDo.UseModel(&model.RobotdogTask{})

	tableName := _robotdogTask.robotdogTaskDo.TableName()
	_robotdogTask.ALL = field.NewAsterisk(tableName)
	_robotdogTask.ID = field.NewInt64(tableName, "id")
	_robotdogTask.TenantID = field.NewInt32(tableName, "tenant_id")
	_robotdogTask.TaskID = field.NewString(tableName, "task_id")
	_robotdogTask.DogID = field.NewInt64(tableName, "dog_id")
	_robotdogTask.RouteID = field.NewInt64(tableName, "route_id")
	_robotdogTask.WaypointID = field.NewInt64(tableName, "waypoint_id")
	_robotdogTask.Type = field.NewString(tableName, "type")
	_robotdogTask.Action = field.NewString(tableName, "action")
	_robotdogTask.Status = field.NewString(tableName, "status")
	_robotdogTask.Progress = field.NewInt32(tableName, "progress")
	_robotdogTask.Message = field.NewString(tableName, "message")
	_robotdogTask.CreatedAt = field.NewTime(tableName, "created_at")
	_robotdogTask.UpdatedAt = field.NewTime(tableName, "updated_at")
	_robotdogTask.DeletedAt = field.NewField(tableName, "deleted_at")

	_robotdogTask.fillFieldMap()

	return _robotdogTask
}

// robotdogTask 机械狗任务
type robotdogTask struct {
	robotdogTaskDo

	ALL        field.Asterisk
	ID         field.Int64  // ID
	TenantID   field.Int32  // 租户唯一标识
	TaskID     field.String // 任务编号
	DogID      field.Int64  // 机械狗ID
	RouteID    field.Int64  // 航线ID
	WaypointID field.Int64  // 航点ID
	Type       field.String // 任务类型:route/nav
	Action     field.String // 动作
	Status     field.String // 状态
	Progress   field.Int32  // 进度
	Message    field.String // 消息
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间
	DeletedAt  field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (r robotdogTask) Table(newTableName string) *robotdogTask {
	r.robotdogTaskDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r robotdogTask) As(alias string) *robotdogTask {
	r.robotdogTaskDo.DO = *(r.robotdogTaskDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *robotdogTask) updateTableName(table string) *robotdogTask {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.TenantID = field.NewInt32(table, "tenant_id")
	r.TaskID = field.NewString(table, "task_id")
	r.DogID = field.NewInt64(table, "dog_id")
	r.RouteID = field.NewInt64(table, "route_id")
	r.WaypointID = field.NewInt64(table, "waypoint_id")
	r.Type = field.NewString(table, "type")
	r.Action = field.NewString(table, "action")
	r.Status = field.NewString(table, "status")
	r.Progress = field.NewInt32(table, "progress")
	r.Message = field.NewString(table, "message")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *robotdogTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *robotdogTask) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 14)
	r.fieldMap["id"] = r.ID
	r.fieldMap["tenant_id"] = r.TenantID
	r.fieldMap["task_id"] = r.TaskID
	r.fieldMap["dog_id"] = r.DogID
	r.fieldMap["route_id"] = r.RouteID
	r.fieldMap["waypoint_id"] = r.WaypointID
	r.fieldMap["type"] = r.Type
	r.fieldMap["action"] = r.Action
	r.fieldMap["status"] = r.Status
	r.fieldMap["progress"] = r.Progress
	r.fieldMap["message"] = r.Message
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r robotdogTask) clone(db *gorm.DB) robotdogTask {
	r.robotdogTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r robotdogTask) replaceDB(db *gorm.DB) robotdogTask {
	r.robotdogTaskDo.ReplaceDB(db)
	return r
}

type robotdogTaskDo struct{ gen.DO }

type IRobotdogTaskDo interface {
	gen.SubQuery
	Debug() IRobotdogTaskDo
	WithContext(ctx context.Context) IRobotdogTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRobotdogTaskDo
	WriteDB() IRobotdogTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRobotdogTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRobotdogTaskDo
	Not(conds ...gen.Condition) IRobotdogTaskDo
	Or(conds ...gen.Condition) IRobotdogTaskDo
	Select(conds ...field.Expr) IRobotdogTaskDo
	Where(conds ...gen.Condition) IRobotdogTaskDo
	Order(conds ...field.Expr) IRobotdogTaskDo
	Distinct(cols ...field.Expr) IRobotdogTaskDo
	Omit(cols ...field.Expr) IRobotdogTaskDo
	Join(table schema.Tabler, on ...field.Expr) IRobotdogTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogTaskDo
	Group(cols ...field.Expr) IRobotdogTaskDo
	Having(conds ...gen.Condition) IRobotdogTaskDo
	Limit(limit int) IRobotdogTaskDo
	Offset(offset int) IRobotdogTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogTaskDo
	Unscoped() IRobotdogTaskDo
	Create(values ...*model.RobotdogTask) error
	CreateInBatches(values []*model.RobotdogTask, batchSize int) error
	Save(values ...*model.RobotdogTask) error
	First() (*model.RobotdogTask, error)
	Take() (*model.RobotdogTask, error)
	Last() (*model.RobotdogTask, error)
	Find() ([]*model.RobotdogTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogTask, err error)
	FindInBatches(result *[]*model.RobotdogTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RobotdogTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRobotdogTaskDo
	Assign(attrs ...field.AssignExpr) IRobotdogTaskDo
	Joins(fields ...field.RelationField) IRobotdogTaskDo
	Preload(fields ...field.RelationField) IRobotdogTaskDo
	FirstOrInit() (*model.RobotdogTask, error)
	FirstOrCreate() (*model.RobotdogTask, error)
	FindByPage(offset int, limit int) (result []*model.RobotdogTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRobotdogTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r robotdogTaskDo) Debug() IRobotdogTaskDo {
	return r.withDO(r.DO.Debug())
}

func (r robotdogTaskDo) WithContext(ctx context.Context) IRobotdogTaskDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r robotdogTaskDo) ReadDB() IRobotdogTaskDo {
	return r.Clauses(dbresolver.Read)
}

func (r robotdogTaskDo) WriteDB() IRobotdogTaskDo {
	return r.Clauses(dbresolver.Write)
}

func (r robotdogTaskDo) Session(config *gorm.Session) IRobotdogTaskDo {
	return r.withDO(r.DO.Session(config))
}

func (r robotdogTaskDo) Clauses(conds ...clause.Expression) IRobotdogTaskDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r robotdogTaskDo) Returning(value interface{}, columns ...string) IRobotdogTaskDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r robotdogTaskDo) Not(conds ...gen.Condition) IRobotdogTaskDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r robotdogTaskDo) Or(conds ...gen.Condition) IRobotdogTaskDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r robotdogTaskDo) Select(conds ...field.Expr) IRobotdogTaskDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r robotdogTaskDo) Where(conds ...gen.Condition) IRobotdogTaskDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r robotdogTaskDo) Order(conds ...field.Expr) IRobotdogTaskDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r robotdogTaskDo) Distinct(cols ...field.Expr) IRobotdogTaskDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r robotdogTaskDo) Omit(cols ...field.Expr) IRobotdogTaskDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r robotdogTaskDo) Join(table schema.Tabler, on ...field.Expr) IRobotdogTaskDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r robotdogTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRobotdogTaskDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r robotdogTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) IRobotdogTaskDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r robotdogTaskDo) Group(cols ...field.Expr) IRobotdogTaskDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r robotdogTaskDo) Having(conds ...gen.Condition) IRobotdogTaskDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r robotdogTaskDo) Limit(limit int) IRobotdogTaskDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r robotdogTaskDo) Offset(offset int) IRobotdogTaskDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r robotdogTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRobotdogTaskDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r robotdogTaskDo) Unscoped() IRobotdogTaskDo {
	return r.withDO(r.DO.Unscoped())
}

func (r robotdogTaskDo) Create(values ...*model.RobotdogTask) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r robotdogTaskDo) CreateInBatches(values []*model.RobotdogTask, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r robotdogTaskDo) Save(values ...*model.RobotdogTask) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r robotdogTaskDo) First() (*model.RobotdogTask, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogTask), nil
	}
}

func (r robotdogTaskDo) Take() (*model.RobotdogTask, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogTask), nil
	}
}

func (r robotdogTaskDo) Last() (*model.RobotdogTask, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogTask), nil
	}
}

func (r robotdogTaskDo) Find() ([]*model.RobotdogTask, error) {
	result, err := r.DO.Find()
	return result.([]*model.RobotdogTask), err
}

func (r robotdogTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RobotdogTask, err error) {
	buf := make([]*model.RobotdogTask, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r robotdogTaskDo) FindInBatches(result *[]*model.RobotdogTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r robotdogTaskDo) Attrs(attrs ...field.AssignExpr) IRobotdogTaskDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r robotdogTaskDo) Assign(attrs ...field.AssignExpr) IRobotdogTaskDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r robotdogTaskDo) Joins(fields ...field.RelationField) IRobotdogTaskDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r robotdogTaskDo) Preload(fields ...field.RelationField) IRobotdogTaskDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r robotdogTaskDo) FirstOrInit() (*model.RobotdogTask, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogTask), nil
	}
}

func (r robotdogTaskDo) FirstOrCreate() (*model.RobotdogTask, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RobotdogTask), nil
	}
}

func (r robotdogTaskDo) FindByPage(offset int, limit int) (result []*model.RobotdogTask, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r robotdogTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r robotdogTaskDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r robotdogTaskDo) Delete(models ...*model.RobotdogTask) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *robotdogTaskDo) withDO(do gen.Dao) *robotdogTaskDo {
	r.DO = *do.(*gen.DO)
	return r
}
