// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAdminAuthRule = "gf_admin_auth_rule"

// AdminAuthRule 业务后台菜单
type AdminAuthRule struct {
	ID                 int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID                int64          `gorm:"column:uid;not null;comment:添加用户" json:"uid"`                                              // 添加用户
	Title              string         `gorm:"column:title;not null;comment:菜单名称" json:"title"`                                          // 菜单名称
	Des                string         `gorm:"column:des;not null;comment:描述" json:"des"`                                                // 描述
	Locale             string         `gorm:"column:locale;not null;comment:中英文标题key" json:"locale"`                                    // 中英文标题key
	Weigh              int32          `gorm:"column:weigh;not null;comment:排序" json:"weigh"`                                            // 排序
	Type               int8           `gorm:"column:type;not null;comment:类型 0=目录，1=菜单，2=按钮" json:"type"`                               // 类型 0=目录，1=菜单，2=按钮
	Pid                int32          `gorm:"column:pid;not null;comment:上一级" json:"pid"`                                               // 上一级
	Icon               string         `gorm:"column:icon;not null;comment:图标" json:"icon"`                                              // 图标
	Routepath          string         `gorm:"column:routepath;not null;comment:路由地址" json:"routepath"`                                  // 路由地址
	Routename          string         `gorm:"column:routename;not null;comment:路由名称" json:"routename"`                                  // 路由名称
	Component          string         `gorm:"column:component;not null;comment:组件路径" json:"component"`                                  // 组件路径
	Redirect           string         `gorm:"column:redirect;not null;comment:重定向地址" json:"redirect"`                                   // 重定向地址
	Path               string         `gorm:"column:path;not null;comment:接口路径" json:"path"`                                            // 接口路径
	Permission         string         `gorm:"column:permission;comment:权限标识" json:"permission"`                                         // 权限标识
	Status             int8           `gorm:"column:status;not null;comment:状态 0=启用1=禁用" json:"status"`                                 // 状态 0=启用1=禁用
	Isext              int8           `gorm:"column:isext;not null;comment:是否外链 0=否1=是" json:"isext"`                                   // 是否外链 0=否1=是
	Keepalive          int8           `gorm:"column:keepalive;not null;comment:是否缓存 0=否1=是" json:"keepalive"`                           // 是否缓存 0=否1=是
	Requiresauth       int8           `gorm:"column:requiresauth;not null;default:1;comment:是否需要登录鉴权 0=否1=是" json:"requiresauth"`       // 是否需要登录鉴权 0=否1=是
	Hideinmenu         int8           `gorm:"column:hideinmenu;not null;comment:是否在左侧菜单中隐藏该项 0=否1=是" json:"hideinmenu"`                 // 是否在左侧菜单中隐藏该项 0=否1=是
	Hidechildreninmenu int8           `gorm:"column:hidechildreninmenu;not null;comment:强制在左侧菜单中显示单项 0=否1=是" json:"hidechildreninmenu"` // 强制在左侧菜单中显示单项 0=否1=是
	Activemenu         int8           `gorm:"column:activemenu;not null;comment:高亮设置的菜单项 0=否1=是" json:"activemenu"`                     // 高亮设置的菜单项 0=否1=是
	Noaffix            int8           `gorm:"column:noaffix;not null;comment:如果设置为true，标签将不会添加到tab-bar中 0=否1=是" json:"noaffix"`         // 如果设置为true，标签将不会添加到tab-bar中 0=否1=是
	Onlypage           int8           `gorm:"column:onlypage;not null;comment:独立页面不需layout和登录，如登录页、数据大屏" json:"onlypage"`               // 独立页面不需layout和登录，如登录页、数据大屏
	CreatedAt          time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                         // 创建时间
	UpdatedAt          time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                         // 更新时间
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                         // 删除时间
}

// TableName AdminAuthRule's table name
func (*AdminAuthRule) TableName() string {
	return TableNameAdminAuthRule
}
