// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAdminAuthDept = "gf_admin_auth_dept"

// AdminAuthDept 管理后台部门
type AdminAuthDept struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TenantID  int32          `gorm:"column:tenant_id;not null;default:1;comment:租户唯一标识" json:"tenant_id"` // 租户唯一标识
	AccountID int64          `gorm:"column:account_id;not null;comment:添加账号" json:"account_id"`           // 添加账号
	Name      string         `gorm:"column:name;not null;comment:部门名称" json:"name"`                       // 部门名称
	Pid       int32          `gorm:"column:pid;not null;comment:上级部门" json:"pid"`                         // 上级部门
	Weigh     int32          `gorm:"column:weigh;not null;comment:排序" json:"weigh"`                       // 排序
	Status    int8           `gorm:"column:status;not null;comment:状态:0=正常;1=禁用" json:"status"`           // 状态:0=正常;1=禁用
	Remark    string         `gorm:"column:remark;not null;comment:备注" json:"remark"`                     // 备注
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                    // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                    // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                    // 删除时间
}

// TableName AdminAuthDept's table name
func (*AdminAuthDept) TableName() string {
	return TableNameAdminAuthDept
}
