// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAdmin = "gf_admin"

// Admin 管理员表
type Admin struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`              // ID
	TenantID      int32          `gorm:"column:tenant_id;not null;default:1;comment:租户唯一标识" json:"tenant_id"`       // 租户唯一标识
	AccountID     int64          `gorm:"column:account_id;not null;comment:账号id/记录那个账号添加" json:"account_id"`        // 账号id/记录那个账号添加
	MainAccount   int8           `gorm:"column:main_account;not null;comment:是否为租户主账号:0=否,1=是" json:"main_account"` // 是否为租户主账号:0=否,1=是
	DeptID        int32          `gorm:"column:dept_id;not null;comment:部门id" json:"dept_id"`                       // 部门id
	Username      string         `gorm:"column:username;comment:用户名" json:"username"`                               // 用户名
	Password      string         `gorm:"column:password;comment:密码" json:"password"`                                // 密码
	Salt          string         `gorm:"column:salt;comment:密码盐" json:"salt"`                                       // 密码盐
	Name          string         `gorm:"column:name;comment:姓名" json:"name"`                                        // 姓名
	Nickname      string         `gorm:"column:nickname;comment:昵称" json:"nickname"`                                // 昵称
	Avatar        string         `gorm:"column:avatar;comment:头像" json:"avatar"`                                    // 头像
	Email         string         `gorm:"column:email;comment:电子邮箱" json:"email"`                                    // 电子邮箱
	Mobile        string         `gorm:"column:mobile;comment:手机号码" json:"mobile"`                                  // 手机号码
	Tel           string         `gorm:"column:tel;not null;comment:备用电话用户自己填写" json:"tel"`                         // 备用电话用户自己填写
	Status        int8           `gorm:"column:status;not null;comment:状态:0=正常,1=禁用" json:"status"`                 // 状态:0=正常,1=禁用
	Remark        string         `gorm:"column:remark;not null;comment:备注" json:"remark"`                           // 备注
	Loginip       string         `gorm:"column:loginip;comment:登录IP" json:"loginip"`                                // 登录IP
	Logintime     time.Time      `gorm:"column:logintime;comment:最后登录时间" json:"logintime"`                          // 最后登录时间
	LoginAttempts int8           `gorm:"column:login_attempts;not null;comment:登录尝试次数" json:"login_attempts"`       // 登录尝试次数
	LockTime      time.Time      `gorm:"column:lock_time;comment:账号锁定时间" json:"lock_time"`                          // 账号锁定时间
	PwdResetTime  time.Time      `gorm:"column:pwd_reset_time;comment:修改密码时间" json:"pwd_reset_time"`                // 修改密码时间
	CreatedAt     time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                          // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                          // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                          // 删除时间
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
