// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdminAuthRoleAccess = "gf_admin_auth_role_access"

// AdminAuthRoleAccess 业务后台菜单授权
type AdminAuthRoleAccess struct {
	UID    int64 `gorm:"column:uid;not null;comment:账号id" json:"uid"`         // 账号id
	RoleID int32 `gorm:"column:role_id;not null;comment:授权id" json:"role_id"` // 授权id
}

// TableName AdminAuthRoleAccess's table name
func (*AdminAuthRoleAccess) TableName() string {
	return TableNameAdminAuthRoleAccess
}
