// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminAuthRole = "gf_admin_auth_role"

// AdminAuthRole 权限分组
type AdminAuthRole struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TenantID   int32     `gorm:"column:tenant_id;not null;comment:租户唯一标识" json:"tenant_id"`                    // 租户唯一标识
	AccountID  int64     `gorm:"column:account_id;not null;comment:添加用户id" json:"account_id"`                  // 添加用户id
	Pid        int32     `gorm:"column:pid;not null;comment:父级" json:"pid"`                                    // 父级
	Name       string    `gorm:"column:name;not null;comment:名称" json:"name"`                                  // 名称
	Rules      string    `gorm:"column:rules;not null;comment:规则ID 所拥有的权限包括父级" json:"rules"`                   // 规则ID 所拥有的权限包括父级
	Menu       string    `gorm:"column:menu;not null;comment:选择的id，用于编辑赋值" json:"menu"`                        // 选择的id，用于编辑赋值
	Btns       string    `gorm:"column:btns;not null;comment:按钮id，用于编辑赋值" json:"btns"`                         // 按钮id，用于编辑赋值
	Status     int8      `gorm:"column:status;not null;comment:状态1=禁用" json:"status"`                          // 状态1=禁用
	DataAccess int8      `gorm:"column:data_access;not null;comment:数据权限0=自己1=自己及子权限，2=全部" json:"data_access"` // 数据权限0=自己1=自己及子权限，2=全部
	Remark     string    `gorm:"column:remark;not null;comment:描述" json:"remark"`                              // 描述
	Weigh      int32     `gorm:"column:weigh;not null;comment:排序" json:"weigh"`                                // 排序
	CreatedAt  time.Time `gorm:"column:created_at;comment:添加时间" json:"created_at"`                             // 添加时间
}

// TableName AdminAuthRole's table name
func (*AdminAuthRole) TableName() string {
	return TableNameAdminAuthRole
}
