// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAttachment = "gf_attachment"

// Attachment 客户端附件
type Attachment struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:文件类型0=图片，1=文件夹,2=视频，3=音频,4=文档" json:"id"`                               // 文件类型0=图片，1=文件夹,2=视频，3=音频,4=文档
	TenantID    int32     `gorm:"column:tenant_id;not null;comment:租户唯一标识" json:"tenant_id"`                                                             // 租户唯一标识
	Pid         int64     `gorm:"column:pid;not null;comment:附件" json:"pid"`                                                                             // 附件
	Location    string    `gorm:"column:location;not null;default:local;comment:图片存储位置:local=本地,alioss=阿里云,tencentcos=腾讯云,qiniuoss=七牛云" json:"location"` // 图片存储位置:local=本地,alioss=阿里云,tencentcos=腾讯云,qiniuoss=七牛云
	Name        string    `gorm:"column:name;not null;comment:附件原来名称" json:"name"`                                                                       // 附件原来名称
	Title       string    `gorm:"column:title;not null;comment:文件名称" json:"title"`                                                                       // 文件名称
	Type        int8      `gorm:"column:type;not null;comment:文件类型0=图片，1=文件夹,2=视频，3=音频,4=文档,5=其他" json:"type"`                                           // 文件类型0=图片，1=文件夹,2=视频，3=音频,4=文档,5=其他
	Weigh       int64     `gorm:"column:weigh;not null;comment:排序" json:"weigh"`                                                                         // 排序
	URL         string    `gorm:"column:url;not null;comment:访问路径" json:"url"`                                                                           // 访问路径
	Imagewidth  string    `gorm:"column:imagewidth;not null;comment:宽度" json:"imagewidth"`                                                               // 宽度
	Imageheight string    `gorm:"column:imageheight;not null;comment:高度" json:"imageheight"`                                                             // 高度
	Filesize    int64     `gorm:"column:filesize;not null;comment:文件大小" json:"filesize"`                                                                 // 文件大小
	Mimetype    string    `gorm:"column:mimetype;not null;comment:mime类型" json:"mimetype"`                                                               // mime类型
	Extparam    string    `gorm:"column:extparam;not null;comment:透传数据" json:"extparam"`                                                                 // 透传数据
	Storage     string    `gorm:"column:storage;not null;default:local;comment:存储位置" json:"storage"`                                                     // 存储位置
	CoverURL    string    `gorm:"column:cover_url;not null;comment:视频封面" json:"cover_url"`                                                               // 视频封面
	Sha1        string    `gorm:"column:sha1;not null;comment:文件 sha1编码" json:"sha1"`                                                                    // 文件 sha1编码
	IsCommon    int8      `gorm:"column:is_common;not null;comment:是否公共1=是" json:"is_common"`                                                            // 是否公共1=是
	CreatedAt   time.Time `gorm:"column:created_at;comment:上传时间" json:"created_at"`                                                                      // 上传时间
}

// TableName Attachment's table name
func (*Attachment) TableName() string {
	return TableNameAttachment
}
