// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommonMessage = "gf_common_message"

// CommonMessage 系统通用消息
type CommonMessage struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Usertype  int8      `gorm:"column:usertype;not null;comment:用户类型0=全部，1=系统-2=boss端，3=C端" json:"usertype"` // 用户类型0=全部，1=系统-2=boss端，3=C端
	AccountID int64     `gorm:"column:account_id;not null;comment:账号id" json:"account_id"`                   // 账号id
	Adduid    int32     `gorm:"column:adduid;not null;comment:添加用户" json:"adduid"`                           // 添加用户
	Touid     int32     `gorm:"column:touid;not null;comment:接收用户" json:"touid"`                             // 接收用户
	Type      int8      `gorm:"column:type;not null;default:2;comment:类型1=通知，2=消息，3=代办" json:"type"`         // 类型1=通知，2=消息，3=代办
	Title     string    `gorm:"column:title;not null;comment:消息标题" json:"title"`                             // 消息标题
	Path      string    `gorm:"column:path;not null;comment:跳转路由" json:"path"`                               // 跳转路由
	Content   string    `gorm:"column:content;not null;comment:消息内容" json:"content"`                         // 消息内容
	Isread    int8      `gorm:"column:isread;not null;comment:是否已读1=已读" json:"isread"`                       // 是否已读1=已读
	CreatedAt time.Time `gorm:"column:created_at;comment:发送时间" json:"created_at"`                            // 发送时间
}

// TableName CommonMessage's table name
func (*CommonMessage) TableName() string {
	return TableNameCommonMessage
}
