// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCreatecodeProductCate = "gf_createcode_product_cate"

// CreatecodeProductCate 测试代码产品分类
type CreatecodeProductCate struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AccountID int64          `gorm:"column:account_id;not null;comment:账号id/记录那个账号添加" json:"account_id"` // 账号id/记录那个账号添加
	TenantID  int64          `gorm:"column:tenant_id;not null;comment:租户唯一标识" json:"tenant_id"`          // 租户唯一标识
	Pid       int32          `gorm:"column:pid;not null;comment:父级" json:"pid"`                          // 父级
	Name      string         `gorm:"column:name;not null;comment:名称" json:"name"`                        // 名称
	Remark    string         `gorm:"column:remark;not null;comment:备注" json:"remark"`                    // 备注
	Weigh     int32          `gorm:"column:weigh;not null;comment:排序" json:"weigh"`                      // 排序
	Status    int8           `gorm:"column:status;not null;comment:状态:0=正常,1=隐藏" json:"status"`          // 状态:0=正常,1=隐藏
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                   // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                   // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                   // 删除时间
}

// TableName CreatecodeProductCate's table name
func (*CreatecodeProductCate) TableName() string {
	return TableNameCreatecodeProductCate
}
