// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCreatecodeProduct = "gf_createcode_product"

// CreatecodeProduct 测试代码产品
type CreatecodeProduct struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AccountID   int64          `gorm:"column:account_id;not null;comment:账号id/记录那个账号添加" json:"account_id"`           // 账号id/记录那个账号添加
	TenantID    int64          `gorm:"column:tenant_id;not null;comment:租户唯一标识" json:"tenant_id"`                    // 租户唯一标识
	Cid         int32          `gorm:"column:cid;not null;comment:分类" json:"cid"`                                    // 分类
	Title       string         `gorm:"column:title;not null;comment:标题" json:"title"`                                // 标题
	Num         int32          `gorm:"column:num;not null;comment:库存" json:"num"`                                    // 库存
	Price       float64        `gorm:"column:price;not null;comment:价格" json:"price"`                                // 价格
	Sex         int8           `gorm:"column:sex;not null;comment:性别:0=未知,1=男,2=女" json:"sex"`                       // 性别:0=未知,1=男,2=女
	Desc        string         `gorm:"column:desc;not null;comment:描述" json:"desc"`                                  // 描述
	Content     string         `gorm:"column:content;not null;comment:内容详情" json:"content"`                          // 内容详情
	LikeColor   string         `gorm:"column:likeColor;not null;comment:喜欢的颜色" json:"likeColor"`                     // 喜欢的颜色
	BallType    string         `gorm:"column:ballType;not null;comment:球类" json:"ballType"`                          // 球类
	UserType    string         `gorm:"column:userType;not null;comment:用户类型" json:"userType"`                        // 用户类型
	Image       string         `gorm:"column:image;not null;comment:单张图" json:"image"`                               // 单张图
	Images      string         `gorm:"column:images;not null;comment:多张图" json:"images"`                             // 多张图
	Moreimgs    string         `gorm:"column:moreimgs;not null;comment:图组" json:"moreimgs"`                          // 图组
	Contenttow  string         `gorm:"column:contenttow;not null;comment:注意内容" json:"contenttow"`                    // 注意内容
	RecordAudio string         `gorm:"column:record_audio;not null;comment:记录录音" json:"record_audio"`                // 记录录音
	File        string         `gorm:"column:file;not null;comment:附件" json:"file"`                                  // 附件
	Workerway   string         `gorm:"column:workerway;not null;comment:出行方式:car=汽车,bus=公交,air=飞机" json:"workerway"` // 出行方式:car=汽车,bus=公交,air=飞机
	Status      int8           `gorm:"column:status;not null;comment:状态:0=正常,1=隐藏" json:"status"`                    // 状态:0=正常,1=隐藏
	CreatedAt   time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                             // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                             // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                             // 删除时间
}

// TableName CreatecodeProduct's table name
func (*CreatecodeProduct) TableName() string {
	return TableNameCreatecodeProduct
}
