// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDictionaryData = "gf_dictionary_data"

// DictionaryData 字典数据-公共表
type DictionaryData struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DataFrom  string    `gorm:"column:data_from;not null;default:admin;comment:数据来源:common=公共,admin=管理后台" json:"data_from"` // 数据来源:common=公共,admin=管理后台
	GroupID   int32     `gorm:"column:group_id;not null;comment:数据分组id" json:"group_id"`                                    // 数据分组id
	Keyname   string    `gorm:"column:keyname;not null;comment:字典名称" json:"keyname"`                                        // 字典名称
	Keyvalue  string    `gorm:"column:keyvalue;not null;comment:字典项值" json:"keyvalue"`                                      // 字典项值
	Tagcolor  string    `gorm:"column:tagcolor;not null;comment:标签颜色" json:"tagcolor"`                                      // 标签颜色
	Des       string    `gorm:"column:des;not null;comment:字典描述" json:"des"`                                                // 字典描述
	Status    int8      `gorm:"column:status;not null;comment:状态" json:"status"`                                            // 状态
	Weigh     int32     `gorm:"column:weigh;not null;comment:排序" json:"weigh"`                                              // 排序
	CreatedAt time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                           // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                           // 更新时间
}

// TableName DictionaryData's table name
func (*DictionaryData) TableName() string {
	return TableNameDictionaryData
}
