// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDictionaryGroup = "gf_dictionary_group"

// DictionaryGroup 字典分组
type DictionaryGroup struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TenantID  int32     `gorm:"column:tenant_id;not null;comment:租户唯一标识" json:"tenant_id"`                                   // 租户唯一标识
	Title     string    `gorm:"column:title;not null;comment:字典分组名称" json:"title"`                                           // 字典分组名称
	Remark    string    `gorm:"column:remark;not null;comment:备注" json:"remark"`                                             // 备注
	DataFrom  string    `gorm:"column:data_from;not null;default:common;comment:数据来源:common=公共,admin=管理后台" json:"data_from"` // 数据来源:common=公共,admin=管理后台
	DbWay     string    `gorm:"column:db_way;not null;default:sys;comment:数据存储位置:sys=公共表,alone=单独建表" json:"db_way"`          // 数据存储位置:sys=公共表,alone=单独建表
	Tablename string    `gorm:"column:tablename;not null;comment:数据表名称" json:"tablename"`                                    // 数据表名称
	Status    int8      `gorm:"column:status;not null;comment:状态" json:"status"`                                             // 状态
	Weigh     int32     `gorm:"column:weigh;not null;default:1;comment:排序" json:"weigh"`                                     // 排序
	CreatedAt time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                            // 创建时间
}

// TableName DictionaryGroup's table name
func (*DictionaryGroup) TableName() string {
	return TableNameDictionaryGroup
}
