// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGeneratecode = "gf_generatecode"

// Generatecode 代码生成
type Generatecode struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Fromtype      int8      `gorm:"column:fromtype;not null;comment:数据类型0=数据表，1=代码工具" json:"fromtype"`                       // 数据类型0=数据表，1=代码工具
	Tablename     string    `gorm:"column:tablename;not null;comment:表名称" json:"tablename"`                                  // 表名称
	Comment       string    `gorm:"column:comment;not null;comment:表备注" json:"comment"`                                      // 表备注
	Engine        string    `gorm:"column:engine;not null;comment:引擎" json:"engine"`                                         // 引擎
	TableRows     int32     `gorm:"column:table_rows;not null;comment:记录数" json:"table_rows"`                                // 记录数
	Collation     string    `gorm:"column:collation;not null;comment:编码" json:"collation"`                                   // 编码
	AutoIncrement int32     `gorm:"column:auto_increment;not null;default:1;comment:自增索引" json:"auto_increment"`             // 自增索引
	Status        int8      `gorm:"column:status;not null;comment:状态1=禁用" json:"status"`                                     // 状态1=禁用
	Pid           int32     `gorm:"column:pid;not null;comment:菜单上级" json:"pid"`                                             // 菜单上级
	Icon          string    `gorm:"column:icon;not null;comment:图标" json:"icon"`                                             // 图标
	Routepath     string    `gorm:"column:routepath;not null;comment:路由地址" json:"routepath"`                                 // 路由地址
	Routename     string    `gorm:"column:routename;not null;comment:路由名称" json:"routename"`                                 // 路由名称
	Component     string    `gorm:"column:component;not null;comment:组件路径" json:"component"`                                 // 组件路径
	Godir         string    `gorm:"column:godir;not null;comment:后端代码位置" json:"godir"`                                       // 后端代码位置
	APIPath       string    `gorm:"column:api_path;not null;comment:后端业务接口" json:"api_path"`                                 // 后端业务接口
	APIFilename   string    `gorm:"column:api_filename;not null;comment:后端文件名" json:"api_filename"`                          // 后端文件名
	Fields        string    `gorm:"column:fields;not null;comment:查询字段" json:"fields"`                                       // 查询字段
	RuleID        int32     `gorm:"column:rule_id;not null;comment:生成菜单id" json:"rule_id"`                                   // 生成菜单id
	RuleName      string    `gorm:"column:rule_name;not null;comment:菜单名称" json:"rule_name"`                                 // 菜单名称
	Codelocation  string    `gorm:"column:codelocation;not null;default:admin;comment:生成代码位置" json:"codelocation"`           // 生成代码位置
	IsInstall     int8      `gorm:"column:is_install;not null;comment:是否安装0=未安装，1=已安装，2=已卸载" json:"is_install"`              // 是否安装0=未安装，1=已安装，2=已卸载
	TplType       string    `gorm:"column:tpl_type;not null;default:list;comment:模板类型list=仅一个数据，cate=数据加分类" json:"tpl_type"` // 模板类型list=仅一个数据，cate=数据加分类
	CateTablename string    `gorm:"column:cate_tablename;not null;comment:分类表名称" json:"cate_tablename"`                      // 分类表名称
	CreatedAt     time.Time `gorm:"column:created_at;comment:上传时间" json:"created_at"`                                        // 上传时间
	UpdatedAt     time.Time `gorm:"column:updated_at;comment:修改时间" json:"updated_at"`                                        // 修改时间
}

// TableName Generatecode's table name
func (*Generatecode) TableName() string {
	return TableNameGeneratecode
}
