// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGeneratecodeField = "gf_generatecode_field"

// GeneratecodeField 生成代码字段管理
type GeneratecodeField struct {
	ID             int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GeneratecodeID int32  `gorm:"column:generatecode_id;not null;comment:关联列表" json:"generatecode_id"`      // 关联列表
	Islist         int8   `gorm:"column:islist;not null;comment:是否是列表1=是" json:"islist"`                    // 是否是列表1=是
	Name           string `gorm:"column:name;not null;comment:字段名称" json:"name"`                            // 字段名称
	Field          string `gorm:"column:field;not null;comment:字段" json:"field"`                            // 字段
	DataType       string `gorm:"column:data_type;not null;comment:数据库原生字段类型" json:"data_type"`             // 数据库原生字段类型
	Isorder        int8   `gorm:"column:isorder;not null;comment:是否参与排序" json:"isorder"`                    // 是否参与排序
	Align          string `gorm:"column:align;not null;default:left;comment:对齐方向" json:"align"`             // 对齐方向
	Width          int32  `gorm:"column:width;not null;comment:宽度" json:"width"`                            // 宽度
	ShowUI         string `gorm:"column:show_ui;not null;comment:显示UI" json:"show_ui"`                      // 显示UI
	Isform         int8   `gorm:"column:isform;not null;comment:是否为表单字段" json:"isform"`                     // 是否为表单字段
	Required       int8   `gorm:"column:required;not null;comment:是否为必填项" json:"required"`                  // 是否为必填项
	Formtype       string `gorm:"column:formtype;not null;comment:表单类型" json:"formtype"`                    // 表单类型
	Datatable      string `gorm:"column:datatable;not null;comment:关联数据表" json:"datatable"`                 // 关联数据表
	Datatablename  string `gorm:"column:datatablename;not null;comment:关联显示字段" json:"datatablename"`        // 关联显示字段
	DicGroupID     int32  `gorm:"column:dic_group_id;not null;comment:关联字典分组id" json:"dic_group_id"`        // 关联字典分组id
	Issearch       int8   `gorm:"column:issearch;not null;comment:是否查询" json:"issearch"`                    // 是否查询
	Searchway      string `gorm:"column:searchway;not null;default:=;comment:查询方式" json:"searchway"`        // 查询方式
	Searchtype     string `gorm:"column:searchtype;not null;comment:查询文本类型" json:"searchtype"`              // 查询文本类型
	FieldWeigh     int32  `gorm:"column:field_weigh;not null;comment:表单排序" json:"field_weigh"`              // 表单排序
	ListWeigh      int32  `gorm:"column:list_weigh;not null;comment:列表排序" json:"list_weigh"`                // 列表排序
	SearchWeigh    int32  `gorm:"column:search_weigh;not null;comment:搜索排序" json:"search_weigh"`            // 搜索排序
	DefValue       string `gorm:"column:def_value;not null;comment:默认值" json:"def_value"`                   // 默认值
	OptionValue    string `gorm:"column:option_value;not null;comment:选项值" json:"option_value"`             // 选项值
	Gridwidth      int32  `gorm:"column:gridwidth;not null;default:12;comment:布局栅格" json:"gridwidth"`       // 布局栅格
	Searchwidth    int32  `gorm:"column:searchwidth;not null;default:120;comment:搜索表单宽" json:"searchwidth"` // 搜索表单宽
}

// TableName GeneratecodeField's table name
func (*GeneratecodeField) TableName() string {
	return TableNameGeneratecodeField
}
