// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHomeQuickop = "gf_home_quickop"

// HomeQuickop 首页快捷操作
type HomeQuickop struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TenantID int32  `gorm:"column:tenant_id;not null;comment:租户唯一标识" json:"tenant_id"` // 租户唯一标识
	UID      int32  `gorm:"column:uid;not null;comment:添加人" json:"uid"`                // 添加人
	IsCommon int8   `gorm:"column:is_common;not null;comment:公共1=是" json:"is_common"`  // 公共1=是
	Type     int8   `gorm:"column:type;not null;comment:类型1=外部" json:"type"`           // 类型1=外部
	Name     string `gorm:"column:name;not null;comment:快捷名称" json:"name"`             // 快捷名称
	PathURL  string `gorm:"column:path_url;not null;comment:跳转路径" json:"path_url"`     // 跳转路径
	Icon     string `gorm:"column:icon;not null;comment:图标" json:"icon"`               // 图标
	Weigh    int32  `gorm:"column:weigh;not null;comment:权重" json:"weigh"`             // 权重
}

// TableName HomeQuickop's table name
func (*HomeQuickop) TableName() string {
	return TableNameHomeQuickop
}
