// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLoginLog = "gf_login_log"

// LoginLog 系统登录日志
type LoginLog struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TenantID  int32     `gorm:"column:tenant_id;comment:租户唯一标识" json:"tenant_id"`                  // 租户唯一标识
	AccountID int64     `gorm:"column:account_id;not null;comment:添加用户id" json:"account_id"`       // 添加用户id
	Type      string    `gorm:"column:type;not null;comment:类型:admin=admin后台（根据需要扩展）" json:"type"` // 类型:admin=admin后台（根据需要扩展）
	UID       int64     `gorm:"column:uid;not null;comment:用户id" json:"uid"`                       // 用户id
	Username  string    `gorm:"column:username;not null;comment:登录账号" json:"username"`             // 登录账号
	IP        string    `gorm:"column:ip;not null;comment:登录IP" json:"ip"`                         // 登录IP
	Address   string    `gorm:"column:address;not null;comment:地点" json:"address"`                 // 地点
	Des       string    `gorm:"column:des;not null;comment:登录行为" json:"des"`                       // 登录行为
	Os        string    `gorm:"column:os;comment:操作系统" json:"os"`                                  // 操作系统
	Browser   string    `gorm:"column:browser;comment:浏览器类型" json:"browser"`                       // 浏览器类型
	ErrorMsg  string    `gorm:"column:error_msg;not null;comment:登录失败原因" json:"error_msg"`         // 登录失败原因
	Status    int8      `gorm:"column:status;not null;comment:状态:0=成功,1=失败" json:"status"`         // 状态:0=成功,1=失败
	CreatedAt time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                  // 创建时间
}

// TableName LoginLog's table name
func (*LoginLog) TableName() string {
	return TableNameLoginLog
}
