// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMember = "gf_member"

// Member 会员表(用户主表)
type Member struct {
	ID             int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                    // ID
	TenantID       int32          `gorm:"column:tenant_id;not null;default:1;comment:租户唯一标识" json:"tenant_id"`             // 租户唯一标识
	Username       string         `gorm:"column:username;comment:用户名" json:"username"`                                     // 用户名
	Name           string         `gorm:"column:name;not null;comment:姓名" json:"name"`                                     // 姓名
	Nickname       string         `gorm:"column:nickname;comment:昵称" json:"nickname"`                                      // 昵称
	Remark         string         `gorm:"column:remark;not null;comment:备注" json:"remark"`                                 // 备注
	Password       string         `gorm:"column:password;comment:密码" json:"password"`                                      // 密码
	Salt           string         `gorm:"column:salt;comment:密码盐" json:"salt"`                                             // 密码盐
	Email          string         `gorm:"column:email;comment:电子邮箱" json:"email"`                                          // 电子邮箱
	Mobile         string         `gorm:"column:mobile;comment:手机号" json:"mobile"`                                         // 手机号
	Avatar         string         `gorm:"column:avatar;comment:头像" json:"avatar"`                                          // 头像
	Level          int8           `gorm:"column:level;not null;comment:等级" json:"level"`                                   // 等级
	Sex            int8           `gorm:"column:sex;not null;comment:性别:1=男性,2=女性,0=未知" json:"sex"`                        // 性别:1=男性,2=女性,0=未知
	Birthday       time.Time      `gorm:"column:birthday;comment:出生日期" json:"birthday"`                                    // 出生日期
	Money          float64        `gorm:"column:money;not null;comment:余额" json:"money"`                                   // 余额
	Score          int32          `gorm:"column:score;not null;comment:积分" json:"score"`                                   // 积分
	Successions    int32          `gorm:"column:successions;not null;default:1;comment:连续登录天数" json:"successions"`         // 连续登录天数
	Maxsuccessions int32          `gorm:"column:maxsuccessions;not null;default:1;comment:最大连续登录天数" json:"maxsuccessions"` // 最大连续登录天数
	Prevtime       int64          `gorm:"column:prevtime;comment:上次登录时间" json:"prevtime"`                                  // 上次登录时间
	Logintime      int64          `gorm:"column:logintime;comment:登录时间" json:"logintime"`                                  // 登录时间
	Loginip        string         `gorm:"column:loginip;comment:登录IP" json:"loginip"`                                      // 登录IP
	Loginfailure   int8           `gorm:"column:loginfailure;not null;comment:失败次数" json:"loginfailure"`                   // 失败次数
	Status         int8           `gorm:"column:status;not null;comment:状态" json:"status"`                                 // 状态
	CreatedAt      time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                // 创建时间
	UpdatedAt      time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                // 更新时间
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                // 删除时间
}

// TableName Member's table name
func (*Member) TableName() string {
	return TableNameMember
}
