// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOperationLog = "gf_operation_log"

// OperationLog 系统操作日志
type OperationLog struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type        string    `gorm:"column:type;not null;comment:类型:admin=admin后台（根据需要扩展）" json:"type"` // 类型:admin=admin后台（根据需要扩展）
	AccountID   int64     `gorm:"column:account_id;not null;comment:添加用户id" json:"account_id"`       // 添加用户id
	TenantID    int32     `gorm:"column:tenant_id;not null;comment:租户唯一标识" json:"tenant_id"`         // 租户唯一标识
	UID         int64     `gorm:"column:uid;not null;comment:用户id" json:"uid"`                       // 用户id
	Method      string    `gorm:"column:method;not null;comment:请求方法" json:"method"`                 // 请求方法
	URL         string    `gorm:"column:url;not null;comment:请求地址" json:"url"`                       // 请求地址
	IP          string    `gorm:"column:ip;not null;comment:登录IP" json:"ip"`                         // 登录IP
	Address     string    `gorm:"column:address;not null;comment:地点" json:"address"`                 // 地点
	Des         string    `gorm:"column:des;not null;comment:登录行为" json:"des"`                       // 登录行为
	ReqHeaders  string    `gorm:"column:req_headers;not null;comment:请求头" json:"req_headers"`        // 请求头
	ReqBody     string    `gorm:"column:req_body;not null;comment:请求体" json:"req_body"`              // 请求体
	RespHeaders string    `gorm:"column:resp_headers;not null;comment:响应头" json:"resp_headers"`      // 响应头
	RespBody    string    `gorm:"column:resp_body;not null;comment:响应体" json:"resp_body"`            // 响应体
	Latency     float64   `gorm:"column:latency;not null;default:0.0000;comment:耗时" json:"latency"`  // 耗时
	Status      int32     `gorm:"column:status;not null;comment:状态:0=成功,1=失败" json:"status"`         // 状态:0=成功,1=失败
	CreatedAt   time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                  // 创建时间
}

// TableName OperationLog's table name
func (*OperationLog) TableName() string {
	return TableNameOperationLog
}
