// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRobotdogRouteWaypoint = "gf_robotdog_route_waypoint"

// RobotdogRouteWaypoint 机械狗航线航点关系
type RobotdogRouteWaypoint struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`        // ID
	TenantID   int32          `gorm:"column:tenant_id;not null;default:1;comment:租户唯一标识" json:"tenant_id"` // 租户唯一标识
	RouteID    int64          `gorm:"column:route_id;not null;comment:航线ID" json:"route_id"`               // 航线ID
	WaypointID int64          `gorm:"column:waypoint_id;not null;comment:航点ID" json:"waypoint_id"`         // 航点ID
	Weigh      int32          `gorm:"column:weigh;not null;comment:排序" json:"weigh"`                       // 排序
	CreatedAt  time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                    // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                    // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                    // 删除时间
}

// TableName RobotdogRouteWaypoint's table name
func (*RobotdogRouteWaypoint) TableName() string {
	return TableNameRobotdogRouteWaypoint
}
