// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRobotdogRouteTask = "gf_robotdog_route_task"

// RobotdogRouteTask 机械狗航线子任务
type RobotdogRouteTask struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`        // ID
	TenantID  int32          `gorm:"column:tenant_id;not null;default:1;comment:租户唯一标识" json:"tenant_id"` // 租户唯一标识
	RouteID   int64          `gorm:"column:route_id;not null;comment:航线ID" json:"route_id"`               // 航线ID
	Seq       int32          `gorm:"column:seq;not null;comment:执行序号" json:"seq"`                         // 执行序号
	Action    string         `gorm:"column:action;not null;comment:动作" json:"action"`                     // 动作
	WaitSec   float64        `gorm:"column:wait_sec;not null;default:0.00;comment:等待秒数" json:"wait_sec"`  // 等待秒数
	Params    string         `gorm:"column:params;comment:动作参数JSON" json:"params"`                        // 动作参数JSON
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                    // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                    // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                    // 删除时间
}

// TableName RobotdogRouteTask's table name
func (*RobotdogRouteTask) TableName() string {
	return TableNameRobotdogRouteTask
}
