// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRobotdogWaypoint = "gf_robotdog_waypoint"

// RobotdogWaypoint 机械狗航点
type RobotdogWaypoint struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`        // ID
	TenantID  int32          `gorm:"column:tenant_id;not null;default:1;comment:租户唯一标识" json:"tenant_id"` // 租户唯一标识
	MapID     int64          `gorm:"column:map_id;not null;comment:地图ID" json:"map_id"`                   // 地图ID
	Name      string         `gorm:"column:name;not null;comment:航点名称" json:"name"`                       // 航点名称
	X         float64        `gorm:"column:x;not null;default:0.0000;comment:X坐标" json:"x"`               // X坐标
	Y         float64        `gorm:"column:y;not null;default:0.0000;comment:Y坐标" json:"y"`               // Y坐标
	Z         float64        `gorm:"column:z;not null;default:0.0000;comment:Z坐标" json:"z"`               // Z坐标
	Yaw       float64        `gorm:"column:yaw;not null;default:0.00;comment:航向角" json:"yaw"`             // 航向角
	Remark    string         `gorm:"column:remark;not null;comment:备注" json:"remark"`                     // 备注
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                    // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                    // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                    // 删除时间
}

// TableName RobotdogWaypoint's table name
func (*RobotdogWaypoint) TableName() string {
	return TableNameRobotdogWaypoint
}
