// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRobotdogTask = "gf_robotdog_task"

// RobotdogTask 机械狗任务
type RobotdogTask struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`          // ID
	TenantID   int32          `gorm:"column:tenant_id;not null;default:1;comment:租户唯一标识" json:"tenant_id"`   // 租户唯一标识
	TaskID     string         `gorm:"column:task_id;not null;comment:任务编号" json:"task_id"`                   // 任务编号
	DogID      int64          `gorm:"column:dog_id;not null;comment:机械狗ID" json:"dog_id"`                    // 机械狗ID
	RouteID    int64          `gorm:"column:route_id;not null;comment:航线ID" json:"route_id"`                 // 航线ID
	WaypointID int64          `gorm:"column:waypoint_id;not null;comment:航点ID" json:"waypoint_id"`           // 航点ID
	Type       string         `gorm:"column:type;not null;default:route;comment:任务类型:route/nav" json:"type"` // 任务类型:route/nav
	Action     string         `gorm:"column:action;not null;comment:动作" json:"action"`                       // 动作
	Status     string         `gorm:"column:status;not null;default:running;comment:状态" json:"status"`       // 状态
	Progress   int32          `gorm:"column:progress;not null;comment:进度" json:"progress"`                   // 进度
	Message    string         `gorm:"column:message;not null;comment:消息" json:"message"`                     // 消息
	CreatedAt  time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                      // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                      // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                      // 删除时间
}

// TableName RobotdogTask's table name
func (*RobotdogTask) TableName() string {
	return TableNameRobotdogTask
}
