// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRobotdogDog = "gf_robotdog_dog"

// RobotdogDog 机械狗
type RobotdogDog struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                        // ID
	TenantID  int32          `gorm:"column:tenant_id;not null;default:1;comment:租户唯一标识" json:"tenant_id"`                 // 租户唯一标识
	Name      string         `gorm:"column:name;not null;comment:机械狗名称" json:"name"`                                      // 机械狗名称
	Sn        string         `gorm:"column:sn;not null;comment:机械狗序列号" json:"sn"`                                         // 机械狗序列号
	Model     string         `gorm:"column:model;not null;comment:型号" json:"model"`                                       // 型号
	Status    string         `gorm:"column:status;not null;default:offline;comment:状态:online/offline/busy" json:"status"` // 状态:online/offline/busy
	MaxSpeed  float64        `gorm:"column:max_speed;not null;default:0.00;comment:最大速度" json:"max_speed"`                // 最大速度
	Battery   int32          `gorm:"column:battery;not null;comment:电量" json:"battery"`                                   // 电量
	StreamURL string         `gorm:"column:stream_url;not null;comment:视频播放地址" json:"stream_url"`                         // 视频播放地址
	RtspURL   string         `gorm:"column:rtsp_url;not null;comment:RTSP地址" json:"rtsp_url"`                             // RTSP地址
	MapID     int64          `gorm:"column:map_id;not null;comment:默认地图ID" json:"map_id"`                                 // 默认地图ID
	PtzID     int64          `gorm:"column:ptz_id;not null;default:0;comment:绑定云台ID" json:"ptz_id"`                       // 绑定云台ID
	UdpHost   string         `gorm:"column:udp_host;not null;comment:UDP主机地址" json:"udp_host"`                            // UDP主机地址
	UdpPort   int32          `gorm:"column:udp_port;not null;comment:UDP端口" json:"udp_port"`                              // UDP端口
	Remark    string         `gorm:"column:remark;not null;comment:备注" json:"remark"`                                     // 备注
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                    // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                    // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName RobotdogDog's table name
func (*RobotdogDog) TableName() string {
	return TableNameRobotdogDog
}
