// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRobotdogRoute = "gf_robotdog_route"

// RobotdogRoute 机械狗航线
type RobotdogRoute struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                             // ID
	TenantID  int32          `gorm:"column:tenant_id;not null;default:1;comment:租户唯一标识" json:"tenant_id"`                      // 租户唯一标识
	DogID     int64          `gorm:"column:dog_id;not null;comment:机械狗ID" json:"dog_id"`                                       // 机械狗ID
	Name      string         `gorm:"column:name;not null;comment:航线名称" json:"name"`                                            // 航线名称
	Status    string         `gorm:"column:status;not null;default:draft;comment:状态:draft/ready/published" json:"status"`      // 状态:draft/ready/published
	RunStatus string         `gorm:"column:run_status;not null;default:idle;comment:执行状态:idle/running/done" json:"run_status"` // 执行状态:idle/running/done
	Remark    string         `gorm:"column:remark;not null;comment:备注" json:"remark"`                                          // 备注
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                         // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                         // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                         // 删除时间
}

// TableName RobotdogRoute's table name
func (*RobotdogRoute) TableName() string {
	return TableNameRobotdogRoute
}
