// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRobotdogMap = "gf_robotdog_map"

// RobotdogMap 机械狗点云地图
type RobotdogMap struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`        // ID
	TenantID   int32          `gorm:"column:tenant_id;not null;default:1;comment:租户唯一标识" json:"tenant_id"` // 租户唯一标识
	Name       string         `gorm:"column:name;not null;comment:地图名称" json:"name"`                       // 地图名称
	Format     string         `gorm:"column:format;not null;default:pcd;comment:格式" json:"format"`         // 格式
	URL        string         `gorm:"column:url;not null;comment:资源地址" json:"url"`                         // 资源地址
	PreviewURL string         `gorm:"column:preview_url;not null;comment:预览地址" json:"preview_url"`         // 预览地址
	OriginX    float64        `gorm:"column:origin_x;not null;default:0.0000;comment:原点X" json:"origin_x"` // 原点X
	OriginY    float64        `gorm:"column:origin_y;not null;default:0.0000;comment:原点Y" json:"origin_y"` // 原点Y
	OriginZ    float64        `gorm:"column:origin_z;not null;default:0.0000;comment:原点Z" json:"origin_z"` // 原点Z
	Scale      float64        `gorm:"column:scale;not null;default:1.0000;comment:比例" json:"scale"`        // 比例
	CreatedAt  time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                    // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                    // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                    // 删除时间
}

// TableName RobotdogMap's table name
func (*RobotdogMap) TableName() string {
	return TableNameRobotdogMap
}
